bcgov/met-public

- sonar-project.properties
removed a few settings and added new
> update sonar cloud properties

- met-api/.pylintrc
- met-api/requirements.txt
- met-web/.eslintrc.js
- met-web/.prettierrc.js
- met-web/package-lock.json
- met-web/package.json
Adds ESLint and prettier configuration to met-web
Adds Pylint and configuration to met-api
Pending:
Fixing current errors (this will change a lot of files and will be done in between sprints to avoid conflicts)
Github checks for the lint errors
> Setup ESLint and Pylint

- met-web/.eslintrc.js
- met-web/.prettierrc.js
- met-web/src/components/Login/loginSlice.ts
- met-web/src/components/common/http-common.ts.ts
- met-web/src/components/common/index.ts
- met-web/src/config.ts
- met-web/src/constants/constants.ts
- met-web/src/constants/tenantConstants.ts
- met-web/src/constants/types.ts
- met-web/src/hooks.ts
- met-web/src/models/engagement.ts
- met-web/src/react-formio.d.ts
- met-web/src/routes/types.ts
- met-web/src/services/EngagementService.ts
- met-web/src/services/UserServices.ts
- met-web/src/services/engagementSlice.ts
- met-web/src/services/types.ts
- met-web/src/services/userSlice.ts
- met-web/src/store.ts
- met-web/src/styles/Theme.ts
Fixes all automated lint errors and warnings
> Automated lint fix

- met-api/src/met_api/__init__.py
- met-api/src/met_api/config.py
- met-api/src/met_api/models/db.py
- met-api/src/met_api/models/default_method_result.py
- met-api/src/met_api/models/engagement.py
- met-api/src/met_api/models/engagement_status.py
- met-api/src/met_api/models/user.py
- met-api/src/met_api/resources/__init__.py
- met-api/src/met_api/resources/engagement.py
Ran make lint, and implemented the feasible fixes
> fix lint issues in backend

- .github/workflows/met-api-ci.yml
- met-api/src/met_api/utils/util.py
*Issue #:*
https://github.com/bcgov/met-public/issues/42
- Added API CI
- Fixed an issue with CORS urls being null
> Github Action CI for API Layer

- met-api/Dockerfile
- met-api/docker-entrypoint.sh
- met-api/src/met_api/__init__.py
- met-api/wsgi.py
*Issue #:*
- Changed docker file and added a docker entry point file
- change python starting
> Python api fixes

- met-api/src/met_api/resources/engagement.py
*Issue #:*
https://github.com/bcgov/met-public/issues/188
- Make Get engagements endpoints public
> Make get engagements public

- met-api/tests/utilities/factory_scenarios.py
*Issue #:*
https://github.com/bcgov/met-public/issues/246
- Update rich text fields with json string
> Update rich text fields in the engagement unit test

- met-api/src/met_api/models/engagement.py
- met-api/src/met_api/models/user.py
- met-api/src/met_api/schemas/Engagement.py
- met-api/src/met_api/services/engagement_service.py
- met-web/src/components/engagement/form/ActionContext.tsx
- met-web/src/components/engagement/form/EngagementForm.tsx
- met-web/src/components/engagement/view/ActionContext.tsx
- met-web/src/models/engagement.ts
- met-web/src/models/status.ts
- met-web/src/routes/LandingPage/Table/index.tsx
*Issue #216*
https://github.com/bcgov/met-public/issues/#216
Fix engagement draft bug
> Engagement Table Fix

- met-web/src/components/imageUpload/index.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/258
- Fix remove image button
> Fix remove image in engagement form not working

- met-web/src/routes/LandingPage/Table/index.tsx
*Issue #261 & #260 :*
https://github.com/bcgov/met-public/issues/#261
https://github.com/bcgov/met-public/issues/#260
Fix SearchBar bugs that occur when searching.
> Fix SearchBar Bugs

- met-api/migrations/versions/ec504565fab3_update_status_and_user.py
- met-api/src/met_api/resources/engagement.py
- met-web/src/components/engagement/form/ActionContext.tsx
- met-web/src/components/engagement/form/EngagementForm.tsx
- met-web/src/components/engagement/form/types.ts
- met-web/src/components/engagement/view/ActionContext.tsx
- met-web/src/services/engagementService/index.ts
- met-web/src/services/userService/index.ts
Refactor callbacks into promises
*Issue #:*
https://github.com/bcgov/met-public/issues/257
Adds Preview button to engagement form
Refactor callbacks into promises
> Add engagement preview button

- met-web/src/components/Form/formio.scss
- met-web/src/components/engagement/banner/Banner.tsx
- met-web/src/components/engagement/banner/BannerWithImage.tsx
- met-web/src/components/engagement/view/SurveyBlock.tsx
- met-web/src/components/engagement/view/index.tsx
- met-web/src/components/survey/submit/SurveySubmitWrapped.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/303
- Make engagement page and survey page work for xs to lg screen sizes
> Make engagement and survey pages mobile friendlty

- met-web/package-lock.json
- met-web/package.json
- met-web/src/App.scss
- met-web/src/components/Form/FormBuilder.tsx
- met-web/src/components/Form/FormSubmit.tsx
- met-web/src/components/Form/formio-bootstrap.scss
- met-web/src/components/Form/formio.scss
- met-web/src/components/LandingPage/LandingPage.tsx
- met-web/src/components/common/Table/index.tsx
- met-web/src/components/engagement/banner/BannerWithImage.tsx
- met-web/src/components/engagement/status/index.tsx
- met-web/src/components/engagement/view/EngagementBanner.tsx
- met-web/src/components/imageUpload/index.tsx
- met-web/src/components/layout/Header/LoggedInHeader.tsx
- met-web/src/components/layout/SideNav/SideNav.tsx
- met-web/src/components/survey/building/index.tsx
- met-web/src/components/survey/create/OptionsForm.tsx
- met-web/src/index.scss
- met-web/src/index.tsx
- met-web/src/styles/Theme.ts
*Issue #:*
https://github.com/bcgov/met-public/issues/271
- Update font family to BC standard
- Fix css clash with bootsrap css import
- pulled bootstrap css manually and updated the clashing css properties
- Changed text color in header to match design
> Fix app font family, bootstrap clash, and text color

- met-api/src/met_api/auth.py
- met-api/src/met_api/constants/status.py
- met-api/src/met_api/models/engagement.py
- met-api/src/met_api/models/survey.py
- met-api/src/met_api/resources/engagement.py
- met-api/src/met_api/resources/survey.py
- met-api/src/met_api/services/engagement_service.py
- met-api/src/met_api/services/submission_service.py
- met-api/src/met_api/services/survey_service.py
- met-api/src/met_api/utils/token_info.py
- met-api/tests/unit/services/test_engagement.py
- met-api/tests/utilities/factory_scenarios.py
- met-web/public/index.html
- met-web/public/snowplow.js
- met-web/src/components/engagement/banner/BannerWithImage.tsx
- met-web/src/components/engagement/form/EngagementForm.tsx
- met-web/src/components/engagement/status/index.tsx
- met-web/src/components/engagement/view/ActionContext.tsx
- met-web/src/components/engagement/view/PreviewBanner.tsx
- met-web/src/components/engagement/view/index.tsx
- met-web/src/components/survey/building/index.tsx
- met-web/src/constants/engagementStatus.ts
*Issue #:*
https://github.com/bcgov/met-public/issues/293
Add Preview Engagement banner when viewing an engagement.
Add feature to publish engagements.
Add checks for published/draft engagements.
> Publish Engagement

- docs/analytics_database_ERD.md
*Issue #:*
https://github.com/bcgov/met-public/issues/277
Adding the ER diagram for analytics database
> adding the analytics database ER diagram file

- met-web/public/snowplow.js
*Issue #:*
https://github.com/bcgov/met-public/issues/265
Fixes duplicated events when refreshing a page.
> Remove duplicated snowplow track page view

- met-web/src/components/common/Table/index.tsx
- met-web/src/components/engagement/banner/BannerWithoutImage.tsx
- met-web/src/components/engagement/view/ActionContext.tsx
- met-web/src/components/engagement/view/EngagementBanner.tsx
- met-web/src/components/engagement/view/EngagementContent.tsx
- met-web/src/components/engagement/view/EngagementView.tsx
- met-web/src/components/engagement/view/PreviewBanner.tsx
- met-web/src/components/engagement/view/SurveyBlock.tsx
- met-web/src/components/engagement/view/index.tsx
- met-web/src/components/engagement/view/types.ts
- met-web/src/routes/AuthenticatedRoutes.tsx
- met-web/src/routes/UnauthenticatedRoutes.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/293
Improvements to Preview Engagement
> Update Preview Engagement

- met-api/src/met_api/config.py
- notify-api/README.md
- openshift/notify-api.bc.yml
- openshift/notify-api.dc.yml
*Issue #:*
https://github.com/bcgov/met-public/issues/309
> Notify service bc and dc added

- met-web/public/snowplow.js
*Issue #:*
https://github.com/bcgov/met-public/issues/265
Move snowplow integration to their production environment
> Move snowplow integration to production

- met-web/src/App.tsx
- met-web/src/components/survey/submit/ActionContext.tsx
- met-web/src/components/survey/submit/InvalidTokenModal.tsx
- met-web/src/components/survey/submit/SurveyForm.tsx
- met-web/src/components/survey/submit/SurveySubmitWrapped.tsx
- met-web/src/components/survey/types.ts
- met-web/src/routes/NotFound.tsx
- met-web/src/routes/UnauthenticatedRoutes.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/307
Adds invalid token modal to survey submit
> Add invalid token modal

- met-api/src/met_api/models/survey.py
- met-api/src/met_api/services/email_verification_service.py
- met-api/src/met_api/services/survey_service.py
- met-api/templates/email_verification.html
*Issue #:*
https://github.com/bcgov/met-public/issues/307
Fixes email verification and template
> Fixes email verification and template

- met-web/src/components/engagement/dashboard/comment/EngagementUserComments.tsx
- met-web/src/components/engagement/dashboard/comment/index.tsx
- met-web/src/components/engagement/dashboard/report/EngagementDashboard.tsx
- met-web/src/components/engagement/dashboard/report/index.tsx
- met-web/src/config.ts
- met-web/src/routes/AuthenticatedRoutes.tsx
- met-web/src/routes/UnauthenticatedRoutes.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/289
> dashboard changes

- met-api/src/met_api/schemas/engagement.py
- met-api/templates/email_verification.html
- met-web/public/snowplow.js
- met-web/src/components/survey/submit/ActionContext.tsx
*Issue #:*
No Issue Created
Fix engagement upcoming status
Fix code smells reported by sonarcloud
> Fix SonarQube code smells

- met-web/src/components/engagement/view/EmailPanel.tsx
- met-web/src/styles/Theme.ts
*Issue #:*
https://github.com/bcgov/met-public/issues/414
- Revert changes to body2 in theme
> Revert body2 changes

- met-web/src/components/LandingPage/LandingPage.tsx
- met-web/src/components/Login/index.tsx
- met-web/src/components/comments/admin/review/CommentReview.tsx
- met-web/src/components/comments/admin/reviewListing/index.tsx
- met-web/src/components/comments/admin/textListing/index.tsx
- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/dashboard/comment/EngagementUserComments.tsx
- met-web/src/components/engagement/dashboard/report/EngagementDashboard.tsx
- met-web/src/components/engagement/form/AddSurveyBlock.tsx
- met-web/src/components/engagement/form/EngagementForm.tsx
- met-web/src/components/engagement/view/EmailPanel.tsx
- met-web/src/components/engagement/view/EngagementBanner.tsx
- met-web/src/components/engagement/view/FailurePanel.tsx
- met-web/src/components/engagement/view/PreviewBanner.tsx
- met-web/src/components/engagement/view/SuccessPanel.tsx
- met-web/src/components/engagement/view/SurveyBlock.tsx
- met-web/src/components/imageUpload/index.tsx
- met-web/src/components/survey/building/index.tsx
- met-web/src/components/survey/create/CreateOptions.tsx
- met-web/src/components/survey/create/LinkOptions.tsx
- met-web/src/components/survey/create/OptionsForm.tsx
- met-web/src/components/survey/listing/index.tsx
- met-web/src/components/survey/submit/InvalidTokenModal.tsx
- met-web/src/components/survey/submit/SurveyForm.tsx
- met-web/src/styles/Theme.ts
- met-web/tests/unit/components/test.test.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/354
- Update hover effect and text transform for primary and secondary buttons
> Make primary and secondary buttons BV Gov standard

- met-web/src/components/comments/admin/reviewListing/index.tsx
*Issue #424:*
*Description of changes:#424*
> Read All Comments fix

- met-web/src/components/engagement/banner/BannerWithoutImage.tsx
- met-web/src/components/engagement/view/PreviewBanner.tsx
- met-web/src/styles/Theme.ts
*Issue #422 :*
- Added Icons to the Preview Banner
- Fixed some of the spacing in the Preview Banner
- Changed Preview Banner Background when there is no image 
- Added Preview Banner messages
-Improved Mobile responsiveness
Desktop View:
Mobile Preview: 
> Preview Banner changes

- met-web/src/components/engagement/dashboard/comment/EngagementComments.tsx
- met-web/src/components/engagement/dashboard/report/EngagementDashboard.tsx
- met-web/src/components/engagement/dashboard/report/ReportBanner.tsx
- met-web/src/routes/AuthenticatedRoutes.tsx
*Issue #:*
- Make dashboard component independent of Engagement View component
> Remove dashboard page reliance on engagement view context

- met-api/migrations/versions/ba02399c821c_add_closed_status.py
- met-api/src/met_api/config.py
- met-api/src/met_api/services/engagement_service.py
- met-api/src/met_api/utils/template.py
- met-api/templates/email_engagement_closeout.html
- met-cron/config.py
- met-cron/tasks/met_closeout.py
- notify-api/src/notify_api/services/email/email_ches_notify.py
- notify-api/src/notify_api/services/email/email_gc_notify.py
*Issue #:*
https://github.com/bcgov/met-public/issues/383
Fixes notify api and what we heard report
> What we heard report Fixes

- met-api/src/met_api/models/engagement.py
- met-api/templates/email_engagement_closeout.html
- met-cron/tasks/met_closeout.py
*Issue #:*
https://github.com/bcgov/met-public/issues/383
Fixes query with end date
> Fixes engagement closeout query

- met-cron/migrations/versions/c03b11293c59_etl_models_redone.py
- met-cron/src/met_cron/models/__init__.py
- met-cron/src/met_cron/models/user_details.py
> renamed user to UserDetails

- met-api/src/met_api/models/engagement.py
- met-cron/tasks/met_closeout.py
- openshift/README.md
- openshift/api.bc.yml
- openshift/api.dc.yml
- openshift/cron.bc.yml
- openshift/cron.dc.yml
- openshift/deploy.sh
- openshift/notify-api.bc.yml
- openshift/notify-api.dc.yml
- openshift/web.dc.yml
*Issue #:*
https://github.com/bcgov/met-public/issues/383
Updated openshift documentation
> Updated openshift documentation

- met-web/src/components/engagement/view/PreviewBanner.tsx
*Issue #460 *
-fixed image icon not showing up
-added responsive spacing
> preview banner bug fix & spacing fix

- met-api/src/met_api/models/survey.py
- met-api/src/met_api/schemas/engagement.py
- met-web/src/components/LandingPage/LandingPage.tsx
- met-web/src/components/survey/listing/index.tsx
- met-web/src/models/engagement.ts
- met-web/src/models/survey.ts
> Add response count to engagement table & table cleanup

- met-cron/tasks/met_closeout.py
- openshift/README.md
- openshift/deploy.sh
- openshift/met-analytics.bc.yml
- openshift/redash/Chart.yaml
- openshift/redash/charts/redis-exporter/Chart.yaml
- openshift/redash/charts/redis-exporter/templates/configmap.yaml
- openshift/redash/charts/redis-exporter/templates/service.yaml
- openshift/redash/charts/redis-exporter/templates/statefulset.yaml
- openshift/redash/charts/redis-exporter/values.yaml
- openshift/redash/templates/configmap.yaml
- openshift/redash/templates/deployment.yaml
- openshift/redash/templates/ingress.yaml
- openshift/redash/templates/secret.yaml
- openshift/redash/templates/service.yaml
- openshift/redash/values.yaml
- openshift/web.dc.yml
*Issue #:*
https://github.com/bcgov/met-public/issues/428
Add redash/met-analytics helm charts
> Add Redash/MET analytics templates

- met-web/src/components/engagement/dashboard/comment/CommentsBlock.tsx
- met-web/src/components/engagement/dashboard/comment/EngagementComments.tsx
- met-web/src/components/engagement/dashboard/comment/index.tsx
- met-web/src/components/engagement/form/EngagementFormTabs.tsx
- met-web/src/components/engagement/form/EngagementSettings.tsx
- met-web/src/components/engagement/form/StyledTabComponents.tsx
- met-web/src/routes/AuthenticatedRoutes.tsx
- met-web/src/routes/UnauthenticatedRoutes.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/471
- Import the proper context for the report component
- Add a skeleton
- Fix what we heard button navigation bug
- Change Tabs colors in Engagement Form page
> Fix report component importing wrong context

- met-web/src/components/Form/formio.scss
*Issue #:*
https://github.com/bcgov/met-public/issues/267
- Fix formio tooltip background
- update colors in formio scss
> Fix formio tooltip

- met-cron/requirements.txt
- met-cron/src/met_cron/services/comments_etl_service.py
- met-cron/src/met_cron/services/engagement_etl_service.py
- met-cron/src/met_cron/services/submission_etl_service.py
- met-cron/src/met_cron/services/user_etl_service.py
- met-cron/tasks/met_extractor.py
*Issue #:*
https://github.com/bcgov/met-public/issues/276
> added user details for submission ETL

- met-web/src/components/engagement/view/EmailModal.tsx
- met-web/src/components/engagement/view/EngagementView.tsx
- met-web/src/components/survey/submit/ActionContext.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/357
Add snowplow action events
> Add snowplow track events

- met-web/src/components/homePage/homePage.tsx
- met-web/src/components/layout/Header/EnvironmentBanner.tsx
- met-web/src/components/layout/Header/LoggedInHeader.tsx
- met-web/src/components/layout/Header/LoggedOutHeader.tsx
- met-web/src/routes/UnauthenticatedRoutes.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/406
Add a basic home page
Add the test environment warning banner
> Add basic home page

- met-web/src/components/Form/formio.scss
*Issue #:*
https://github.com/bcgov/met-public/issues/405
- Change formio primary button to gold background
> Update formio button color

- met-api/src/met_api/config.py
- met-api/src/met_api/services/email_verification_service.py
- met-api/src/met_api/services/engagement_service.py
*Issue #:*
https://github.com/bcgov/met-public/issues/477
Fixes the engagement dashboard url in the email link
> Fix engagement dashboard url

- met-web/package.json
- met-web/src/components/engagement/dashboard/report/EngagementDashboard.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/480
Fixes read comments button when engagement is open
> Fixes Read Comments button

- met-web/src/components/layout/SideNav/SideNav.tsx
- met-web/src/components/layout/SideNav/SideNavElements.tsx
- met-web/src/components/layout/SideNav/types.ts
*Issue #:*
https://github.com/bcgov/met-public/issues/292
- Create new method to get active route path
- use above method to highlight menu item in side nav
> Fix side nav menu

- met-web/src/components/engagement/view/EmailPanel.tsx
- met-web/src/components/engagement/view/ThankYouPanel.tsx
*Issue #489 *
https://github.com/bcgov/met-public/issues/489
-Update thank you modal text
-Update email modal text
> modal text update

- met-web/src/components/LandingPage/LandingPage.tsx
- met-web/src/components/survey/listing/index.tsx
*Issue #500 :*
https://github.com/bcgov/met-public/issues/500
-Added search bar functionality to survey page
-Improved search bar so the table updates as the user is typing 
> Fix Survey SearchBar

- met-web/src/components/common/Table/index.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/495
Changes the default sort order from ascending to descending
> Fix default sort order

- met-api/src/met_api/models/engagement.py
*Issue #:*
https://github.com/bcgov/met-public/issues/408
Since its a full update , in a few scenarios , UI doesnt pass the published date and backend updates it to null.
The ideal fix has to be https://github.com/bcgov/met-public/issues/510
> fix for engagement published date disappearing

- met-api/src/met_api/services/comment_service.py
*Issue #:*
https://github.com/bcgov/met-public/issues/487
Allow empty/missing questions during comment extraction 
> Fix conditional question submission

- met-web/src/components/engagement/banner/BannerWithImage.tsx
- met-web/src/components/engagement/banner/BannerWithoutImage.tsx
*Issue #504 :*
https://github.com/bcgov/met-public/issues/504
-Adding small screen header change for responsiveness
-Fixed the size of the description changing
> Fix size changing for banner without image

- docs/Redash_Changes.md
- docs/Redash_Queries.md
- met-web/src/components/engagement/dashboard/report/EngagementDashboard.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/508
1) Added the documentation for changes made on Redash code base
2) Added the documentation for dashboard queries
3) Changes made to access the dashboard using engagement id instead of name.
> include the documentation for redash

- met-web/package-lock.json
- met-web/package.json
*Issue #:*
https://github.com/bcgov/met-public/issues/486
- Fix postal code component in met-formio
- update met-formio version in package.json
> update met formio to fix postal code

- met-web/src/components/engagement/form/EngagementForm.tsx
- met-web/src/components/engagement/form/RichTextEditor.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/491
- Fix alignment of From and To dates in the engagement form page
> Fix alignment of From and To Dates

- met-web/package-lock.json
- met-web/package.json
*Issue #:*
https://github.com/bcgov/met-public/issues/493
- changes happened in https://github.com/bcgov/met-formio/pull/8
- Add ignore for optionsLabelPosition in SimpleRadios component in
- Add ignore for optionsLabelPosition in SimpleCheckbox componen
> Remove optionsLabelPosition for radio and checkbox components

- met-web/src/components/engagement/view/EmailPanel.tsx
*Issue #485 :*
https://github.com/bcgov/met-public/issues/485
-Change Button Order for mobile
> Align Email Modal Buttons for Mobile

- met-web/src/components/survey/create/LinkOptions.tsx
*Issue #484 :*
https://github.com/bcgov/met-public/issues/484
-Update notification text
> Update notification text

- met-api/src/met_api/models/survey.py
- met-web/src/components/survey/building/index.tsx
- met-web/src/components/survey/create/OptionsForm.tsx
- met-web/src/services/surveyService/form/index.ts
*Issue #404 :*
https://github.com/bcgov/met-public/issues/404
-Add survey name changing
-Change survey header size
> Add survey name update and change header size

- met-web/src/components/LandingPage/LandingPage.tsx
- met-web/src/components/survey/listing/index.tsx
*Issue #498 *
https://github.com/bcgov/met-public/issues/498
-Make View Report link to engagement dashboard
> Update View report link

- met-web/src/components/engagement/view/PreviewBanner.tsx
*Issue #460 :*
https://github.com/bcgov/met-public/issues/460
-Add better spacing to the preview banner
> Improve Preview Banner spacing

- met-api/src/met_api/services/engagement_service.py
- met-web/src/components/engagement/form/EngagementForm.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/494
- Add back-end checks for engagement date
- Define a minimum and maximum for the date pickers in the front end
> Add front end and back end checks for engagement dates

- met-web/src/components/engagement/dashboard/report/EngagementDashboard.tsx
- met-web/src/components/engagement/form/ActionContext.tsx
- met-web/src/components/engagement/view/ActionContext.tsx
- met-web/src/components/engagement/view/EmailModal.tsx
- met-web/src/components/survey/submit/ActionContext.tsx
- met-web/src/components/survey/submit/SurveyForm.tsx
- met-web/src/components/survey/submit/SurveySubmitWrapped.tsx
- met-web/src/components/survey/types.ts
- snowplow/action.json
- snowplow/verify_email copy.json
- snowplow/verify_email.json
*Issue #:*
https://github.com/bcgov/met-public/issues/276
Add snowplow custom schemas
Fix public navigation to root when public user
> Add snowplow schemas and Fix navigation to root

- met-web/src/components/survey/building/index.tsx
- met-web/src/components/survey/create/OptionsForm.tsx
*Issue #404 :*
https://github.com/bcgov/met-public/issues/404
-Added edit icon to create survey page
-removed clear icon
> Update Create Survey Icons

- met-web/src/routes/AuthenticatedRoutes.tsx
- met-web/src/routes/UnderConstruction.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/535
- Create an under construction message page
- Show an under construction message for reporting and calendar routes
> Add under construction  / coming soon page

- met-web/src/components/Form/formio.scss
*Issue #:*
https://github.com/bcgov/met-public/issues/492
- Make active formio button dark gold
> Update formio button color when active

- met-web/src/components/engagement/dashboard/report/EngagementDashboard.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/527
Changed the text "What we heard" in the title to "What We Heard"
> Changes on dashboard

- met-web/src/components/engagement/view/EmailPanel.tsx
*Issue #:*
- Update the email modal panel content
> Update email panel content

- met-web/src/components/comments/admin/review/CommentReview.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/548
- Default comment review options to existing approved/rejected value
> Default review comment to existing approved or rejected status

- met-web/src/components/survey/submit/SurveyForm.tsx
*Issue #547 :*
https://github.com/bcgov/met-public/issues/547
-Rearrange order of buttons on mobile
> Rearrange order of buttons on mobile for Survey Submission

- met-web/src/components/LandingPage/LandingPage.tsx
- met-web/src/components/survey/listing/index.tsx
- met-web/tests/unit/components/landingPage.test.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/560
- Fix create engagement button wrapping on smaller screens
- update layout of search bar and create button
> Update search bar and create button layout

- met-web/src/components/comments/admin/reviewListing/index.tsx
- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/banner/BannerWithImage.tsx
- met-web/src/components/engagement/banner/BannerWithoutImage.tsx
- met-web/src/components/engagement/dashboard/comment/CommentsBlock.tsx
- met-web/src/components/engagement/dashboard/report/CommentInfoModal.tsx
- met-web/src/components/engagement/dashboard/report/EngagementDashboard.tsx
- met-web/src/components/engagement/form/AddSurveyBlock.tsx
- met-web/src/components/engagement/form/EngagementForm.tsx
- met-web/src/components/engagement/form/EngagementFormModal.tsx
- met-web/src/components/engagement/form/EngagementSettings.tsx
- met-web/src/components/engagement/view/EmailPanel.tsx
- met-web/src/components/engagement/view/FailurePanel.tsx
- met-web/src/components/engagement/view/PreviewBanner.tsx
- met-web/src/components/engagement/view/SuccessPanel.tsx
- met-web/src/components/engagement/view/SurveyBlock.tsx
- met-web/src/components/engagement/view/ThankYouPanel.tsx
- met-web/src/components/engagement/view/WhoIsListeningWidget.tsx
- met-web/src/components/homePage/homePage.tsx
- met-web/src/components/layout/Header/LoggedInHeader.tsx
- met-web/src/components/layout/Header/LoggedOutHeader.tsx
- met-web/src/components/survey/building/index.tsx
- met-web/src/components/survey/create/OptionsForm.tsx
- met-web/src/components/survey/submit/InvalidTokenModal.tsx
- met-web/src/routes/NotFound.tsx
*Issue #352 , #351 :*
https://github.com/bcgov/met-public/issues/352
https://github.com/bcgov/met-public/issues/351
-Add MetHeader 1,2,3,4 common component
-Add MetBody component
-Replace body and h1,2,3,4 typography variants throughout application for readability
> Standardize Text throughout application

- met-api/src/met_api/models/engagement.py
- met-api/src/met_api/schemas/engagement.py
- met-api/src/met_api/services/engagement_service.py
- met-api/src/met_api/utils/datetime.py
*Issue #:*
https://github.com/bcgov/met-public/issues/555
Fixes engagement closeout logic to include timezone and end of day.
> Fix engagement closeout dates

- met-api/src/met_api/models/comment.py
- met-api/src/met_api/models/engagement.py
- met-api/src/met_api/models/survey.py
- met-api/src/met_api/resources/comment.py
- met-api/src/met_api/resources/engagement.py
- met-api/src/met_api/resources/survey.py
- met-api/src/met_api/services/comment_service.py
- met-api/src/met_api/services/engagement_service.py
- met-api/src/met_api/services/survey_service.py
- met-api/tests/unit/api/test_engagement.py
*Issue #:*
https://github.com/bcgov/met-public/issues/561
- Use paginate for queries
- update resources and services to pass pagination options
> Implement server side pagination for listing resources

- met-cron/cron/crontab
- met-web/src/components/survey/submit/SurveySubmitWrapped.tsx
- openshift/redash/templates/deployment.yaml
- openshift/redash/values.yaml
*Issue #:*
https://github.com/bcgov/met-public/issues/569
Update crontab with default values
> Update Crontab default values

- met-web/src/components/survey/building/index.tsx
*Issue #484 :*
https://github.com/bcgov/met-public/issues/484
-Update Notification success message
> Update Survey Creation Notification  

- met-api/src/met_api/models/comment.py
- met-api/src/met_api/models/data_class.py
- met-api/src/met_api/models/engagement.py
- met-api/src/met_api/models/survey.py
- met-api/src/met_api/resources/comment.py
- met-api/src/met_api/resources/engagement.py
- met-api/src/met_api/resources/survey.py
- met-api/src/met_api/services/comment_service.py
- met-api/src/met_api/services/engagement_service.py
- met-api/src/met_api/services/survey_service.py
- met-api/tests/unit/api/test_engagement.py
*Issue #:*
https://github.com/bcgov/met-public/issues/561
- Solve too many arguments issue in paginated methods
- Add a data class file
- Add a pagination options class in data class to store pagination options
> Add pagination options data class

- met-web/src/components/common/Modals/ConfirmModal.tsx
- met-web/src/components/common/Modals/UpdateModal.tsx
- met-web/src/components/common/constants.ts
- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/banner/BannerWithImage.tsx
- met-web/src/components/engagement/dashboard/report/CommentInfoModal.tsx
- met-web/src/components/engagement/form/AddSurveyBlock.tsx
- met-web/src/components/engagement/form/EngagementForm.tsx
- met-web/src/components/engagement/form/EngagementFormModal.tsx
- met-web/src/components/engagement/view/EmailPanel.tsx
- met-web/src/components/engagement/view/FailurePanel.tsx
- met-web/src/components/engagement/view/SuccessPanel.tsx
- met-web/src/components/engagement/view/ThankYouPanel.tsx
- met-web/src/components/engagement/view/WhoIsListeningWidget.tsx
- met-web/src/components/survey/submit/InvalidTokenModal.tsx
*Issue #584 :*
https://github.com/bcgov/met-public/issues/584
-Add variants to base component
> Make Header tags reflect as h tags in html

- met-web/src/components/comments/admin/review/CommentReview.tsx
- met-web/src/components/comments/admin/review/CommentReviewSkeleton.tsx
- met-web/src/components/common/Modals/ConfirmModal.tsx
- met-web/src/components/common/Modals/UpdateModal.tsx
- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/dashboard/comment/CommentsBlock.tsx
- met-web/src/components/engagement/form/EngagementFormModal.tsx
- met-web/src/components/engagement/view/EmailPanel.tsx
- met-web/src/components/engagement/view/FailurePanel.tsx
- met-web/src/components/engagement/view/PreviewBanner.tsx
- met-web/src/components/engagement/view/SuccessPanel.tsx
- met-web/src/components/imageUpload/index.tsx
- met-web/src/components/survey/submit/SurveyForm.tsx
- met-web/src/routes/UnderConstruction.tsx
*Issue #531 :*
https://github.com/bcgov/met-public/issues/531
> Update Grid Containers

- .github/workflows/deploy.yml
- .github/workflows/met-api-ci.yml
- .github/workflows/met-web-ci.yml
*Issue #:*
https://github.com/bcgov/met-public/issues/599
Adds environment to deployment for reviews/approval
> Update deploy action

- codecov.yaml
- met-api/src/met_api/models/user.py
- met-api/src/met_api/resources/user.py
- met-api/src/met_api/services/user_service.py
- met-api/tests/unit/api/test_user.py
- met-api/tests/unit/models/test_user.py
- met-api/tests/unit/services/test_engagement.py
- met-api/tests/unit/services/test_user.py
- met-api/tests/utilities/factory_scenarios.py
- met-api/tests/utilities/factory_utils.py
*Issue #:*
https://github.com/bcgov/met-public/issues/566
- Added tests for all layers of user classes
- Did a few improvements which was necessary to make the tests pass
> Covered Tests for user related classes

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/met-api-ci.yml
- .github/workflows/met-web-ci.yml
- codecov.yaml
*Issue #:*
https://github.com/bcgov/met-public/issues/625
CI trigger by push
updated codecov commenting
updated pull request template
> Update CI to trigger on merge

- met-api/src/met_api/services/email_verification_service.py
- met-api/src/met_api/services/user_service.py
> Fix for email not working

- met-api/src/met_api/schemas/survey.py
- met-api/tests/unit/services/test_engagement.py
- met-api/tests/unit/services/test_survey.py
- met-api/tests/utilities/factory_scenarios.py
*Issue #:*
https://github.com/bcgov/met-public/issues/644
Add survey creation unit test at service level
> Survey service unit test

- met-api/tests/unit/api/test_email_verification_service.py
- met-api/tests/unit/api/test_survey.py
- met-api/tests/unit/models/test_engagement.py
- met-api/tests/unit/services/test_email_verification_service.py
*Issue #:*
https://github.com/bcgov/met-public/issues/566
PR comments addressed Ref:https://github.com/bcgov/met-public/pull/649
> PR comments addressed and added one test

- met-api/src/met_api/services/__init__.py
- met-api/tests/unit/utils/test_notification.py
*Issue #:*
https://github.com/bcgov/met-public/issues/566
> added is_valid_email test

- postman/Comment.postman_collection.json
- postman/Engagements.postman_collection.json
- postman/Surveys.postman_collection.json
*Issue #588 :*
https://github.com/bcgov/met-public/issues/588
-Add postman collections
> Setup Postman

- met-api/src/met_api/models/engagement.py
- met-api/src/met_api/models/user.py
- met-api/src/met_api/resources/engagement.py
- met-api/src/met_api/schemas/engagement.py
- met-api/src/met_api/services/engagement_service.py
- met-web/package-lock.json
- met-web/package.json
- met-web/src/apiManager/httpRequestHandler/index.ts
- met-web/src/components/engagement/form/ActionContext.tsx
- met-web/src/components/engagement/form/EngagementForm.tsx
- met-web/src/components/engagement/form/types.ts
- met-web/src/services/engagementService/index.ts
- met-web/src/services/engagementService/types.ts
- met-web/src/utils/index.ts
- met-web/tests/unit/components/engagementForm.test.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/510
- validate engagement form data with the schema
- dynamically update fields in the back-end
- partially load data in engagement schema
- Only send changed data in front for update
> Replace PUT command with PATCH for updating engagement

- met-api/src/met_api/resources/submission.py
- met-api/src/met_api/schemas/schemas/submission.json
- met-api/src/met_api/schemas/utils.py
- met-api/src/met_api/services/submission_service.py
- met-api/tests/unit/api/test_submission.py
- met-api/tests/utilities/factory_utils.py
> Schema validations added

- met-api/migrations/versions/224b70277ac4_alter_commenttype.py
*Issue #:*
https://github.com/bcgov/met-public/issues/337
Fix migration issue not running in deployment pods.
> Fix alter feedback migration

- met-web/src/components/engagement/banner/BannerWithImage.tsx
- met-web/src/components/engagement/banner/BannerWithoutImage.tsx
*Issue #351 :*
https://github.com/bcgov/met-public/issues/351
> Header updates

- met-web/src/components/feedback/listing.tsx
*Issue #701 :*
https://github.com/bcgov/met-public/issues/701
-Fix Pagination total
> Feedback pagination total bug

- met-api/src/met_api/config.py
- met-api/src/met_api/schemas/schemas/submission.json
- met-api/tests/unit/api/test_submission.py
*Issue #:*
https://github.com/bcgov/met-public/issues/711
Fixes email paths
Fixes submission schema validation
> Fixes email paths and submission schema validation

- met-web/src/components/survey/submit/ActionContext.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/711
Fix redirect after submit
> Fix engagement path after submit

- met-web/src/components/common/Modals/Feedback/constants.tsx
- met-web/src/components/common/Modals/Feedback/index.tsx
- met-web/src/components/feedback/listing.tsx
> Cleanup Feedback Code

- postman/MET.postman_collection.json
*Issue #706 :*
https://github.com/bcgov/met-public/issues/706
-intergrated feedback routes into postman(create and fetch request)
-added feedback environment variables to the MET collection
> add feedback collection to postman

- met-web/src/components/common/Table/index.tsx
- met-web/src/components/feedback/listing.tsx
- met-web/tests/unit/components/feedbackListing.test.tsx
*Issue #699 :*
https://github.com/bcgov/met-public/issues/699
-Add feedback listing unit test
> Add unit test for feedback listing

- .github/workflows/zap-scan.yml
*Issue #:*
https://github.com/bcgov/met-public/issues/596
Add new github action for owasp zap security scan
> Add Github action. OWASP ZAP Scan

- met-api/src/met_api/models/comment.py
- met-api/src/met_api/models/db.py
- met-api/src/met_api/models/email_verification.py
- met-api/src/met_api/models/submission.py
- met-api/src/met_api/services/comment_service.py
- met-api/src/met_api/services/email_verification_service.py
- met-api/src/met_api/services/submission_service.py
Issue #:
https://github.com/bcgov/met-public/issues/396
Add support for scoped db sessions
Change submission to use scoped session
> Add DB transaction support

- met-web/nginx.conf
> Update content security policy

- met-web/nginx.conf
> Fix nginx csp

- met-web/nginx.conf
> Fixes nginx script and style src

- met-web/nginx.conf
- met-web/public/index.html
> Remove unused font

- met-web/nginx.conf
- met-web/src/components/Form/formio.scss
*Issue #:*
Fix formio css import
> Fix formio css import

- met-web/nginx.conf
*Issue #:*
Fix connect-src CSP
> Fix connect-src CSP

- met-web/nginx.conf
> Fis style-src CSP

- met-web/package.json
*Issue #:*
Fix unsafe-eval CSP
> Fix unsafe-eval CSP

- met-web/src/components/survey/building/index.tsx
> Fix build after CSP changes

- met-web/src/components/survey/building/index.tsx
- met-web/src/index.tsx
*Issue #:*
Update formio noeval location
> Update formio noeval location

- met-web/nginx.conf
*Issue #:*
Disable trace and options methods
> Disable trace and options methods

- met-api/src/met_api/models/db.py
- met-api/src/met_api/services/email_verification_service.py
- met-api/tests/unit/services/test_submission.py
*Issue #:*
https://github.com/bcgov/met-public/issues/396
Add unit tests for submission service
> Create submission unit tests

- met-api/migrations/versions/c19bc1af9f2b_alter_engagement_add_scheduled.py
- met-api/src/met_api/models/engagement.py
- met-api/src/met_api/services/engagement_service.py
- met-cron/Makefile
- met-cron/cron/crontab
- met-cron/invoke_jobs.py
- met-cron/run_met_publish.sh
- met-cron/tasks/met_publish.py
*Issue #:*
Add publish engagement cron job
> Add publish engagement cron job

- met-api/src/met_api/schemas/engagement.py
- met-web/src/components/common/Modals/Schedule/index.tsx
- met-web/src/components/engagement/banner/BannerWithImage.tsx
- met-web/src/components/engagement/banner/BannerWithoutImage.tsx
- met-web/src/components/engagement/view/ActionContext.tsx
> engagement scheduling bug fix

- met-api/src/met_api/models/engagement.py
*Issue #:*
Fixes engagement publish function where time was being stripped off
> Fix publish scheduled engagements date

- met-api/src/met_api/schemas/engagement.py
- met-web/src/components/engagement/view/ActionContext.tsx
> Make engagement status badge consistent

- met-api/src/met_api/models/engagement.py
- met-api/src/met_api/services/engagement_service.py
*Issue #:*
Prevent public users to see scheduled engagement
> Prevent public users to see scheduled engagement

- met-web/src/components/engagement/view/ActionContext.tsx
- met-web/src/components/engagement/view/PreviewBanner.tsx
> Make scheduling exclusive to draft and scheduled engagements

- met-api/src/met_api/services/engagement_service.py
- met-cron/cron/crontab
*Issue #:*
Fix engagement status check for the public user
> Fix engagement status check for the public user

- met-web/src/components/engagement/banner/BannerWithImage.tsx
- met-web/src/components/engagement/banner/BannerWithoutImage.tsx
- met-web/src/components/engagement/view/ActionContext.tsx
- met-web/src/components/engagement/view/PreviewBanner.tsx
> Update Preview Banner

- met-web/src/components/common/Modals/Schedule/index.tsx
- met-web/src/components/engagement/view/PreviewBanner.tsx
*Issue #800 :*
https://github.com/bcgov/met-public/issues/800
> Prevent scheduling an engagement after it ends

- met-web/src/components/common/Modals/Schedule/index.tsx
- met-web/tests/unit/components/scheduleModal.test.tsx
*Issue #792  :*
https://github.com/bcgov/met-public/issues/792
-Add unit testing
> schedule Modal testing

- openshift/README.md
*Issue #:*
https://github.com/bcgov/met-public/issues/224
Add documentation on how to deploy patroni
> Update Patroni Openshift Docs

- met-api/src/met_api/resources/__init__.py
- met-api/src/met_api/resources/value_component.py
- met-web/package-lock.json
- met-web/package.json
- met-web/public/index.html
- met-web/src/App.tsx
- met-web/src/components/Form/FormBuilderOptions.ts
- met-web/src/components/Form/formio.scss
- met-web/src/index.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/801
- Create custom checkbox and textarea components in met-formio
- update met-formio version
- add the vc options in the formbuilder options under basic
> Add Value Component options to form builder

- met-etl/src/etl_project/services/jobs/met_data_ingestion.py
- met-etl/src/etl_project/services/ops/comments_etl_service.py
- met-etl/src/etl_project/services/ops/engagement_etl_service.py
- met-etl/src/etl_project/services/ops/submission_etl_service.py
- met-etl/src/etl_project/services/ops/survey_etl_service.py
- met-etl/src/etl_project/services/ops/user_etl_service.py
- met-etl/src/etl_project/services/schedules/met_data_ingestion_schedule.py
*Issue #:*
https://github.com/bcgov/met-public/issues/745
ETL for Survey, User Survey Inputs and User Details along with updated job and schedule.
> Dagster etl changes

- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/view/ActionContext.tsx
- met-web/src/components/engagement/view/WhoIsListeningWidget.tsx
- met-web/src/models/widget.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/784
Update who is listening widget to use contact information stored in the engagement.
> Updates to who is listening widget

- met-web/nginx.conf
*Issue #:*
No related issue
Fixes CSP error in DEV
> Update CSP to include fontawesome

- met-web/src/components/engagement/view/PreviewBanner.tsx
*Issue #298 :*
-shorten time string on preview banner
> Preview banner touch ups

- met-web/src/components/engagement/form/EngagementWidgets/ContactInfoPaper.tsx
*Issue #:832*
https://github.com/bcgov/met-public/issues/832
> remove = from contact info paper

- met-api/migrations/versions/7faee53e6759_alter_submission_add_comment_status.py
> Fix migration remove schema

- met-api/src/met_api/resources/value_component.py
- met-web/.gitignore
- met-web/package-lock.json
- met-web/package.json
- met-web/src/components/Form/FormBuilderOptions.ts
*Issue #:*
https://github.com/bcgov/met-public/issues/814
This is parallel with the PR on met-formio https://github.com/bcgov/met-formio/pull/11
- Update met-formio to the rc version with the text area reserved for other option
- Add 'other' Category
> update met-formio and add other option

- met-api/src/met_api/schemas/schemas/contact.json
- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/AddContactDrawer.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/859
Added validation to check if Bio has a maximum limit of 240 characters and removed the minimum length check.
> validation added for bio to be max 240 characters

- met-api/migrations/versions/9f86fdcfb248_add_widget_type_document.py
*Issue #:*
https://github.com/bcgov/met-public/issues/25
Inserting record to widget type table for document widget
> record for document widget type

- met-api/src/met_api/services/widget_service.py
- met-api/tests/unit/services/test_widget.py
- met-api/tests/utilities/factory_scenarios.py
*Issue #:*
https://github.com/bcgov/met-public/issues/867
- Add test for deleting removed widget items
- Add test for creating added widget items
- Add test for resorting widget items
> Add unit tests to widget_item service

- met-web/Dockerfile
- met-web/nginx/docker-entrypoint.sh
- met-web/nginx/nginx.dev.conf
- met-web/nginx/nginx.test.conf
*Issue #:*
https://github.com/bcgov/met-public/issues/778
Makes nginx configuration dynamic
> Make nginx.conf dynamic

- met-api/src/met_api/models/comment.py
- met-api/src/met_api/services/comment_service.py
*Issue #:*
- fix bug in comments public page
> remove survey field from public comment

- met-web/Dockerfile
- met-web/nginx/docker-entrypoint.sh
*Issue #:*
https://github.com/bcgov/met-public/issues/778
Fixes permissions for nginx user
> Update nginx user permissions

- met-api/migrations/versions/e37d79be3a05_added_sort_for_widgets.py
- met-api/src/met_api/constants/widget.py
- met-api/src/met_api/models/widget.py
- met-api/src/met_api/resources/widget.py
- met-api/src/met_api/schemas/widget.py
- met-api/src/met_api/services/widget_service.py
- met-api/tests/unit/api/test_widget.py
- met-api/tests/utilities/factory_scenarios.py
*Issue #:*
- Added sort_index column
- modified logic to increase sort_index while creating a new widget
- Added new endpoint for sorting the widgets
> Added sort_index for widgets

- met-web/src/components/engagement/form/EngagementWidgets/Phases/PhasesForm.tsx
- met-web/src/services/widgetService/index.tsx
- met-web/tests/unit/components/engagementForm.test.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/885
Add unit tests for phases widget
> Phases widget unit test

- met-api/src/met_api/models/engagement.py
*Issue #:*
https://github.com/bcgov/met-public/issues/882
Fixing issue with publishing an engagement
> fix for publishing an engagement

- .github/workflows/met-cron-cd.yml
- .github/workflows/met-cron-ci.yml
- met-web/tests/unit/components/engagementForm.test.tsx
> Fixes cron workflows

- met-cron/requirements.txt
- met-cron/requirements/dev.txt
> Fixes cron CI

- met-api/src/met_api/resources/widget.py
- met-web/src/components/common/Modals/ConfirmModal.tsx
- met-web/src/services/widgetService/index.tsx
- met-web/src/store.ts
*Issue #:*
https://github.com/bcgov/met-public/issues/885
Fixes Phases widget save error
Fixes ConfirmModal warning about unique keys
Fixes/Workaround for non-serializable objects warning
> Fixes general bugs for widgets

- met-web/public/manifest.json
*Issue #:*
https://github.com/bcgov/met-public/issues/916
Fixes the missing manifest file.
> Fixes missing manifest file

- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentFile.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentFolder.tsx
- met-web/src/components/engagement/form/EngagementWidgets/MetWidget.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/AddContactDrawer.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/ContactBlock.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/ContactInfoPaper.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/WhoIsListeningContext.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/WhoIsListeningForm.tsx
- met-web/src/components/engagement/view/WhoIsListeningWidget.tsx
- met-web/src/components/imageUpload/index.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/883
- Improve UI according to comments in https://github.com/bcgov/met-public/issues/883
- Fix unsaved added contacts  disappearing when contact is edited
> UI Improvements and contacts disappearing fix

- met-web/src/components/engagement/view/EngagementView.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/926
- Fix space added between content and survey blocks when widgets block is longer than content block
> Change alignment of blocks for large and small screens

- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentFile.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentFolder.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/FileDrawer.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/162
Reset Document Form after save/cancel
Remove "Drag" indicator from folder/files
> Reset Document Form

- met-web/src/components/engagement/form/EngagementWidgets/MetWidget.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WidgetCardSwitch.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WidgetsBlock.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/885
Makes engagement phases widget fixed at the top.
> Add fixed and sortable widgets

- met-web/tests/unit/components/engagement.test.tsx
- met-web/tests/unit/components/engagementForm.test.tsx
- met-web/tests/unit/components/factory.ts
> Common factory for tests to avoid jest duplication

- met-api/src/met_api/resources/widget_documents.py
- met-api/tests/unit/api/test_comment.py
- met-api/tests/unit/api/test_contact.py
- met-api/tests/unit/api/test_email_verification_service.py
- met-api/tests/unit/api/test_engagement.py
- met-api/tests/unit/api/test_feedback.py
- met-api/tests/unit/api/test_submission.py
- met-api/tests/unit/api/test_survey.py
- met-api/tests/unit/api/test_user.py
- met-api/tests/unit/api/test_widget.py
- met-api/tests/unit/api/test_widget_document.py
- met-api/tests/unit/models/test_widget_documents.py
- met-api/tests/utilities/factory_scenarios.py
*Issue #:*
[https://github.com/bcgov/met-public/issues/<Put the github issue number here>](https://github.com/bcgov/met-public/issues/162)
- added a constant and refactored all files 
- Added a few tests
- handled exception in resources
- removed hard coding of few ids in the tests
> Added a few additional unit tests for widget doc

- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentFile.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentFolder.tsx
- met-web/src/components/engagement/form/EngagementWidgets/MetWidget.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/ContactInfoPaper.tsx
- met-web/src/components/engagement/view/PreviewBanner.tsx
- met-web/src/components/engagement/view/widgets/DocumentWidget.tsx
- met-web/src/components/survey/building/index.tsx
- met-web/src/styles/Theme.ts
*Issue #:*
- Change icon color to #707070
> Change file and folder icons to #707070

- met-web/src/components/engagement/view/widgets/DocumentWidget.tsx
> Fixes icon color

- met-web/src/components/engagement/form/EngagementWidgets/Phases/PhasesForm.tsx
- met-web/src/components/engagement/view/widgets/DocumentWidget.tsx
> Fix phase widget selection

- met-web/src/components/engagement/form/EngagementForm.tsx
> Fix update Engagement button

- met-web/src/components/survey/create/CloneOptions.tsx
- met-web/src/components/survey/create/CreateOptions.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/958
> Fix create and clone survey

- met-web/nginx/nginx.prod.conf
*Issue #:*
https://github.com/bcgov/met-public/issues/325
Add nginx configuration for prod
> Add nginx prod

- met-api/src/met_api/models/widget_documents.py
- met-api/src/met_api/resources/widget_documents.py
- met-api/src/met_api/services/widget_documents_service.py
*Issue #:*
https://github.com/bcgov/met-public/issues/881
- Back end changes for edit/delete documents widget
- The tests are still being worked upon
> backend changes for edit/delete documents widget

- met-web/src/components/layout/Header/EnvironmentBanner.tsx
- openshift/README.md
- openshift/api.dc.yml
- openshift/cron.dc.yml
- openshift/redash/Chart.yaml
- openshift/redash/templates/secret.yaml
- openshift/redash/values.yaml
- openshift/web.dc.yml
*Issue #:*
https://github.com/bcgov/met-public/issues/325
Updated Openshift Documentation
Updated Test Environment Baner
> Updated Openshift Docs

- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentOptionCard.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/StyledTreeItem.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/TreeView.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Phases/PhasesOptionCard.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/WhoIsListeningOptionCard.tsx
- met-web/src/components/engagement/view/widgets/DocumentWidget.tsx
*Issue #951 #953:*
https://github.com/bcgov/met-public/issues/951
https://github.com/bcgov/met-public/issues/953
-Add public tree view
-update widget icons
-update document icons
> Public Document Tree View

- met-web/src/components/common/MetPopper.tsx
- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/view/EngagementView.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/IconBox.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/PhaseBox.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/ReadMoreBox.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/index.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/phaseItems/AppDevReview.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/phaseItems/Decision.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/phaseItems/EarlyEngagement.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/phaseItems/EffectAssessmentRec.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/phaseItems/PostCertificate.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/phaseItems/ProcessPlanning.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/phaseItems/ReadinessDecision.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/670
- Add engagement phases widget in public view
- Add styled popper and arrow components
> Create an engagement phases widget

- met-api/src/met_api/resources/document.py
- met-api/src/met_api/resources/engagement.py
- met-api/src/met_api/resources/survey.py
- met-api/src/met_api/utils/roles.py
- met-api/tests/unit/api/test_engagement.py
- met-api/tests/unit/api/test_survey.py
- met-api/tests/utilities/factory_scenarios.py
*Issue #:*
[[https://github.com/bcgov/met-public/issues/880
- Added changes to support roles
- All end points will be covered in next PR
- created roles in keycloak
> Added annotations to support roles

- met-web/src/App.tsx
- met-web/src/apiManager/endpoints/index.ts
- met-web/src/components/layout/Header/LoggedInHeader.tsx
- met-web/src/components/layout/SideNav/SideNav.tsx
- met-web/src/components/layout/SideNav/SideNavElements.tsx
- met-web/src/components/userManagement/listing/index.tsx
- met-web/src/models/user.ts
- met-web/src/routes/AuthenticatedRoutes.tsx
- met-web/src/services/userService/index.ts
- met-web/tests/unit/components/sidenav.test.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/714
- added the user management listing page
- status for a user and pagination is still work in progress
> user management page

- met-web/src/apiManager/apiSlices/contacts/index.tsx
- met-web/src/apiManager/apiSlices/documents/index.tsx
- met-web/src/apiManager/apiSlices/widgets/index.ts
- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/WhoIsListeningContext.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WidgetDrawerContext.tsx
- met-web/src/components/engagement/view/ActionContext.tsx
- met-web/src/components/engagement/view/widgets/DocumentWidget.tsx
- met-web/src/components/engagement/view/widgets/WhoIsListeningWidget.tsx
- met-web/src/services/contactService/index.tsx
- met-web/src/services/widgetService/DocumentService.tsx/index.tsx
- met-web/src/services/widgetService/index.tsx
- met-web/src/store.ts
- met-web/tests/unit/components/EngagementForm.test.tsx
- met-web/tests/unit/components/EngagementFormDocumentWidget.test.tsx
- met-web/tests/unit/components/engagement.test.tsx
- met-web/tests/unit/components/header.test.tsx
- met-web/tests/unit/components/notification.test.tsx
- met-web/tests/unit/components/scheduleModal.test.tsx
- met-web/tests/unit/components/sidenav.test.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/787
- Add redux RTK Query for documents fetch
- Add redux RTK Query for widgets fetch
- Add redux RTK Query for contacts fetch
> Add RTK Query for documents, widgets, contacts fetches

- met-api/src/met_api/models/widget_documents.py
*Issue #:*
https://github.com/bcgov/met-public/issues/
> Fix met-api unit tests

- met-api/src/met_api/models/user.py
- met-api/src/met_api/resources/user.py
- met-api/src/met_api/schemas/user.py
- met-api/src/met_api/services/user_service.py
- met-api/src/met_api/utils/token_info.py
- met-api/tests/unit/api/test_user.py
- met-api/tests/utilities/factory_scenarios.py
- met-api/tests/utilities/factory_utils.py
*Issue #:*
https://github.com/bcgov/met-public/issues/714
- populated more fields in user table
- Added pagination to get endpoints
- Added tests
> Added pagination to get endpoints

- met-web/src/components/userManagement/listing/index.tsx
- met-web/src/models/user.ts
- met-web/src/services/userService/index.ts
*Issue #:*
https://github.com/bcgov/met-public/issues/714
- Changes for pagination on user management page. 
> front end changes for pagination

- met-web/src/components/engagement/view/widgets/PhasesWidget/IconBox.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/PhaseBoxMobile.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/PhasesWidgetMobile/PhasesWidgetMobile.tsx
- met-web/tests/unit/components/engagement/engagement.test.tsx
- met-web/tests/unit/components/widgets/DocumentWidget.test.tsx
- met-web/tests/unit/components/widgets/PhasesWidget.test.tsx
- met-web/tests/unit/components/widgets/WhoIsListeningWidget.test.tsx
*Issue #888:*
https://github.com/bcgov/met-public/issues/888
-Add close icon 
-make default state for mobile widget accordion collapsed
> Mobile Process Widget Touch Ups

- met-api/migrations/versions/6764af39864e_.py
- met-api/src/met_api/models/user.py
- met-api/src/met_api/services/user_service.py
- met-api/tests/utilities/factory_scenarios.py
*Issue #:*
Fixes users access type
> Fixes users access type

- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentFile.tsx
- met-web/src/components/engagement/view/widgets/DocumentWidget.tsx
> Fixes document widget cache

- met-web/src/components/layout/SideNav/SideNavElements.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1008
Capitalize 'm' in the item "User Management"
> updating the name for user management

- met-web/src/components/comments/admin/textListing/index.tsx
- met-web/src/components/common/Table/index.tsx
- met-web/src/components/common/index.tsx
- met-web/src/components/common/modal.tsx
- met-web/src/components/engagement/view/EngagementBanner.tsx
- met-web/src/components/engagement/view/PreviewBanner.tsx
- met-web/src/components/layout/Header/LoggedOutHeader.tsx
- met-web/src/components/survey/create/OptionsForm.tsx
- met-web/src/components/survey/submit/SurveySubmitWrapped.tsx
- met-web/tests/unit/components/engagement/engagement.test.tsx
> Fixes close preview and removes conditional component

- .github/workflows/met-etl-cd.yml
- openshift/deploy.sh
*Issue #:*
https://github.com/bcgov/met-public/issues/1011
Add continuous deployment for Dagster ETL
> Add dagster etl CD

- met-web/src/components/survey/building/index.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1010
- Add a toggle to make form builder multi page
> Add toggle for multi page survey form

- met-web/src/models/engagementPhases.tsx
*Issue #992 :*
https://github.com/bcgov/met-public/issues/992
-Remove engagement icon for readiness decision
-Rename one of the engagements
Reason: Marie Anik's request
> Engagement Phase Tweaks

- met-web/src/components/common/index.tsx
- met-web/src/components/layout/Header/EnvironmentBanner.tsx
- met-web/src/components/layout/SideNav/SideNav.tsx
*Issue #:*
Update side bar layout
> Updated sidebar

- met-api/src/met_api/services/comment_service.py
- met-web/src/components/Form/FormSubmit.tsx
- met-web/src/components/Form/formio.scss
- met-web/src/components/Form/types.ts
- met-web/src/components/survey/submit/SurveyForm.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/978
- Enable submission for multi-page survey
- handle comments extraction
> Allo multi page form submission and handle extract comments

- met-web/src/components/engagement/form/EngagementWidgets/Phases/PhasesForm.tsx
- met-web/src/models/engagementPhases.tsx
-Update dropdown for engagement phases to update the recommendation text
-Requested by Marie Anik
> Update Dropdown Options for Phases Form

- met-web/package-lock.json
- met-web/package.json
- met-web/src/components/Form/FormBuilderOptions.ts
*Issue #:*
https://github.com/bcgov/met-public/issues/815
- change naming of value component to category component
- update met-formio version
> change naming of value component to category component

- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/EngagementPhase.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/LearnMoreBox.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/PhaseBox.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/PhasesWidgetMobile/EngagementPhaseMobile.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/PhasesWidgetMobile/PhaseBoxMobile.tsx
- met-web/src/models/engagementPhases.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/979
- Implement design tweets according to comment in the above task
> Implement tweaks for engagement phases widget

- met-api/src/met_api/services/email_verification_service.py
*Issue #:*
Changes to validating the email verification expiration logic
> Update Email Verification Expiration Logic

- met-web/src/components/engagement/form/AddSurveyBlockTabs.tsx
*Issue #:*
https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&sinceLeakPeriod=true&types=BUG&id=bcgov_met-public&open=AYVZ8lK8lHcyP0Z-AFqp
> Fix github bug forEach instead of map

- met-web/src/components/common/Modals/DayCalculator/constants.tsx
- met-web/src/components/common/Modals/DayCalculator/dayZeroRules.tsx
- met-web/src/components/common/Modals/DayCalculator/index.tsx
- met-web/src/components/engagement/form/EngagementForm.tsx
- met-web/tests/unit/components/engagement/EngagementForm.test.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1031
Added a new modal for day calculator on the engagement form.
> Day Calculator

- met-web/src/components/comments/admin/review/CommentReview.tsx
- met-web/src/components/engagement/form/AddSurveyBlockTabs.tsx
- met-web/src/components/survey/edit/EditForm.tsx
- met-web/src/components/survey/edit/FormWrapped.tsx
> Fix back to engagement link

- met-web/src/components/common/Modals/Schedule/index.tsx
*Issue #:*
Fixing the issue with schedule an engagement
Fixing the issue with schedule an engagement
> fix for schedule an engagement

- met-web/src/components/engagement/view/ActionContext.tsx
*Issue #1061 :*
https://github.com/bcgov/met-public/issues/1061
-Fix submission status only display upcoming 
> Fix submission status bug

- met-web/src/components/Form/formio.scss
*Issue #:*
https://github.com/bcgov/met-public/issues/1010
- Update colors of Cancel, Previous, Next, Submit buttons to be government standard
> Update multi-page survey navigation buttons

- met-web/src/components/common/Modals/DayCalculator/constants.tsx
- met-web/src/components/common/Modals/DayCalculator/index.tsx
- met-web/tests/unit/components/engagement/EngagementForm.test.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1031
Fixing the formatting issues for day calculator modal. Changed to look like below:
> day calculator formatting changes

- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/WhoIsListeningForm.tsx
*Issue #989 :*
https://github.com/bcgov/met-public/issues/989
-Add who is listening and divider to widget form
> Add Who is Listening to widget form

- met-api/src/met_api/resources/user.py
- met-api/src/met_api/services/user_service.py
- met-api/src/met_api/utils/enums.py
- met-api/src/met_api/utils/token_info.py
- met-api/tests/utilities/factory_scenarios.py
> changed login check

- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/CreateFolderForm.tsx
- met-web/tests/unit/components/widgets/DocumentWidget.test.tsx
*Issue #1027 :*
https://github.com/bcgov/met-public/issues/1027
-Change button order
-edit button styling
> Document Folder UI Tweaks

- met-api/src/met_api/config.py
- met-api/src/met_api/resources/user.py
- met-api/src/met_api/services/user_service.py
- openshift/api.dc.yml
*Issue #:*
https://github.com/bcgov/met-public/issues/1018
Integrate new user flow with user management changes
Update request access email link
> Update request access email link

- met-api/migrations/versions/242c9f0364df_.py
- met-api/src/met_api/models/widget.py
- met-api/src/met_api/models/widget_item.py
- met-api/src/met_api/services/widget_service.py
- met-web/src/components/engagement/form/EngagementWidgets/Subscribe/SubscribeOptionCard.tsx
*Issue #680:*
https://github.com/bcgov/met-public/issues/680 
-Add migrations for subscribe widget
> add migrations for new subscribe widget

- met-web/src/components/comments/admin/review/CommentReview.tsx
- met-web/src/components/comments/admin/reviewListing/index.tsx
- met-web/src/constants/commentStatus.ts
- met-web/src/constants/staffNoteType.ts
- met-web/src/models/staffNote.ts
- met-web/src/models/surveySubmission.ts
- met-web/src/services/submissionService/index.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1016
- Changes made to handle internal note for any comment review reason3
- Changes made to handle rejection review comments
- Added additional review reason
- Added the option to not send rejection email
> front end changes for review comments updates

- met-api/src/met_api/services/submission_service.py
*Issue #:*
https://github.com/bcgov/met-public/issues/1029
Changes made to pass additional arguments to the rejection email template.
> changes for update rejected email content

- met-api/src/met_api/config.py
> Added prop exception true to fix tests

- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/AddContactDrawer.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/991
- Reverting prior changes as it was preventing changing the image for an existing contact
- Added new change to handle the image for editing a contact
> fix for contact image

- met-web/src/components/common/Modals/ConfirmModal.tsx
- met-web/src/components/common/Modals/EmailModal.tsx
- met-web/src/components/common/Modals/UpdateModal.tsx
- met-web/src/components/common/Modals/types.tsx
- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/dashboard/report/EngagementDashboard.tsx
- met-web/src/components/engagement/form/AddSurveyBlock.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentFile.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentFolder.tsx
- met-web/src/components/engagement/form/EngagementWidgets/MetWidget.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Subscribe/SubscribeOptionCard.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WidgetsBlock.tsx
- met-web/src/components/engagement/view/ActionContext.tsx
- met-web/src/components/engagement/view/widgets/Subscribe/SubscribeWidget.tsx
- met-web/src/services/notificationModalService/types.ts
#680 
https://github.com/bcgov/met-public/issues/#680
-Change Sign up to Sign Up
-Make subscribe modal subtext bold:
To do this we added the subtext prop to all modal subtexts for future use cases
> updates to subscribe widget & modal sub text

- met-web/src/components/engagement/form/EngagementWidgets/Documents/CreateFolderForm.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/WhoIsListeningForm.tsx
*Issue #1027 :*
https://github.com/bcgov/met-public/issues/1027
-Fix spacing for responsiveness
-Remove old padding on buttons
> UX updates to buttons & Document widget

- met-api/tests/utilities/factory_scenarios.py
*Issue #:*
Fixed a test which was breaking
> Added missing role in the tests - Fix a failing test

- met-web/src/components/engagement/form/EngagementForm.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/CreateFolderForm.tsx
- met-web/tests/unit/components/engagement/EngagementForm.test.tsx
- met-web/tests/unit/components/widgets/DocumentWidget.test.tsx
*Issue #1069:*
https://github.com/bcgov/met-public/issues/1069
-Change create/update engagement text to save
-Change preview & save engagement text to preview
> Update Engagement Form names

- met-web/src/components/common/Table/index.tsx
- met-web/src/components/dashboard/EngagementsAccordion.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1022
Changes made to handle empty table while data is loading
> updated logic to handle table loading

- met-api/src/met_api/models/membership.py
*Issue #:*
https://github.com/bcgov/met-public/issues/1151
- change lazy from select to joined
> Fix user not being loaded when member is fetched

- met-api/src/met_api/models/membership.py
- met-web/src/components/engagement/form/EngagementFormTabs/AddTeamMemberModal.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/EngagementTabsContext.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/EngagementUserManagement.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/TeamMemberListing.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1151
- Add a manual join with User model
- Load team members table after adding team member
> Fix team member name appears as undefined

- met-web/src/components/dashboard/EngagementList.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1019
Updated borders in dashboard page.
> Dashboard UI Updates

- met-web/src/components/comments/admin/review/CommentReview.tsx
- met-web/src/components/comments/admin/review/emailPreview/EmailPreview.tsx
- met-web/src/components/comments/admin/review/emailPreview/EmailTemplates.tsx
*Issue #1017 :*
https://github.com/bcgov/met-public/issues/1017
-Add engagement name to email
-Only display preview for rejected comments
> Email Preview Touch ups

- met-web/src/components/comments/admin/review/CommentReview.tsx
*Issue #1017 :*
https://github.com/bcgov/met-public/issues/1017
-Preview button update
> Preview Button styling update

- met-web/src/components/comments/admin/review/CommentReview.tsx
- met-web/src/components/comments/admin/review/emailPreview/EmailPreview.tsx
- met-web/src/components/comments/admin/review/emailPreview/EmailTemplates.tsx
*Issue #1017:*
https://github.com/bcgov/met-public/issues/1017
-Add more data to email template to match email being sent
> Update email template

- met-web/src/components/comments/admin/review/CommentReview.tsx
- met-web/src/components/comments/admin/review/emailPreview/EmailPreview.tsx
- met-web/src/components/comments/admin/review/emailPreview/EmailTemplates.tsx
*Issue #:1017*
https://github.com/bcgov/met-public/issues/1017
-Edit spacing in modal
> Preview Modal tweaks

- docs/cleanup_space.md
- met-api/src/met_api/constants/engagement_status.py
- met-api/src/met_api/models/engagement.py
- met-api/src/met_api/resources/engagement.py
- met-api/src/met_api/services/engagement_service.py
- met-api/tests/unit/models/test_engagement.py
- met-web/src/components/engagement/listing/AdvancedSearch/SearchComponent.tsx
- met-web/src/components/engagement/listing/AdvancedSearch/SearchTypes.ts
- met-web/src/components/engagement/listing/index.tsx
- met-web/src/constants/engagementStatus.ts
- met-web/src/services/engagementService/index.ts
- met-web/tests/unit/components/engagement/EngagementListing.test.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/572
1) Back end changes to add the filter conditions needed for advanced search
2) Front end changes to add the advanced search feature on engagement listing page
> advanced Search for Engagement listing page

- met-api/src/met_api/models/engagement.py
*Issue #:*
https://github.com/bcgov/met-public/issues/572
> refactored the code into smaller methods

- met-web/src/components/engagement/view/widgets/PhasesWidget/InfoArrow.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/index.tsx
- met-web/src/models/engagementPhases.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1141
- Add first nations arrow below engagement phase boxes
- Add current phase text under title
> Add the "First Nations" Arrow

- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentOptionCard.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Phases/PhasesOptionCard.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Subscribe/SubscribeOptionCard.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/WhoIsListeningOptionCard.tsx
- met-web/src/styles/Theme.ts
*Issue #1103:*
https://github.com/bcgov/met-public/issues/1103
-Remove left padding
-Update icon colors
> Update widget options ui

- met-web/src/components/engagement/form/EngagementFormTabs/AddTeamMemberModal.tsx
- met-web/tests/unit/components/engagement/EngagementFormUserTab.test.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1157
- Update add team member text
> updated add team member text in engagement form

- met-web/src/components/engagement/form/EngagementWidgets/Documents/CreateFolderForm.tsx
*Issue #1116 :*
https://github.com/bcgov/met-public/issues/1116
-Remove state delay for form
> Empty Folder Document Fix

- met-web/package-lock.json
- met-web/package.json
*Issue #:*
https://github.com/bcgov/met-public/issues/1101
https://github.com/bcgov/met-public/issues/1127
- Rename the "Basic" header on top of the questions/survey components
- Change the name of the "Data" tab to "values"
- Make Label field required for checkbox and radio
- Hide the "Search field(s)" search bar
- Reorder formio components
> Formio tweaks

- met-api/src/met_api/models/engagement.py
- met-api/tests/unit/api/test_engagement.py
- met-web/src/components/engagement/listing/AdvancedSearch/SearchComponent.tsx
- met-web/src/components/engagement/listing/AdvancedSearch/SearchComponentMobile.tsx
- met-web/src/components/engagement/listing/index.tsx
- met-web/tests/unit/components/engagement/EngagementListing.test.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/572
Changes to use mui collapse and fix the dates filter
> refactoring code for advanced search

- met-web/src/components/engagement/form/StyledTabComponents.tsx
- met-web/src/styles/Theme.ts
*Issue #1068 :*
https://github.com/bcgov/met-public/issues/1068
-Add consistent borders in MET
> Add consistent borders and shadows in MET

- met-web/src/styles/Theme.ts
*Issue #1214 :*
https://github.com/bcgov/met-public/issues/1214
-Remove fixed height for multiline text fields
> Remove fixed height for multiline text fields

- met-web/src/styles/Theme.ts
*Issue #1068 :*
https://github.com/bcgov/met-public/issues/1068
-Remove the mui tab style
> Remove mui tab style

- met-api/src/met_api/schemas/comment.py
- met-etl/container/dagster/Dockerfile
- met-etl/container/user_code/Dockerfile
- met-etl/src/etl_project/services/ops/submission_etl_service.py
- met-etl/src/etl_project/services/ops/survey_etl_service.py
*Issue #:*
https://github.com/bcgov/met-public/issues/1150
1) Changes made to display the label for a comment on comments review page
2) ETL fixes to pull survey and submission data for a multi page survey
> fix for multi page comments review and etl

- met-web/src/components/engagement/form/EngagementFormTabs/EngagementForm.tsx
- met-web/src/components/imageUpload/index.tsx
*Issue #1152 :*
https://github.com/bcgov/met-public/issues/1152
-Reorder engagement form
> Engagement form reorder

- met-etl/src/etl_project/services/ops/submission_etl_service.py
*Issue #:*
https://github.com/bcgov/met-public/issues/1150
- logic added to exclude comments related to category type question
> etl changes to exclude category comments

- met-web/src/components/comments/admin/reviewListing/index.tsx
- met-web/src/components/comments/admin/textListing/index.tsx
- met-web/src/components/common/Table/index.tsx
- met-web/src/components/engagement/dashboard/comment/CommentTable.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/TeamMemberListing.tsx
- met-web/src/components/engagement/listing/index.tsx
- met-web/src/components/feedback/listing.tsx
- met-web/src/components/survey/listing/index.tsx
- met-web/src/components/userManagement/listing/UserManagementListing.tsx
*Issue #1138 :*
https://github.com/bcgov/met-public/issues/1138
-Add dividers to all listing tables
> add dividers to all table listings

- met-web/src/components/layout/Header/InternalHeader.tsx
- met-web/src/components/layout/SideNav/SideNav.tsx
- met-web/src/components/layout/SideNav/types.ts
- met-web/tests/unit/components/sidenav.test.tsx
*Issue #990 :*
https://github.com/bcgov/met-public/issues/990
-Allow side navigation to show up for mobile
> Add side navigation for mobile

- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/FormTabs.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/SurveyBlock/SurveyTextTabs.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Phases/PhasesOptionCard.tsx
- met-web/src/components/engagement/form/RichTextEditor.tsx
- met-web/src/components/engagement/form/StyledTabComponents.tsx
- met-web/src/styles/Theme.ts
*Issue #1068 :*
https://github.com/bcgov/met-public/issues/1068
-Add softer borders to rich content editor
-Add softer borders to engagement text fields
-fix tab spacing
> Update engagement form styles

- met-web/src/components/engagement/form/RichTextEditor.tsx
> Fixed lint issue

- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/EngagementForm.tsx
*Issue #1152 :*
https://github.com/bcgov/met-public/issues/1152
-Update engagement form spacing
-Update label text to MA's design
> Update Engagement Form Spacing

- met-web/src/components/engagement/form/EngagementWidgets/Events/EventInfoPaper.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/Form.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1247
https://github.com/bcgov/met-public/issues/1168
https://github.com/bcgov/met-public/issues/1181
- Change PDT to PST
- Change Add Virtual Event to Add Virtual Session
> Addressing QA/UX issues for add in person event

- met-web/src/components/engagement/form/RichTextEditor.tsx
- Update border for rich text editor
> Rich text editor border bug fix

- met-web/src/components/common/dateHelper.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/EventsContext.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/EventsInfoBlock.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/Form.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/InPersonEventFormDrawer.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/VirtualEventInfoPaper.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/VirtualSessionFormDrawer.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/index.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/utils.tsx
- met-web/src/models/event.ts
- met-web/src/services/widgetService/EventService/index.tsx
*Issue #1182 :*
https://github.com/bcgov/met-public/issues/1182
-Add Virtual session drawer
-Create info paper for virtual event
-Update event context
> Setup Virtual Session drawer

- met-web/src/App.tsx
- met-web/src/components/common/index.tsx
> Update spacing for mobile responsiveness

- met-web/src/components/engagement/form/EngagementWidgets/Events/EventInfoPaper.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/Form.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/InPersonEventFormDrawer.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/VirtualSessionFormDrawer.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1247
- decrease spacing between drawer title and buttons
- decrease spacing between close button and the events info block
- decrease spacing between save and close and the form
> Adjust spacing for add event drawer

- met-web/src/App.tsx
- met-web/src/components/common/index.tsx
> add Toolbar to desktop for spacing

- met-web/tests/unit/components/factory.ts
- met-web/tests/unit/components/widgets/EventsWidget.test.tsx
> Create Event Widgets Test

- met-web/package-lock.json
- met-web/src/components/engagement/view/widgets/Events/EventsWidget.tsx
- met-web/src/components/engagement/view/widgets/Events/InPersonEvent.tsx
- met-web/src/components/engagement/view/widgets/Events/VirtualSession.tsx
- met-web/src/components/engagement/view/widgets/EventsWidget.tsx
- met-web/src/components/engagement/view/widgets/WidgetSwitch.tsx
*Issue #1184 :*
https://github.com/bcgov/met-public/issues/1184
-Add events widget to the public view
> Events widget public view

- met-web/.gitignore
- met-web/config-overrides-wc.js
- met-web/config-overrides.js
- met-web/package.json
- met-web/src/Test.tsx
- met-web/src/web-components/index.ts
- met-web/src/web-components/sample-wc.tsx
*Issue #:*
Basic webpack configuration for web components
Incorporate material design standards
command to build web components
> webcomponents initial setup

- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/view/EmailPanel.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1275
changes made to allow scrolling on modal so that users can scroll down to access the verify email section
> allow modal scrolling on small screen

- met-api/src/met_api/utils/token_info.py
- met-api/tests/unit/api/test_engagement.py
*Issue #:*
[https://github.com/bcgov/met-public/issues/<Put the github issue number here>](https://github.com/bcgov/met-public/issues/1242)
> return empty role for not logged in users

- met-web/src/components/engagement/view/widgets/Events/EventsWidget.tsx
- met-web/src/components/engagement/view/widgets/Events/InPersonEvent.tsx
- met-web/src/components/engagement/view/widgets/Events/VirtualSession.tsx
*Issue #1184 :*
https://github.com/bcgov/met-public/issues/1184
-Change padding
-make event details bold
> ui tweaks to event widget public

- met-api/src/met_api/constants/widget.py
- met-api/src/met_api/schemas/widget_events.py
- met-api/src/met_api/utils/token_info.py
- met-api/tests/unit/api/test_widget_event.py
- met-api/tests/utilities/factory_scenarios.py
> Event tests

- met-api/src/met_api/utils/constants.py
*Issue #:*
[https://github.com/bcgov/met-public/issues/1212]
Only one group mapping changed.Thats the only role that we have for now
> renamed the group mapping to super user

- met-web/src/components/engagement/form/EngagementWidgets/Events/EventsInfoBlock.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/InPersonEventFormDrawer.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/VirtualSessionFormDrawer.tsx
- met-web/src/components/engagement/view/widgets/Events/EventsWidget.tsx
- met-web/src/models/event.ts
> Update event types

- met-web/src/components/engagement/view/EmailPanel.tsx
*Issue:1275*
https://github.com/bcgov/met-public/issues/1275
-Add toolbar for mobile spacing
> Add toolbar to email modal for mobile responsiveness

- met-api/src/met_api/services/engagement_service.py
- met-api/src/met_api/utils/roles.py
- met-api/tests/utilities/factory_scenarios.py
*Issue #:*
https://github.com/bcgov/met-public/issues/1139
- Removed APP_ADMIN and replaced it with another role
- Viewer now wont be able to show drafts
> Do not show draft to viewer

- met-api/tests/unit/api/test_widget_event.py
- met-api/tests/utilities/factory_scenarios.py
- met-web/src/components/common/index.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1263
unit tests for sort event widget
> unit tests for sort event widget

- met-etl/requirements.txt
> version fix for ETL

- met-web/src/components/engagement/form/EngagementWidgets/Events/VirtualSessionFormDrawer.tsx
> Bug fix for event widget virtual session drawer

- met-web/src/components/common/index.tsx
- met-web/src/components/layout/SideNav/SideNav.tsx
- met-web/src/styles/Theme.ts
*Issue #:*
https://github.com/bcgov/met-public/issues/1280
Changes made to make the tone of the hover state on side nav to a lighter color. 
> change tone of hover state on side nav

- met-web/src/config.ts
*Issue #:*
https://github.com/bcgov/met-public/issues/1322
- fixed get env variable function
> fix get environment variable 

- met-web/src/components/common/index.tsx
- met-web/src/styles/Theme.ts
*Issue #1285 :*
https://github.com/bcgov/met-public/issues/1285
-Update button line height
> Change button lineheight to 1.1rem

- met-web/src/apiManager/endpoints/index.ts
- met-web/src/components/engagement/form/EngagementWidgets/Map/Form.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Map/MapContext.tsx
- met-web/src/models/widgetMap.tsx
- met-web/src/services/widgetService/MapService/index.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1290
- Add map form
> Add create map form

- met-api/src/met_api/auth.py
- met-api/src/met_api/resources/comment.py
- met-api/src/met_api/resources/contact.py
- met-api/src/met_api/resources/engagement.py
- met-api/src/met_api/resources/feedback.py
- met-api/src/met_api/resources/submission.py
- met-api/src/met_api/resources/survey.py
- met-api/src/met_api/resources/user.py
- met-api/src/met_api/resources/widget.py
- met-api/src/met_api/resources/widget_documents.py
- met-api/src/met_api/services/authorization.py
- met-api/src/met_api/services/engagement_service.py
- met-api/src/met_api/services/membership_service.py
- met-api/src/met_api/utils/token_info.py
- met-api/src/met_api/utils/user_context.py
- met-api/tests/unit/api/test_engagement.py
- met-api/tests/unit/services/test_engagement.py
- met-api/tests/utilities/factory_scenarios.py
- met-api/tests/utilities/factory_utils.py
*Issue #:*
1) added a user_context..will replace TokenInfo
2) Added check_auth.Will add this to more endpoints once I get this PR merged in.
> added authorisation and cleaned up jwt token handling

- met-cron/Makefile
- met-cron/cron/crontab
- met-cron/invoke_jobs.py
- met-cron/run_met_purge.sh
- met-cron/src/met_cron/services/database_service.py
- met-cron/tasks/met_purge.py
*Issue #:*
https://github.com/bcgov/met-public/issues/1171
Add event logs purge job
> Add purge event logs job

- met-api/src/met_api/resources/engagement.py
> Fixed the error in eng creation

- met-api/src/met_api/services/membership_service.py
> remoevd unncecessay check_auth

- met-web/nginx/nginx.dev.conf
- met-web/nginx/nginx.prod.conf
- met-web/nginx/nginx.test.conf
*Issue #:*
https://github.com/bcgov/met-public/issues/1337
Fixes CSP issue when previewing map
> Fix map CSP

- met-web/src/components/imageUpload/cropImage.tsx
- met-web/src/components/imageUpload/cropModal.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1311
- Add a dummy parameter and end of image url to bypass browser cache
> Fix image crop doesn't work for existing images

- met-api/src/met_api/schemas/widget_map.py
> Removed based map since created_by is throwing an error

- met-api/src/met_api/models/widget_map.py
- met-api/src/met_api/resources/widget_map.py
- met-web/package-lock.json
- met-web/src/components/engagement/form/EngagementWidgets/Map/Form.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Map/MapContext.tsx
- met-web/src/models/widgetMap.tsx
- met-web/src/services/widgetService/MapService/index.tsx
*Issue #1290 :*
https://github.com/bcgov/met-public/issues/1290
> POST & GET integration for maps

- met-api/src/met_api/resources/widget_map.py
> removed the roles for GET Map

- met-web/src/components/engagement/form/EngagementWidgets/Map/Form.tsx
- met-web/src/components/engagement/view/widgets/Map/ExpandModal.tsx
- met-web/src/components/engagement/view/widgets/Map/MapWidget.tsx
- met-web/tests/unit/components/engagement/engagement.test.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1291
- Center the map in the map widget box
- Fix alignment of close button for the expand modal
- Remove expand option for small screens
- fix long and lat flipped
> public page map widget fixes and improvements

- met-web/package-lock.json
- met-web/package.json
- met-web/src/components/common/index.tsx
- met-web/src/components/publicDashboard/KPI/CompleteResponses.tsx
- met-web/src/components/publicDashboard/KPI/ResponsesWithComment.tsx
- met-web/src/components/publicDashboard/KPI/TotalResponses.tsx
- met-web/src/components/publicDashboard/ReportBanner.tsx
- met-web/src/components/publicDashboard/SubmissionTrend/SubmissionTrend.tsx
- met-web/src/components/publicDashboard/SurveyResult.tsx
- met-web/src/components/publicDashboard/index.tsx
- met-web/src/components/publicDashboard/publicDashboard.tsx
- met-web/src/routes/UnauthenticatedRoutes.tsx
*Issue #:*
https://github.com/bcgov/met-public/issues/1345
The changes are for a sample public dashboard to get a start on using rechart.
> Public dashboard

- met-cron/config.py
*Issue #:*
Fixes engagement dashboard path
> Fixes engagement dashboard path

- met-web/src/components/engagement/form/EngagementFormTabs/EngagementSettings.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/EngagementTabsContext.tsx
*Issue #:*
Add engagement metadata fields
> Add engagement metadata fields

- met-web/src/components/engagement/form/EngagementWidgets/Map/FileUploadContext.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Map/Form.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Map/PreviewModal.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Map/ShapefileUpload.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Map/Uploader.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Map/types.ts
- met-web/src/components/engagement/view/widgets/Map/ExpandModal.tsx
- met-web/src/components/engagement/view/widgets/Map/MapWidget.tsx
- met-web/src/components/map/index.tsx
- met-web/src/models/widgetMap.tsx
- met-web/src/services/widgetService/MapService/index.tsx
*Issue #1382 :*
https://github.com/bcgov/met-public/issues/1382
-Add geojson preview on map
-Add file upload to map widgetform
> Geojson Preview & Map Form Update

- met-api/src/met_api/resources/feedback.py
*Issue #:*
https://github.com/bcgov/met-public/issues/1389
change the authorization for feedback post request to be optional
> fix for rate my app comment

- met-web/src/components/common/FileUpload/FileUpload.tsx
- met-web/src/components/common/FileUpload/FileUploadContext.tsx
- met-web/src/components/common/FileUpload/Uploader.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Map/Form.tsx
- met-web/src/services/widgetService/MapService/index.tsx
*Issue #1382 :*
https://github.com/bcgov/met-public/issues/1382
- minimized the file url states
- put geojson in react hook form
- put shapefile in react hook form
- refactored file upload to be separate component.
> move files & refactor file uploader

- met-api/src/met_api/resources/widget_map.py
- met-api/src/met_api/services/shapefile_service.py
- met-web/src/components/common/FileUpload/Uploader.tsx
- met-web/src/services/widgetService/MapService/index.tsx
*Issue #:*
[https://github.com/bcgov/met-public/issues/<Put the github issue number here>](https://github.com/bcgov/met-public/issues/1337)
- converted to multipart request
- removed zip check ;its buggy
> Shape file integration with backend

- met-api/src/met_api/resources/__init__.py
- met-api/src/met_api/resources/shape_file.py
- met-web/src/apiManager/endpoints/index.ts
- met-web/src/components/engagement/form/EngagementWidgets/Documents/StyledTreeItem.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Map/Form.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Map/utils.tsx
- met-web/src/components/engagement/view/widgets/Map/ExpandModal.tsx
- met-web/src/components/engagement/view/widgets/Map/MapWidget.tsx
- met-web/src/models/widgetMap.tsx
- met-web/src/services/widgetService/MapService/index.tsx
> Shapefile Integration

- met-web/src/components/engagement/form/EngagementWidgets/Map/PreviewModal.tsx
- met-web/src/components/engagement/view/PreviewBanner.tsx
- met-web/src/components/engagement/view/widgets/Map/ExpandModal.tsx
- met-web/src/components/engagement/view/widgets/Map/MapWidget.tsx
- met-web/src/components/map/index.tsx
*Issue #1369 :*
https://github.com/bcgov/met-public/issues/1369
-Add permission gate to schedule engagement buttons
> Permission schedule engagement

- met-web/src/components/engagement/view/PreviewBanner.tsx
*Issue #1369:*
https://github.com/bcgov/met-public/issues/1369
> Update spacing for preview banner icons

- met-web/src/components/engagement/form/EngagementWidgets/Map/Form.tsx
*Issue #1382 :*
https://github.com/bcgov/met-public/issues/1382
-Add filename variable to form
-remove display and value of geojson when icon is clicked and if saved will remove file
> Add shapefile removal to form

- met-web/src/components/common/FileUpload/Uploader.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Map/Form.tsx
- met-web/tests/unit/components/widgets/MapWidget.test.tsx
*Issue #1382:*
-Reorder map drawer to have match wireframe
-Change the drop zone to a button
-Update unit test
> Shapefile drawer assurance

- met-web/package-lock.json
- met-web/package.json
- met-web/src/App.tsx
- met-web/src/constants.ts
- met-web/src/routes/NotFound.tsx
- met-web/src/routes/constants.ts
*Issue #:*
https://github.com/bcgov/met-public/issues/1438
- Add a basename for the route path
- make eao the default basename
- store basename in session storage
> Add a basename for the route path

- met-web/src/components/Form/FormSubmit.tsx
- met-web/src/components/Form/formio.scss
- met-web/src/components/Form/types.ts
- met-web/src/components/engagement/view/ScheduleModal/index.tsx
- met-web/src/components/survey/submit/FormProgressBar.tsx
*Issue #1392 :*
https://github.com/bcgov/met-public/issues/1392
-add progress bar to form io form
-remove page buttons from form view
> Progress bar form io

- met-web/src/App.tsx
- met-web/src/apiManager/apiSlices/contacts/index.tsx
- met-web/src/apiManager/apiSlices/documents/index.tsx
- met-web/src/apiManager/apiSlices/util.ts
- met-web/src/apiManager/apiSlices/widgets/index.ts
- met-web/src/apiManager/httpRequestHandler/index.ts
*Issue #:*
https://github.com/bcgov/met-public/issues/1445
- Add tenant-id header to all requests
- redirect to pathname with /eao as basename if pathname was just '/'
> Add tenant id to all requests

- met-web/src/components/Form/FormBuilderOptions.ts
*Issue #:*
https://github.com/bcgov/met-public/issues/1465
- Add content: true in FormBuilderOptions
> Add content component to form builder

- met-web/src/components/comments/admin/reviewListing/index.tsx
- met-web/src/constants/commentStatus.ts
*Issue #:*
https://github.com/bcgov/met-public/issues/1451
- Add Needs Further Review label to comment listing
> Add Needs Further Review label to comment listing

- met-web/src/components/engagement/form/DayCalculator/index.tsx
*Issue #:*
Fixes scroll on day calculator modal
> Fix day calculator scroll

- met-web/src/components/survey/create/CreateOptions.tsx
-Add a small label under the multipage toggle
> Add a label to the multipage toggle

- met-api/src/met_api/__init__.py
- met-api/src/met_api/models/base_model.py
- met-api/src/met_api/models/survey.py
- met-api/src/met_api/models/tenant.py
- met-api/src/met_api/schemas/engagement.py
- met-api/src/met_api/services/tenant_service.py
- met-api/src/met_api/utils/cache.py
- met-api/tests/unit/api/test_engagement.py
https://github.com/bcgov/met-public/issues/1445
1. Added tenant id to g
2. added saving of tenant id in basemodel
3. a cache implementation - Will work on improving it later
4. Changed survey to save using basemodel.save()
> Set Tenant Id to global and added to basemodel as well

- met-web/src/components/engagement/form/EngagementWidgets/Documents/StyledTreeItem.tsx
- met-web/src/components/engagement/view/widgets/DocumentWidget.tsx
- met-web/src/components/engagement/view/widgets/Events/EventsWidget.tsx
- met-web/src/components/engagement/view/widgets/Map/MapWidget.tsx
- met-web/src/components/engagement/view/widgets/Subscribe/SubscribeWidget.tsx
- met-web/src/components/engagement/view/widgets/WhoIsListeningWidget.tsx
#1490 
-Add dividers to Who is listening, Document  & Subscribe Widget
-Edit Document widget appearance (more indentation and changed size of labels
-Made Who is listening & events widget more responsive and added email label 
-Map widget slightly smaller
> Widget UI tweaks

- analytics-api/Makefile
- analytics-api/src/analytics_api/config.py
- analytics-api/src/analytics_api/models/__init__.py
- analytics-api/src/analytics_api/models/base_model.py
- analytics-api/src/analytics_api/models/db.py
- analytics-api/src/analytics_api/models/engagement.py
- analytics-api/src/analytics_api/models/etlruncycle.py
- analytics-api/src/analytics_api/models/request_mixin.py
- analytics-api/src/analytics_api/models/response_mixin.py
- analytics-api/src/analytics_api/models/response_type_textfield.py
- analytics-api/src/analytics_api/models/survey.py
- analytics-api/src/analytics_api/services/engagement_service.py
Fixes lint issues for analytics-api
> Fix lint issues for analytics-api

- met-web/src/components/comments/admin/reviewListing/CommentListingContext.tsx
- met-web/src/components/comments/admin/reviewListing/Submissions.tsx
- met-web/src/components/engagement/listing/Icons.tsx
- met-web/src/components/engagement/listing/index.tsx
- met-web/src/components/survey/listing/index.tsx
- met-web/tests/unit/components/comment/CommentListing.test.tsx
- met-web/tests/unit/components/engagement/EngagementListing.test.tsx
- met-web/tests/unit/components/surveyListing.test.tsx
- Make badges clickable
- Fix badges width
- Replace Box with ButtonBase
- navigate to comment listing with corresponding status initially set
> Make badges clickable and navigate to comment listing

- met-web/package-lock.json
- met-web/package.json
- met-web/src/components/engagement/form/EngagementWidgets/Map/Form.tsx
-Added turf js
-Calculates latitude & longitude on file upload
-Fills longitude and latitude based on data
> Autofill Shapefile latitude & longitude based on geojson center on upload

- met-web/package-lock.json
- met-web/package.json
- met-web/src/components/Form/FormSubmit.tsx
- met-web/src/components/Form/MultiPageForm.tsx
- met-web/src/components/Form/SinglePageForm.tsx
- met-web/tests/unit/components/engagement/EngagementForm.test.tsx
- in met-formio add validate on option in validation tab
- clean up Form Submit to separate single page from multi page
- update package json
> Add option to validate component on blur

- met-web/src/components/survey/create/OptionsForm.tsx
Changing text on clone an existing Survey
> Changing text on clone an existing Survey

- met-web/src/components/common/Modals/EmailModal.tsx
- met-web/src/components/common/Modals/types.tsx
- met-web/src/components/engagement/view/EmailPanel.tsx
- met-web/src/components/engagement/view/EngagementContent.tsx
- met-web/src/components/engagement/view/SurveyBlock.tsx
- met-web/src/components/engagement/view/widgets/Subscribe/SubscribeWidget.tsx
- met-web/src/components/engagement/view/widgets/WhoIsListeningWidget.tsx
-Make the sid tobias email clickable mailto link on email modals
-Update who is listening responsiveness
-update font size on email modals from 1rem to 0.8rem
> Widget UX assurance 

- analytics-api/Makefile
- analytics-api/src/analytics_api/models/user_response_detail.py
- analytics-api/src/analytics_api/resources/__init__.py
- analytics-api/src/analytics_api/resources/apihelper.py
- analytics-api/src/analytics_api/resources/user_response_detail.py
- analytics-api/src/analytics_api/services/user_response_detail.py
- met-web/sample.env
- met-web/src/apiManager/endpoints/index.ts
- met-web/src/components/publicDashboard/Dashboard.tsx
- met-web/src/components/publicDashboard/DashboardContext.tsx
- met-web/src/components/publicDashboard/SubmissionTrend/SubmissionTrend.tsx
- met-web/src/components/publicDashboard/constants.ts
- met-web/src/config.ts
- met-web/src/models/analytics/userResponseDetail.ts
- met-web/src/services/analytics/userResponseDetailService/index.tsx
- openshift/web.dc.yml
- Backend changes to add logic to pull user response data by week or by month.
- Front end changes to remove hard coded data and extract data from analytics API.
> Analytics changes for survey responses over time

- met-web/nginx/nginx.dev.conf
- met-web/nginx/nginx.prod.conf
- met-web/nginx/nginx.test.conf
> Fix analytics api cors

- met-web/src/components/comments/admin/review/CommentReview.tsx
- met-web/src/components/comments/admin/textListing/index.tsx
- met-web/src/components/common/Table/index.tsx
-Align read all comments section
-update text styling for review page
> Comment Page ux changes

- met-api/src/met_api/__init__.py
- met-api/src/met_api/models/base_model.py
- met-api/src/met_api/models/engagement.py
- met-api/src/met_api/models/survey.py
- met-api/src/met_api/services/engagement_service.py
- met-api/tests/unit/api/test_engagement.py
- met-api/tests/unit/api/test_survey.py
- met-api/tests/utilities/factory_scenarios.py
- met-api/tests/utilities/factory_utils.py
- Added tenant id check in the basemodel and used that in the subqueries
- Refactored some tests to avoid duplication
> adding tenant check to get all queries

- met-web/src/components/comments/admin/textListing/index.tsx
- met-web/src/components/common/Table/index.tsx
-Showed MA screenshot and it was ux approved
-change comment date & reviewed by to a column stack
-change size of columns 
> Update comment table spacing

- met-api/src/met_api/models/engagement.py
- met-api/src/met_api/resources/engagement_members.py
- met-api/src/met_api/resources/user.py
- met-api/src/met_api/services/membership_service.py
> New api for fetching engagements against a user

- met-api/src/met_api/resources/comment.py
- met-api/src/met_api/services/comment_service.py
- met-api/src/met_api/services/submission_service.py
- met-api/src/met_api/services/user_service.py
- met-api/src/met_api/utils/roles.py
- met-api/tests/unit/api/test_submission.py
- met-api/tests/unit/services/test_comment.py
- met-api/tests/utilities/factory_scenarios.py
> Filtered comment fetching

- met-web/src/components/Form/types.ts
- met-web/src/components/banner/BannerWithoutImage.tsx
- met-web/src/components/engagement/view/EngagementInfoSection.tsx
- met-web/src/components/survey/listing/index.tsx
- met-web/src/components/survey/submit/ActionContext.tsx
- met-web/src/components/survey/submit/EngagementLink.tsx
Enable view survey with no engagement
> Enable view survey with no engagement

- met-web/src/routes/NoAccess.tsx
- met-web/src/routes/NotFound.tsx
-update not found & no access sites to new designs
> Update 404 & no access page(ux edits)

- analytics-api/src/analytics_api/config.py
- analytics-api/src/analytics_api/models/base_model.py
- analytics-api/tests/conftest.py
Removed the Bind since met-analytics connects only to one DB
> Fixed MET-Analytics DB test cases

- met-web/src/components/survey/submit/SurveySubmitWrapped.tsx
Fixes view survey not displaying questions
> Fixes view survey not displaying questions

- met-web/src/components/engagement/form/EngagementFormTabs/EngagementSettings.tsx
> Fix internal engagement label

- met-web/src/components/publicDashboard/Dashboard.tsx
- met-web/src/components/publicDashboard/KPI/ProjectLocation.tsx
- met-web/src/components/publicDashboard/KPI/SurveyEmailsSent.tsx
- met-web/src/components/publicDashboard/KPI/SurveysCompleted.tsx
-Make the engagement name the top of the dashboard for mobile
-Make SurveyEmailsSent, SurveyCompleted & ProjectLocation mobile dashboard components responsive
> Dashboard header mobile

- met-web/src/components/common/index.tsx
- met-web/src/components/map/index.tsx
- met-web/src/components/publicDashboard/Dashboard.tsx
- met-web/src/components/publicDashboard/KPI/ProjectLocation.tsx
- met-web/src/components/publicDashboard/KPI/SurveyEmailsSent.tsx
- met-web/src/components/publicDashboard/KPI/SurveysCompleted.tsx
- met-web/src/components/publicDashboard/SubmissionTrend/SubmissionTrend.tsx
- met-web/src/components/publicDashboard/SurveyBar.tsx/index.tsx
- met-web/src/components/publicDashboard/util.ts
- Export map component to PDF
- Clean code by extracting function to util file and adding error handling
- fix spacing
- fix display when fetch data fails
- Add backdrop when exporting pdf with percentage progress
> Export map component to PDF

- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/view/EmailPanel.tsx
- met-web/src/components/survey/create/CloneOptions.tsx
- met-web/src/components/survey/create/CreateOptions.tsx
- met-web/src/components/survey/create/CreateSurveyContext.tsx
- met-web/src/components/survey/create/Disclaimer.tsx
- met-web/src/components/survey/create/LinkOptions.tsx
- met-web/src/components/survey/create/OptionsForm.tsx
- Add disclaimer for create survey page
- Add checkbox
- Disable save button until checkbox is checked
> Add disclaimer for create survey page

- met-web/src/components/publicDashboard/Dashboard.tsx
- met-web/src/components/publicDashboard/SurveyBar/BarBlock.tsx
- met-web/src/components/publicDashboard/SurveyBar/index.tsx
-Make update styling for q&a widget
-Add read comment button under bar graph 
> Responsiveness for q&a dashboard widget

- met-web/package-lock.json
- met-web/package.json
- met-web/src/components/Form/FormBuilderOptions.ts
- Add Select question type
- Add survey question type
> Add select and survey (likart) question types

- met-api/src/met_api/utils/enums.py
- met-cron/config.py
- met-cron/requirements.txt
- met-cron/src/met_cron/services/mail_service.py
- met-cron/tasks/subscription_mailer.py
https://github.com/bcgov/met-public/issues/1646
> email cron added

- met-web/src/components/common/Modals/ConfirmModal.tsx
- met-web/src/components/common/Modals/types.tsx
- met-web/src/components/common/modal.tsx
- met-web/src/components/survey/submit/EngagementLink.tsx
- met-web/src/services/notificationModalService/notificationModalSlice.tsx
- met-web/src/services/notificationModalService/types.ts
-Add modals for survey submission to make sure user knows they will lose their link if they leave the page
> Returning to engagement 'warning box'

- met-api/src/met_api/services/engagement_service.py
- met-cron/invoke_jobs.py
- met-cron/requirements.txt
- met-cron/src/met_cron/models/__init__.py
Fixes cron job after removing etl
> Fix cron job - Removed unused refs

- met-api/src/met_api/models/email_queue.py
- met-api/src/met_api/services/engagement_service.py
- met-api/templates/publish_engagement.html
- met-cron/config.py
- met-cron/invoke_jobs.py
- met-cron/src/met_cron/services/mail_service.py
- Added changes to include the new email template
- Changes to cron job for publish engagement
> updates on engagement publish

- met-api/src/met_api/models/widget_documents.py
- met-api/src/met_api/resources/widget_documents.py
- met-api/src/met_api/services/widget_documents_service.py
- met-api/tests/unit/api/test_widget_document.py
- met-web/src/apiManager/endpoints/index.ts
- met-web/src/components/common/Dragdrop/index.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentFile.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentFolder.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentSwitch.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentsBlock.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentsContext.tsx
- met-web/src/models/document.ts
- met-web/src/services/widgetService/DocumentService/index.tsx
- Add drag and drop library components and apply them to the documents
- Add handle drag method for folder and file
- Call sort on drag end
- Add back end resource, service and model logic
> Implement sorting for documents in document widget

- met-web/src/components/survey/create/CloneOptions.tsx
- met-web/src/components/survey/create/CreateOptions.tsx
- met-web/src/components/survey/create/CreateSurveyContext.tsx
- met-web/src/components/survey/create/Disclaimer.tsx
- met-web/src/components/survey/create/LinkOptions.tsx
- replace pattern where button is disabled where error text appears if checkbox not pressed
> Add an error text when disclaimer box is not checked

- met-api/src/met_api/services/membership_service.py
The extra validation doesnt look necessary.so removing it
> Removed viewer check

- met-api/src/met_api/__init__.py
> Updated CORS

- met-web/src/App.tsx
- met-web/src/components/common/index.tsx
- met-web/src/components/feedback/FeedbackModal/index.tsx
- met-web/src/components/layout/Footer/constants.ts
- met-web/src/components/layout/Footer/index.tsx
- met-web/src/components/layout/Header/PublicHeader.tsx
- met-web/src/components/layout/SideNav/SideNav.tsx
- met-web/src/components/scrollToTop/index.tsx
- met-web/src/routes/AuthenticatedRoutes.tsx
- met-web/src/styles/Theme.ts
- Add footer component to app
- Make footer friendly on big and mobile screens'
- Remove login on header
> Add Footer component#1607

- .vscode/launch.json
- .vscode/settings.json
- met-api/requirements.txt
- met-api/src/met_api/models/comment.py
- met-api/src/met_api/models/submission.py
- met-api/src/met_api/resources/comment.py
- met-api/src/met_api/services/submission_service.py
- met-cron/requirements.txt
- met-web/src/components/comments/admin/review/emailPreview/EmailPreview.tsx
Fix Email preview logo
Fix Comments not being displayed
> Fix comments

- met-web/src/components/Login/index.tsx
- met-web/src/components/layout/Header/InternalHeader.tsx
- met-web/src/components/layout/Header/PublicHeader.tsx
- met-web/src/services/userService/index.ts
-Open to ideas
-Current solution is to navigate user to homepage before the logout is executed
-Cannot seem to find a way to execute the navigate command after a user has logged out(since application reloads)
> logout user consistently to homepage

- met-api/src/met_api/services/email_verification_service.py
- met-api/src/met_api/services/engagement_service.py
- Links for public dashboard in emails changed to use slug if it exists
> Update verification and closeout emails to have slug url links

- met-api/src/met_api/config.py
- met-api/tests/unit/services/test_email_verification_service.py
- Add dashboard slug path in the config file
> Add dashboard slug path in the config file

- met-web/src/components/layout/SideNav/UserGuideNav.tsx
Update help page url and paths
> Update help page url and paths

- met-web/src/components/engagement/form/EngagementFormTabs/TeamMemberListing.tsx
- met-web/src/services/userService/index.ts
-update link path in engagement user management tab
> Update user link in engagement user management tab

- openshift/README.md
- openshift/analytics-api.bc.yml
- Adding analytics BuildConfig.
- Updating openshift docs to reflect new analytics BuildConfig.
-  Reducing memory and cpu limits for the web BuildConfig.
> Updating Buildconfigs

- openshift/README.md
- openshift/web.bc.yml
- Updating Readme to add step for deploying analytics-api.
-  Updating buildconfig for met-web.
> Updating Documentation

- met-web/nginx/nginx.dev.conf
- met-web/nginx/nginx.prod.conf
- met-web/nginx/nginx.test.conf
- Add csp exception for youtube
> Add csp exception for youtube

- met-web/nginx/nginx.dev.conf
- met-web/nginx/nginx.prod.conf
- met-web/nginx/nginx.test.conf
- met-web/src/components/engagement/view/widgets/Video/VideoWidgetView.tsx
- Add csp exception for youtube frame-src
> Add csp exception for youtube frame-src

- openshift/api.dc.yml
- openshift/cron.dc.yml
- Added missing key/value pairs to configmaps
> Updating configmaps

- met-web/src/components/landing/EngagementTile.tsx
- change card height to minHeight
> Fix text overlap in engagement tile

- met-web/nginx/nginx.dev.conf
- updating nginx.dev.conf to include epic-engage-analytics url
> updating nginx.dev.conf

- met-web/nginx/nginx.test.conf
- Updating nginx.test.conf to include epic-engage-analytics url
> Updating nginx.test.conf

- met-web/src/components/publicDashboard/Dashboard.tsx
-Fix alignment of dashboard link
> Dashboard Link Fix

- met-web/src/components/survey/submit/PreviewBanner.tsx
- met-web/src/components/survey/submit/SurveySubmitWrapped.tsx
- Add preview survey banner to survey submit page
> Add preview banner to survey submit page when logged in

- met-web/src/components/survey/listing/ActionsDropDown.tsx
- Remove view survey action from survey listing action drop down
> Remove view survey action from survey listing

- met-web/src/components/survey/create/LinkOptions.tsx
- Return early if disclaimer not checked
> Fix can create survey even if checkbox isn't checked

- met-web/nginx/nginx.prod.conf
- met-web/nginx/nginx.test.conf
- met-web/src/components/common/FileUpload/Uploader.tsx
- Add frame src rule for prod and test
- fix video not playing in test
> Add frame-src rules for prod and test

- met-web/src/components/dashboard/EngagementsAccordion.tsx
- met-web/src/components/publicDashboard/SubmissionTrend/SubmissionTrend.tsx
-change clear button to secondary & update text to match wire frame
-Update from & to date alignment
> Fix overlapping elements on mobile dashboard

- met-web/src/components/Form/formio-bootstrap.scss
- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/EngagementForm.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/constants.ts
-Remove form io button radius:0 as it prevents us from styling their components
> Button styling update

- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/view/widgets/Video/VideoWidgetView.tsx
- Add aspect ratio reusable video container
- Add styled react player
> Fix video player aspect ratio

- met-web/nginx/nginx.dev.conf
- met-web/nginx/nginx.prod.conf
- met-web/nginx/nginx.test.conf
- Add csp connect src exception in dev prod and test for noembed.com so thumbnails can be loaded
> Add exception for noembed to load thumbnails

- met-web/src/components/engagement/form/EngagementWidgets/Subscribe/index.tsx
> Description fix for Subscribe drawer

- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentOptionCard.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/EventsOptionCard.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Map/MapOptionCard.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Phases/PhasesOptionCard.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Subscribe/SubscribeOptionCard.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Video/VideoOptionCard.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/WhoIsListeningOptionCard.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WidgetOptionCards.tsx
- met-web/src/components/engagement/form/EngagementWidgets/constants.ts
- met-web/src/components/survey/create/Disclaimer.tsx
- Change font sizes
- Make option cards stretch to align
- Update texts
> text and styling updates for widget drawer

- met-web/src/App.tsx
- met-web/src/locales/en/default.json
- met-web/src/locales/en/eao.json
- met-web/src/reduxSlices/tenantSlice.ts
- Add default text file
- Handle if text file wasn't found
- Handle when tenant not loaded
> Add default translation file

- met-web/nginx/nginx.dev.conf
- met-web/nginx/nginx.prod.conf
- met-web/nginx/nginx.test.conf
- met-web/src/components/engagement/form/EngagementWidgets/Video/Form.tsx
- Break CSP rules into several lines for readability
- Add Vimeo CSP
> Add vimeo CSP

- .github/workflows/deploy.yml
- openshift/deploy.sh
- Updating deploy.sh to include the EAO project and its secrets
- 
> Updating deploy.sh

- met-api/src/met_api/services/submission_service.py
- met-api/templates/email_rejected_comment.html
- met-api/templates/email_verification.html
- met-web/src/components/comments/admin/review/emailPreview/EmailTemplates.tsx
-Update text for email rejection template & email verification template
> Hard coded text

- met-api/src/met_api/constants/user.py
- met-api/src/met_api/models/submission.py
- met-api/src/met_api/schemas/engagement.py
- met-api/src/met_api/schemas/survey.py
- met-api/src/met_api/schemas/utils.py
- Filtered submissions approved by system
> Fix comments count

- met-web/src/components/engagement/form/ActionContext.tsx
- Fix update survey block in engagement form
> Fix update survey block in engagement form

- met-api/src/met_api/resources/engagement.py
- met-api/src/met_api/resources/survey.py
- met-api/src/met_api/services/authorization.py
- met-api/src/met_api/services/engagement_service.py
- met-api/src/met_api/services/survey_service.py
- met-api/src/met_api/utils/roles.py
- met-api/tests/unit/api/test_engagement.py
- met-api/tests/unit/api/test_survey.py
- met-api/tests/unit/services/test_engagement.py
- met-api/tests/unit/services/test_survey.py
- met-api/tests/utilities/factory_scenarios.py
- met-api/tests/utilities/factory_utils.py
https://github.com/bcgov/met-public/issues/1899
1. Added auth_check for survey GET and engagement GET
2. Added tests for the same
> auth check added

- met-api/src/met_api/services/comment_service.py
- met-api/tests/unit/api/test_submission.py
https://github.com/bcgov/met-public/issues/1900
> Reviewer cannot access unapproved comments - Bug Fix

- met-api/src/met_api/models/submission.py
- met-api/src/met_api/resources/submission.py
- met-api/src/met_api/services/comment_service.py
- met-api/src/met_api/services/submission_service.py
- met-api/src/met_api/utils/roles.py
- met-api/tests/unit/api/test_comment.py
https://github.com/bcgov/met-public/issues/1909
> Added auth checks on the comments

- met-web/nginx/nginx.dev.conf
- met-web/nginx/nginx.prod.conf
- met-web/nginx/nginx.test.conf
> Fix CSP not being read because they are multi line

- met-web/src/components/engagement/view/EngagementBanner.tsx
- met-web/src/components/engagement/view/EngagementInfoSection.tsx
- met-web/src/components/imageUpload/index.tsx
- Reduce engagement banner size
- update image upload help text
> Tweak engagement banner size

- met-web/nginx/nginx.dev.conf
- met-web/nginx/nginx.prod.conf
- met-web/nginx/nginx.test.conf
- Add vimeo CSP rule in connect-src
> Add vimeo csp exception

- met-web/src/components/engagement/view/widgets/Subscribe/SubscribeWidget.tsx
> Update text for subscribe widget modal

- met-web/nginx/nginx.prod.conf
- Updating nginx.prod config to include urls for production environment
> updating nginx config

- met-api/src/met_api/models/engagement.py
- met-api/src/met_api/models/membership.py
- met-api/src/met_api/services/membership_service.py
- met-web/src/components/engagement/form/EngagementFormTabs/UserManagement/ActionsDropDown.tsx
- Change how revoke and reinstate function are called
> Fix revoke button doing nothing

- met-api/src/met_api/schemas/memberships.py
> Add revoked date

- met-api/src/met_api/config.py
- met-api/src/met_api/services/contact_service.py
- met-api/src/met_api/services/engagement_service.py
- met-api/src/met_api/services/object_storage_service.py
- met-api/src/met_api/services/survey_service.py
https://github.com/bcgov/met-public/issues/1761
- Add a util to dynamically get s3 config depending on tenant
> Add dynamic s3 config

- met-cron/config.py
adding slug variables to cron config
> adding slug variables to cron config

- met-cron/config.py
adding email environment variable to cron config
> adding email environment variable to cron config

- met-web/src/components/comments/admin/reviewListing/CommentListingContext.tsx
- met-web/src/components/comments/admin/textListing/index.tsx
- met-web/src/components/common/Table/index.tsx
- met-web/src/components/common/Table/utils.ts
- met-web/src/components/engagement/listing/index.tsx
- met-web/src/components/feedback/listing.tsx
- met-web/src/components/survey/listing/SurveyListingContext.tsx
- met-web/src/components/userManagement/listing/UserManagementContext.tsx
- met-web/tests/unit/components/comment/CommentListing.test.tsx
- met-web/tests/unit/components/engagement/EngagementListing.test.tsx
- met-web/tests/unit/components/feedback/feedbackListing.test.tsx
- met-web/tests/unit/components/survey/surveyListing.test.tsx
- met-web/tests/unit/components/user/UserListing.test.tsx
- Add pagination params as url query params
- make sure url update doesn't cause page rerender
> Make rows per page sticky

- met-api/src/met_api/models/membership.py
- met-api/src/met_api/resources/engagement_members.py
- met-api/src/met_api/schemas/membership_engagement.py
- met-api/src/met_api/schemas/memberships.py
- met-api/src/met_api/services/membership_service.py
- met-web/package.json
- met-web/src/components/userManagement/userDetails/ActionsDropDown.tsx
- met-web/src/components/userManagement/userDetails/AddToEngagement.tsx
- met-web/src/components/userManagement/userDetails/AssignedEngagementsListing.tsx
- met-web/src/components/userManagement/userDetails/UserDetails.tsx
- met-web/src/components/userManagement/userDetails/UserDetailsContext.tsx
- met-web/src/components/userManagement/userDetails/index.tsx
- met-web/src/models/engagementTeamMember.ts
- met-web/src/services/membershipService/index.tsx
- met-web/src/services/userService/index.ts
- Add action drop down in user details
- Fetch memebrships instead of engagements
- load engagement details in schema only for user details page
> Revoke and Reinstate memberships from user details

- met-web/src/components/comments/admin/review/emailPreview/EmailPreviewModal.tsx
- met-web/src/components/common/Modals/EmailModal.tsx
- met-web/src/components/engagement/view/widgets/Subscribe/SubscribeWidget.tsx
- met-web/tests/unit/components/engagement/EngagementListing.test.tsx
- met-web/tests/unit/components/feedback/feedbackListing.test.tsx
- met-web/tests/unit/components/survey/surveyListing.test.tsx
- met-web/tests/unit/components/user/UserListing.test.tsx
-Subscribe Widget modal scroll bug
> Subscribe Widget modal scroll bug

- met-web/src/components/common/index.tsx
- met-web/src/components/feedback/FeedbackModal/index.tsx
- met-web/src/components/feedback/FeedbackModal/styledComponents.tsx
- met-web/tests/unit/components/feedback/feedbackModal.test.tsx
-Add PL warning to feedback modal
-Remove question option 
-Remove the header
-Move X icon higher
-Update PL text
> Feedback Modal Ui Updates

- met-web/src/components/userManagement/userDetails/UserStatusToggle.tsx
Issue #: https://github.com/bcgov/met-public/issues/1273
- Add success message to activate/deactivate user
> Add success message to activate/deactivate user

- met-api/src/met_api/resources/engagement.py
- met-api/src/met_api/resources/engagement_members.py
- met-api/src/met_api/services/engagement_service.py
- met-api/src/met_api/services/membership_service.py
- met-api/tests/unit/api/test_engagement.py
- met-api/tests/unit/api/test_engagement_membership.py
- met-api/tests/utilities/factory_scenarios.py
[Issue #: https://github.com/bcgov/met-public/issues/](https://github.com/bcgov/met-public/issues/1910)
Added team level fetch 
> permission check added for member editing

- met-api/src/met_api/services/membership_service.py
Issue #: https://github.com/bcgov/met-public/issues/1916
- Fix user assigning engagement to themselves
- Uncomment validate create membership
> fix user assigning engagement to themselves

- met-web/src/components/userManagement/listing/ActionsDropDown.tsx
Issue #: https://github.com/bcgov/met-public/issues/1910
> fix to allow admins to have assign role

- met-api/src/met_api/resources/engagement_members.py
- met-api/src/met_api/resources/engagement_metadata.py
- met-api/src/met_api/resources/widget.py
- met-api/src/met_api/resources/widget_map.py
- met-api/src/met_api/resources/widget_video.py
- met-api/src/met_api/services/engagement_metadata_service.py
- met-api/src/met_api/services/engagement_service.py
- met-api/src/met_api/services/engagement_settings_service.py
- met-api/src/met_api/services/membership_service.py
- met-api/src/met_api/services/widget_map_service.py
- met-api/src/met_api/services/widget_service.py
- met-api/src/met_api/services/widget_video_service.py
- met-api/tests/unit/api/test_widget.py
- met-api/tests/unit/services/test_widget.py
> Added more permission checks

- met-api/src/met_api/utils/constants.py
[Issue #: https://github.com/bcgov/met-public/issues/](https://github.com/bcgov/met-public/issues/1917)
> Role display name change

- met-web/src/components/userManagement/listing/UserManagementContext.tsx
- met-web/src/components/userManagement/listing/UserManagementListing.tsx
Issue #: https://github.com/bcgov/met-public/issues/2021
- Add search text state
- trigger load users on search text change and click
> Fix search in user listing not working

- met-web/src/components/comments/admin/review/CommentReview.tsx
- met-web/src/locales/en/default.json
- met-web/src/locales/en/eao.json
Issue #: https://github.com/bcgov/met-public/issues/2002
- Fix contains threat text
> Fix threat text in comment review

- met-web/src/components/landing/EngagementTile.tsx
> Fix engagement tile on hover

- met-web/package.json
- met-web/src/components/Form/FormBuilderOptions.ts
-update form io options for new content component
-update package json version for latest met-formio updates
> Formio content update

- met-api/src/met_api/services/comment_service.py
- met-api/src/met_api/services/engagement_metadata_service.py
- met-api/src/met_api/utils/roles.py
- met-api/tests/unit/api/test_comment.py
- met-api/tests/utilities/factory_scenarios.py
- met-web/src/components/comments/admin/reviewListing/Submissions.tsx
- met-web/src/components/permissionsGate/index.tsx
- met-web/src/services/userService/constants.ts
- met-web/tests/unit/components/comment/CommentListing.test.tsx
- Added a new role for export to csv.
- Disabled export to csv for users not having this role
> Adding check for export to csv

- met-api/src/met_api/models/engagement.py
- met-api/src/met_api/models/staff_user.py
- met-api/src/met_api/resources/engagement.py
- met-api/src/met_api/services/authorization.py
- met-api/src/met_api/services/keycloak.py
- met-api/src/met_api/services/staff_user_service.py
- met-api/src/met_api/utils/tenant_validator.py
- met-api/src/met_api/utils/user_context.py
- met-api/tests/unit/api/test_engagement.py
- met-api/tests/unit/api/test_user.py
- met-api/tests/utilities/factory_scenarios.py
Issue #: https://github.com/bcgov/met-public/issues/1589
> added a new decorator to support tenant based role checks
> added tenant check against membership
> added KC attribute for new members
> make tenant check on user fetch

- met-api/src/met_api/services/authorization.py
- met-api/src/met_api/utils/constants.py
- met-api/src/met_api/utils/tenant_validator.py
- met-api/src/met_api/utils/user_context.py
> a few more changes ; added logs ;created constant

- met-api/src/met_api/services/authorization.py
> Fixed str check

- met-api/migrations/versions/f037908194df_kc_attribute_script.py
- met-api/src/met_api/config.py
Issue #: https://github.com/bcgov/met-public/issues/1589
> Added script to add attribute to all users

- openshift/README.md
- updating to readme to be more specific with image tag usage in the oc commands
> Updates to Openshift README file

- met-api/src/met_api/models/membership.py
- met-api/src/met_api/resources/staff_user.py
- met-api/src/met_api/resources/widget_subscribe.py
- met-api/src/met_api/services/keycloak.py
- met-api/src/met_api/services/membership_service.py
- met-api/src/met_api/services/staff_user_membership_service.py
- met-api/src/met_api/services/staff_user_service.py
- met-api/src/met_api/utils/enums.py
- met-api/src/met_api/utils/roles.py
- met-web/src/apiManager/endpoints/index.ts
- met-web/src/components/userManagement/listing/ActionsDropDown.tsx
- met-web/src/components/userManagement/listing/ReassignRoleModal.tsx
- met-web/src/components/userManagement/listing/UserManagementContext.tsx
- met-web/src/components/userManagement/listing/index.tsx
- met-web/src/models/user.ts
- met-web/src/services/userService/api/index.tsx
- met-web/src/services/userService/constants.ts
- Add resource, service and model methods to to change user group and reassign memberships
- Add new staffUserMembership service to overcome circular import
- Add reassign user modal in the front end
- Integrate UI and resource
> Change user group and reassign memberships

- met-api/src/met_api/models/membership.py
- met-api/src/met_api/services/membership_service.py
Issue #: https://github.com/bcgov/met-public/issues/2079
- Use the create new version model method for the create membership service method
> Create new version on create membership method

- met-api/src/met_api/models/feedback.py
- met-api/src/met_api/resources/feedback.py
- met-api/src/met_api/services/feedback_service.py
- met-api/tests/unit/models/test_feedback.py
- met-web/src/components/feedback/listing.tsx
- met-web/src/services/feedbackService/index.tsx
- met-web/src/services/feedbackService/types.ts
- met-web/tests/unit/components/feedback/feedbackListing.test.tsx
-Move feedback status filtering from front end to back end
> Move status filtering from front end to back end

- met-web/src/components/engagement/view/widgets/Subscribe/ManageSubscription/Subscription.tsx
> Update unsubscribe text

- met-web/src/components/dashboard/EngagementsAccordion.tsx
- met-web/src/components/publicDashboard/Dashboard.tsx
- met-web/src/components/publicDashboard/KPI/ProjectLocation.tsx
- met-web/src/components/publicDashboard/util.ts
-Do not display project location if there is no map data on pdf & on dashboard layout
> Remove map from dashboard if there is not location data

- met-web/src/components/feedback/actionDropdown.tsx
-Feedback update: Marie Anik suggested we change the "Mark as Resolved" dropdown text to "Archive " for UX
> Update feedback dropdown text

- .github/workflows/analytics-api-cd.yml
- .github/workflows/deploy.yml
- .github/workflows/met-api-cd.yml
- .github/workflows/met-cron-cd.yml
- .github/workflows/met-web-cd.yml
- .github/workflows/notify-api-cd.yml
- Updating workflow files so that images can be tagged according to the env in which they will be used
> Updating image tagging in workflow files

- met-web/src/components/userManagement/userDetails/UserStatusButton.tsx
- Fix typo in user details
- Fix typo in reactivate/deactivate user modal
> Fix typo issue in reactive/deactivate user modal

- met-web/src/components/engagement/view/EngagementBanner.tsx
- met-web/src/components/landing/EngagementTile.tsx
-Update text for share your thoughts (capitalize every first letter of everyword)
-Update text for upcoming engagements
> Update text for share your thoughts

- met-api/src/met_api/resources/staff_user.py
- met-api/src/met_api/utils/tenant_validator.py
- met-api/src/met_api/utils/user_context.py
- met-api/tests/unit/api/test_user.py
- met-api/tests/utilities/factory_scenarios.py
Issue #: https://github.com/bcgov/met-public/issues/1439
> Added cross tenant check

- met-web/src/components/common/dateHelper.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/EventInfoPaper.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/VirtualEventInfoPaper.tsx
- met-web/src/components/engagement/view/PreviewBanner.tsx
- met-web/src/components/engagement/view/ScheduleModal/index.tsx
- met-web/src/components/engagement/view/widgets/Events/InPersonEvent.tsx
- met-web/src/components/engagement/view/widgets/Events/VirtualSession.tsx
-Update pst text to PT
-Change timezone to America/Los_angeles (PT)
> Change to PST to PT

- met-api/tests/unit/api/test_submission.py
- met-api/tests/unit/services/test_submission.py
- met-web/src/components/dashboard/EngagementsAccordion.tsx
- met-web/src/components/publicDashboard/Dashboard.tsx
- met-web/src/components/publicDashboard/KPI/ProjectLocation.tsx
- met-web/src/components/publicDashboard/util.ts
-Move Grid container inside project location to allow Project location to be rendered at all times
> MapExists boolean dashboard update

- met-web/src/components/userManagement/userDetails/UserStatusButton.tsx
- met-web/src/models/user.ts
Issue #: https://github.com/bcgov/met-public/issues/2075
- Change label from inactive to deactivated for users
- Make Activate/Deactivate button primary when it is disabled
> Minor tweaks for UM/UD

- met-api/src/met_api/services/cac_form_service.py
Issue #: https://github.com/bcgov/met-public/issues/2140
- Update check subscribe widget by type to check SIGN_UP type
> Update subscribe widget check by type

- met-api/src/met_api/config.py
- met-api/src/met_api/services/email_verification_service.py
- met-api/src/met_api/services/engagement_metadata_service.py
- met-api/src/met_api/services/rest_service.py
- met-api/src/met_api/utils/eao_util.py
- met-api/src/met_api/utils/enums.py
Issue #: https://github.com/bcgov/met-public/issues/2102
- Added a util to send updates to EAO land.so far only post is supported
- Added a generic post utility
- added configs necessary for EAO coomunication
> Added publish to eao utility

- met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentForm.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/Form.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Map/Form.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Phases/PhasesForm.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Subscribe/SubscribeForm.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Video/Form.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/WhoIsListeningForm.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WidgetDrawer.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WidgetTitle.tsx
Issue #: https://github.com/bcgov/met-public/issues/1982
-MA requested to update margin & padding for Widget Title & Widget Drawers
> Widget Title ux

- met-web/src/components/Form/formio.scss
Issue #: https://github.com/bcgov/met-public/issues/2114
-Add scrolling to formio dropdowns to display all options
> Form io dropdown bug fix

- met-web/src/components/Form/formio.scss
- met-web/src/components/layout/Header/InternalHeader.tsx
- met-web/src/components/layout/Header/PublicHeader.tsx
Issue: #2164 
-Add navigation to home route for bc header & logo
> Add navigation to met header & logo

- met-web/src/App.tsx
- met-web/src/components/engagement/view/widgets/Subscribe/FormSignUpSection.tsx
- met-web/src/config.ts
- met-web/src/constants.ts
- met-web/src/helper/index.ts
- met-web/src/hooks.ts
- met-web/src/reduxSlices/tenantSlice.ts
Issue #: https://github.com/bcgov/met-public/issues/2180
- Add isSingleTenantEnvironment variable
- Assign basename an empty or a full value according to isSingleTenantEnvironment and default tenant values
- Update cac form sign up redirect to use getBaseUrl
> support url for single and multi tenant envs

- met-web/src/components/Login/index.tsx
- met-web/src/components/layout/Header/InternalHeader.tsx
- met-web/src/components/layout/Header/PublicHeader.tsx
- met-web/src/services/userService/index.ts
Issue #: https://github.com/bcgov/met-public/issues/2165
- Add homepage url as redirect url for login and logout
> Add homepage url as redirect url for login and logout

- openshift/README.md
- updating restore documentation to include info about altering roles 
> Updating database restore documentation to include alter role command

- met-web/src/components/banner/BannerWithoutImage.tsx
- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/view/EngagementInfoSection.tsx
- met-web/src/components/landing/LandingComponent.tsx
- met-web/src/styles/constants.ts
Issue: #2190 
-remove padding top for engagment view banner
-update h1 font weight to 700 across application & font size to 1.5rem
> H1 updates

- met-web/src/components/feedback/FeedbackModal/index.tsx
Issue: #2105 
-Change comment box icon to emoji icons 
-Change Text from Feedback to Website Feedback
> Update feedback side button

- met-web/package.json
- met-web/public/index.html
- met-web/src/App.tsx
- met-web/src/DocumentTitle.tsx
- met-web/src/index.tsx
Issue #2160 
-add tenant name to page name on loading tenant
> Add tenant name to page name

- met-web/src/services/userService/index.ts
- logout sometimes throws error about id_token_hint missing. Supplied id_token to logout code
- added tokens to session storage
- cleaned up logout code
> logout code clean up , added tokens to session storage

- met-web/src/components/comments/admin/textListing/index.tsx
- met-web/tests/unit/components/comment/CommentListing.test.tsx
Issue #: https://github.com/bcgov/met-public/issues/2133
- Update export menu labels naming
> update labels for comment export

- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/view/EmailModal.tsx
- met-web/src/components/engagement/view/EmailPanel.tsx
Issue: #2158 
-Add scroll bars to modals in case user zooms in on browser or is on mobile
> Add scroll to modals

- met-api/migrations/versions/d5a6d9bb804b_merge_heads.py
- met-api/migrations/versions/d822eacf35c9_add_engagement_unpublished_status.py
- met-api/src/met_api/constants/engagement_status.py
- met-api/src/met_api/utils/roles.py
- met-web/src/components/engagement/status/index.tsx
- met-web/src/components/engagement/view/ActionContext.tsx
- met-web/src/components/engagement/view/EngagementInfoSection.tsx
- met-web/src/components/engagement/view/PreviewBanner.tsx
- met-web/src/components/engagement/view/ScheduleModal/index.tsx
- met-web/src/components/engagement/view/UnpublishModal/index.tsx
- met-web/src/constants/engagementStatus.ts
- met-web/src/services/engagementService/types.ts
- met-web/src/services/userService/constants.ts
Issue #: https://github.com/bcgov/met-public/issues/2174
- Add unpublished status
- Add unpublished badge
- Add unpublish modal
- Integrate Front and back for unpublishing functionality
> Implement unpublishing an engagement

- met-api/src/met_api/__init__.py
> Removed app level CORS

- met-api/src/met_api/__init__.py
> changed CORS to allowedorigins to support multiple urls

- met-web/package-lock.json
- met-web/package.json
Issue #: https://github.com/bcgov/met-public/issues/2233
- Update to version with advanced conditional
> updatte met-formio version

- met-web/src/components/FormCAC/FormContext.tsx
Issue #2240
-update form sign up text
> Update form sign up text

- met-web/src/components/Form/FormBuilderOptions.ts
Issue #2113 
-Change text from submit form to submit
> Change submit form to submit

- met-api/src/met_api/services/project_service.py
Issue #: https://github.com/bcgov/met-public/issues/1088
- Changed payload to send pulbic and staff url to EPIC
> separated payload for epic

- met-api/src/met_api/constants/engagement_status.py
- met-api/src/met_api/models/engagement.py
- met-web/src/components/engagement/listing/AdvancedSearch/SearchComponent.tsx
- met-web/src/constants/engagementStatus.ts
Issue #: https://github.com/bcgov/met-public/issues/2175
- Add unpublish filter
- Refactor search filtering by status
> Add unpublish filter

- met-web/src/components/FormCAC/FormContext.tsx
Issue #2240 
-Add missing period
> Add missing period for form sign up text

- met-web/src/components/Form/formio.scss
Issue #: https://github.com/bcgov/met-public/issues/2254
- Make likert scrollable
> Make likert scrollable

- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/AddContactDrawer.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/WhoIsListeningContext.tsx
Issue #: https://github.com/bcgov/met-public/issues/1942
- clear the form on close
> Fix form not cleared in who is listening widget

- met-api/src/met_api/services/staff_user_membership_service.py
Issue #: https://github.com/bcgov/met-public/issues/2143
- Add a backend check to prevent reassigning of roles to self
> Added check to prevent self-role change

- met-web/src/components/Form/FormBuilderOptions.ts
- met-web/src/components/FormioListener/index.tsx
- met-web/src/components/FormioModalListener/index.tsx
- met-web/src/routes/AuthenticatedRoutes.tsx
Issue #2113 
-Update submit button by adding a listener in the application
> Form io Submit button fix

- met-web/src/components/publicDashboard/SurveyBar/QuestionBlock.tsx
Issue #2137 
- Add a active button styles
> Add dashboard button styles

- docs/nginx_base_auth.md
- met-web/nginx/nginx.dev.conf
- met-web/nginx/nginx.test.conf
- met-web/package-lock.json
- met-web/package.json
- openshift/web.dc.yml
1) Added nginx base auth to DEV config
2) Changed deployment config to inject secret with password to nginx enviroment
3) Added docs
> Changes for integrating basic auth 

- met-api/src/met_api/services/shapefile_service.py
Issue: #2274 
-Add a checker to convert map format if crs is used
> Update map backend to handle crs

- met-api/src/met_api/services/project_service.py
> updated EPIC payload

- met-web/src/components/engagement/form/ActionContext.tsx
Issue #: https://github.com/bcgov/met-public/issues/2278
- Create a load data method
- set loading is false after all await fetches return
> set loading to false after all fetch is done

- met-web/src/web-components/components/engagement-banner-wc.tsx
Issue #: https://github.com/bcgov/met-public/issues/2281
- Change text to View Engagement
- Fix position to be at end
> Fix position and change text of epic survey button

- met-web/src/components/Form/MultiPageForm.tsx
- met-web/src/components/survey/submit/Stepper.tsx
Issue #: https://github.com/bcgov/met-public/issues/2287
- Add a scroll up function and call it when next or previous page
> Scroll up when changing pages

- met-api/src/met_api/config.py
- met-api/src/met_api/services/engagement_metadata_service.py
- met-api/src/met_api/services/engagement_service.py
- met-api/src/met_api/services/project_service.py
- met-api/src/met_api/utils/datetime.py
- EPIC expects date to be in UTC.so added conversion
- When engagement date changes , send updates to EPIC
> Changes for sending project updates when dates changes

- met-web/src/routes/AuthenticatedRoutes.tsx
Issue #: https://github.com/bcgov/met-public/issues/2293
- Add the slug routes in authenticated users
> Add the /slug route for logged in users

- met-web/src/components/publicDashboard/SurveyBar/QuestionBlock.tsx
> Update dashboard styles

- met-web/src/components/Form/FormBuilderOptions.ts
Issue #:
- Change display to false for category type questions
> Remove category questions

- met-web/src/components/engagement/form/EngagementFormTabs/Links/PublicUrls.tsx
Issue #:
- Add /public to the copy dashboard url
> add /public to the dashboard copy

- met-web/src/components/publicDashboard/SurveyBar/QuestionBlock.tsx
- met-web/src/components/publicDashboard/SurveyBar/index.tsx
Issue #:
- Use Index value to highlight the selected question
> Fix selected question should be highlighted

- met-web/package-lock.json
- met-web/package.json
- met-web/src/services/userService/index.ts
> updated keycloak package version

- met-web/package-lock.json
- met-web/package.json
> new KC version

- met-web/src/components/engagement/form/EngagementFormTabs/Links/PublicUrls.tsx
> Added slash at the end of pulbic url

- met-web/src/components/Form/MultiPageForm.tsx
- Scroll up to absolute location
> Make scroll up absolute

- met-api/src/met_api/schemas/engagement.py
> Fixed - Compare date without time stamp

- met-web/src/components/engagement/view/EmailPanel.tsx
- Fix email panel text and remove TBD
> Fix email panel text and remove TBD

- CHANGELOG.MD
Issue #: N/A
This PR adds a change log following SemVer to allow developers to log any changes they make to the project.
> Add initial version of change log

- CHANGELOG.MD
- met-web/package-lock.json
- met-web/package.json
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-446
1.  Updated the version of @formio/react which fixed the drag-and-drop error of radio and checkbox items.
> DESENG-446 - FormioReact package version upgraded to fix formio errors

- CHANGELOG.MD
- met-web/nginx/nginx.dev.conf
- met-web/nginx/nginx.prod.conf
- met-web/nginx/nginx.test.conf
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-469
- Remove Epic Engage-related links and update Keycloak link.
- Remove additional authentication method.
> DESENG-469: Update NGINX configuration for met-web

- met-web/nginx/nginx.dev.conf
- met-web/nginx/nginx.prod.conf
- met-web/nginx/nginx.test.conf
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-469
- Updating the Keycloak url on dev, test and prod files
> DESENG-469: Updating the Keycloak url on nginx file

- CHANGELOG.MD
- met-web/package-lock.json
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-474
- Run `npm audit fix` to update the vulnerable Babel traverse library.
- Tested the build process and unit test execution
- Tested application in major available browsers like EDGE, Chrome, and Firefox
> DESENG-474: Updated Babel Traverse library

- CHANGELOG.MD
- met-api/tests/docker/docker-compose.yml
- met-web/src/components/engagement/view/widgets/Timeline/TimelineWidgetView.tsx
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-488
- Added new material UI icons to show the status for timeline widget.
> DESENG-488: Changes to update timeline widget icons

- met-web/src/components/engagement/form/EngagementWidgets/Poll/Form.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Poll/PolllAnswerItemForm.tsx
- met-web/tests/unit/components/factory.ts
- met-web/tests/unit/components/widgets/PollWidget.test.tsx
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-483
Added Poll widget unit test
> [TO FEATURE] DESENG-483: Adding Poll Widget Unit test

- met-web/tests/unit/components/factory.ts
- met-web/tests/unit/components/widgets/TimeLineWidget.test.tsx
- met-web/tests/unit/components/widgets/VideoWidget.test.tsx
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-483
Added Unit test for TimeLine widget and VideoWidget
> [TO FEATURE] DESENG-483: Added TimeLine widget and VideoWidget test

- met-web/tests/unit/components/factory.ts
- met-web/tests/unit/components/widgets/PollWidget.test.tsx
- met-web/tests/unit/components/widgets/TimeLineWidget.test.tsx
- met-web/tests/unit/components/widgets/VideoWidget.test.tsx
- met-web/tests/unit/components/widgets/setupWidgetTestEnv.tsx
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-483
Added TimeLine widget and Video Widget Unit Test
> DESENG-483: Added TimeLine widget and Video Widget Unit Test

- CHANGELOG.MD
- met-api/requirements.txt
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-502
- Upgrading flask version to 2.2.5 for met api
> DESENG-502: Upgrading flask version

- met-web/tests/unit/components/landingPage/LandingPage.test.tsx
- met-web/tests/unit/components/widgets/SubscribeWidget.test.tsx
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-483
Added tests for the Subscribe widget and Landing page
> [TO FEATURE] DESENG-483: Unit test for Landing page and Subscribe widget

- CHANGELOG.MD
- met-web/package-lock.json
- met-web/package.json
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-490
Added related libraries to the frontend package.json.
> DESENG-490: Added Font Awesome libraries

- met-api/src/met_api/resources/__init__.py
- met-api/src/met_api/resources/language.py
- met-api/src/met_api/schemas/language.py
- met-api/src/met_api/schemas/schemas/language.json
- met-api/src/met_api/schemas/schemas/language_update.json
- met-api/src/met_api/services/language_service.py
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-509
Added Service and resource files for language
> [TO FEATURE ] DESENG-509: Service and resource files for language

- met-api/migrations/versions/e6c320c178fc_multi_langauge_table_migration.py
- met-api/tests/unit/api/test_language.py
- met-api/tests/unit/models/test_language.py
- met-api/tests/unit/services/test_language_service.py
- met-api/tests/utilities/factory_scenarios.py
- met-api/tests/utilities/factory_utils.py
Issue #:  https://apps.itsm.gov.bc.ca/jira/browse/DESENG-509
Added Unit test for Language API
> [TO FEATURE] DESENG-509: Unit test for Language API

- met-web/src/components/engagement/form/ActionContext.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/AdditionalDetails/AdditionalTabContent.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/EngagementForm.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/EngagementTabsContext.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/FormTabs.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/Settings/EngagementSettingsForm.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/SurveyBlock/index.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/UserManagement/EngagementUserManagement.tsx
- met-web/src/components/engagement/form/EngagementWidgets/WidgetsBlock.tsx
- met-web/src/components/engagement/form/types.ts
- met-web/tests/unit/components/engagement/form/create/EngagementForm.Create.test.tsx
- met-web/tests/unit/components/engagement/form/edit/EngagementForm.Edit.One.test.tsx
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-507
- Splitting existing "Save" button in the floating bar into "Save and Continue" and "Save and Exit"
- Changes to grey out the tabs and add widgets/add survey until the engagement has been saved and added a related tool-tip
> Update save on engagement form

- met-api/src/met_api/models/event_item_translation.py
- met-api/src/met_api/models/poll_answer_translation.py
- met-api/src/met_api/resources/__init__.py
- met-api/src/met_api/resources/event_item_translation.py
- met-api/src/met_api/resources/poll_answer_translation.py
- met-api/src/met_api/schemas/event_item_translation_schema.py
- met-api/src/met_api/schemas/poll_answer_translation_schema.py
- met-api/src/met_api/schemas/schemas/event_item_translation.json
- met-api/src/met_api/schemas/schemas/poll_answer_translation.json
- met-api/src/met_api/services/event_item_translation_service.py
- met-api/src/met_api/services/poll_answer_translation_service.py
- met-api/src/met_api/services/poll_answers_service.py
- met-api/src/met_api/services/widget_events_service.py
- met-api/tests/unit/api/test_event_item_translation.py
- met-api/tests/unit/api/test_poll_answer_translation.py
- met-api/tests/unit/models/test_event_item_translation.py
- met-api/tests/unit/services/test_event_item_translation_service.py
- met-api/tests/unit/services/test_poll_answer_translation_service.py
- met-api/tests/unit/services/test_poll_answers_service.py
- met-api/tests/utilities/factory_utils.py
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-515
Adding API for Poll event and Event Item translations
Added associated unit tests
> [To Feature] DESENG-515 : Adding API for Poll event and Event Item translations

- met-web/tests/unit/components/widgets/PollWidgetResultsView.test.tsx
Fixing a bug in Poll widget result unit test
> Poll widget test fix

- CHANGELOG.MD
- met-web/package-lock.json
- met-web/package.json
- met-web/src/App.scss
- met-web/src/App.tsx
- met-web/src/components/comments/admin/review/emailPreview/EmailPreview.tsx
- met-web/src/components/common/LanguageSelector.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/AdditionalDetails/AdditionalTabContent.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/EngagementForm.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/Results/EngagementResults.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/Settings/EngagementSettingsForm.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/UserManagement/ActionsDropDown.tsx
- met-web/src/components/engagement/form/EngagementFormTabs/UserManagement/EngagementUserManagement.tsx
- met-web/src/components/engagement/listing/ActionsDropDown.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/PhaseBox.tsx
- met-web/src/components/engagement/view/widgets/PhasesWidget/PhasesWidgetMobile/PhaseBoxMobile.tsx
- met-web/src/components/engagement/view/widgets/Timeline/TimelineWidgetView.tsx
- met-web/src/components/feedback/actionDropdown.tsx
- met-web/src/components/imageUpload/cropModal.tsx
- met-web/src/components/landing/EngagementTile.tsx
- met-web/src/components/layout/SideNav/SideNav.tsx
- met-web/src/components/map/index.tsx
- met-web/src/components/publicDashboard/constants.ts
- met-web/src/components/survey/listing/ActionsDropDown.tsx
- met-web/src/components/userManagement/listing/ActionsDropDown.tsx
- met-web/src/components/userManagement/userDetails/ActionsDropDown.tsx
- met-web/src/styles/Theme.ts
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-520
- Update Table and Menu Dropdown hover colors
- Update engagement tiles' hover color.
- Updated all white backgrounds to use CSS variables.
> [TO Main] MET Web - Replace hover & background colors

- CHANGELOG.MD
- met-web/src/components/feedback/FeedbackModal/index.tsx
- met-web/src/components/feedback/listing.tsx
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-524
- Fixed feedback path not updating issue.
- Fixed feedback table grid styles.
> [To Main] DESENG-524: Feedback bugs fixed

- CHANGELOG.MD
- analytics-api/tests/unit/api/test_aggregator.py
- analytics-api/tests/unit/api/test_engagement.py
- analytics-api/tests/unit/api/test_survey_result.py
- analytics-api/tests/unit/api/test_user_response_detail.py
- analytics-api/tests/unit/models/test_available_response_option.py
- analytics-api/tests/unit/models/test_email_verification.py
- analytics-api/tests/unit/models/test_engagement.py
- analytics-api/tests/unit/models/test_request_type_option.py
- analytics-api/tests/unit/models/test_response_type_option.py
- analytics-api/tests/unit/models/test_survey.py
- analytics-api/tests/unit/models/test_user_response_detail.py
- analytics-api/tests/unit/utils/test_token_info.py
- analytics-api/tests/unit/utils/test_util.py
- analytics-api/tests/utilities/factory_scenarios.py
- analytics-api/tests/utilities/factory_utils.py
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-482
- Added unit tests for analytics API models and API end points
> Unit tests for analytics API models and API end points

- CHANGELOG.MD
- openshift/analytics-api.dc.yml
- openshift/api.dc.yml
- openshift/cron.dc.yml
- openshift/notify-api.dc.yml
- openshift/web.dc.yml
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-503
- Added new config/secret required as per recent changes to all the DC files.
> [To Main] DESENG-503: Updating deployment configurations

- CHANGELOG.MD
- met-web/src/App.tsx
- met-web/src/components/auth/AuthKeycloakContext.tsx
- met-web/src/components/layout/Footer/index.tsx
- met-web/src/components/layout/Header/InternalHeader.tsx
- met-web/src/components/layout/SideNav/SideNavElements.tsx
- met-web/src/constants/tenantConstants.ts
- met-web/src/index.tsx
- met-web/src/routes/AuthenticatedRoutes.tsx
- met-web/src/services/userService/index.ts
- met-web/src/utils/index.ts
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-542
- Created authentication provider to know the logged-in state before the App component is rendered.
- Optimized tenant identification from the url.
- Optimized path segment identification.
Note: Keycloak-js has an [issue ](https://www.keycloak.org/docs/latest/securing_apps/#_modern_browsers)with Firefox (Tracking Protection) in local machines (or non-https) . So if using the met-web app locally, please turn off the tracking protection.
> DESENG-542: Keycloak auth method and redirection fixed

- met-api/sample.env
- met-api/src/met_api/config.py
- met-api/src/met_api/services/participant_service.py
- openshift/api.dc.yml
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-574
- Removing dependency on CSS API
> [To Feature] Removing dependency on CSS API

- CHANGELOG.MD
- met-web/src/models/user.ts
- met-web/src/services/userService/constants.ts
- met-web/src/services/userService/index.ts
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-574
- Renamed admin and viewer role.
- Eliminated redundant or unused roles from the system.
> [To Feature] Front end changes for in-app role management

- .github/workflows/met-etl-cd.yml
- CHANGELOG.MD
- met-etl/Dockerfile
- met-etl/container/dagster/Dockerfile
- met-etl/container/user_code/Dockerfile
- met-etl/requirements.txt
- met-etl/src/etl_project/services/ops/survey_etl_service.py
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-599
- Upgrading the version of python to 3.12 for dagster user code.
- Upgrading the dependencies to support the version of python.
- Changes on survey etl service.
> [To Main] Dagster fix and python upgrade

- CHANGELOG.MD
- met-api/src/met_api/__init__.py
- met-api/src/met_api/models/staff_user.py
- met-api/src/met_api/resources/engagement_metadata.py
- met-api/src/met_api/resources/staff_user.py
- met-api/src/met_api/services/authorization.py
- met-api/src/met_api/utils/roles.py
- met-api/src/met_api/utils/tenant_validator.py
- met-api/src/met_api/utils/user_context.py
- met-api/tests/conftest.py
Issue #: [DESENG-557](https://apps.itsm.gov.bc.ca/jira/browse/DESENG-557)
- **Feature** Add Super Admin role  
- Added a new role, `SUPER_ADMIN`, to MET.
- The `SUPER_ADMIN` role has the highest level of access in the MET application.
- The `SUPER_ADMIN` role can perform all actions in MET, including actions in other tenants.
- The role can be only be assigned through the single sign-on (SSO) service.
- This overrides any other permissions set, e.g, a Viewer user who gets the super_admin role
will have all the permissions of a normal super admin.
> [To Feature] Backend changes for DESENG-557

- CHANGELOG.MD
- met-web/sample.env
- met-web/src/config.ts
- met-web/src/services/userService/constants.ts
- met-web/src/services/userService/userSlice.ts
Issue #: [DESENG-557](https://apps.itsm.gov.bc.ca/jira/browse/DESENG-557)
- **Feature** Add Super Admin role
- Change the React app's admin role to `SUPER_ADMIN` (previously `CREATE_TENANT`).
- Force all UI elements to be enabled for the `SUPER_ADMIN` role.
> [To Feature] Frontend changes for DESENG-557

- CHANGELOG.MD
- met-api/tests/unit/api/test_engagement.py
- met-api/tests/unit/api/test_survey.py
- met-api/tests/unit/api/test_user.py
- met-api/tests/utilities/factory_scenarios.py
Issue #: [DESENG-557](https://apps.itsm.gov.bc.ca/jira/browse/DESENG-557)
Added unit tests for DESENG-557.
> [To Feature] Unit tests for DESENG-557

- CHANGELOG.MD
- met-web/src/components/layout/SideNav/SideNavElements.tsx
- met-web/src/components/tenantManagement/listing/index.tsx
- met-web/src/routes/AuthenticatedRoutes.tsx
- met-web/tests/unit/components/sidenav.test.tsx
Issue #: [DESENG-591](https://apps.itsm.gov.bc.ca/jira/browse/DESENG-591)
- **Feature** Added a new landing page for tenant management [🎟️ DESENG-591](https://apps.itsm.gov.bc.ca/jira/browse/DESENG-591)
- The page will be updated to list and manage tenants in upcoming tickets.
> Feature: add tenant management page

- CHANGELOG.MD
- met-web/package-lock.json
- met-web/package.json
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-596
- Upgrading the version of met-formio to add a default description for the form components.
> [To Main] Upgrading the version of met-formio

- CHANGELOG.MD
- met-web/src/components/comments/admin/review/emailPreview/EmailPreview.tsx
- met-web/tests/unit/components/comment/CommentReview.test.tsx
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-597
Related PR : https://github.com/bcgov/met-public/pull/2471
- Fixed the date formatting issue and using the end_date in the email preview
- Updated unit tests
> [To Main] - DESENG-597 - Fixed : Date shown on rejection email preview is incorrect

- met-web/src/components/common/Input/Button.tsx
- met-web/src/components/common/Input/FormField.tsx
- met-web/src/components/common/Input/TextInput.tsx
- met-web/src/components/common/Modals/ConfirmModal.tsx
- met-web/src/components/common/Modals/UpdateModal.tsx
- met-web/src/components/common/Modals/types.tsx
- met-web/src/components/common/Typography/Body.tsx
- met-web/src/components/common/index.tsx
- met-web/src/components/common/modal.tsx
- met-web/src/components/imageUpload/cropModal.tsx
- met-web/src/components/tenantManagement/Detail.tsx
- met-web/src/components/tenantManagement/Edit.tsx
- met-web/src/components/tenantManagement/Listing.tsx
- met-web/src/components/tenantManagement/TenantForm.tsx
- met-web/src/services/notificationModalService/notificationModalSlice.tsx
- met-web/src/services/notificationModalService/types.ts
- met-web/src/utils/index.ts
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-418
- Added new button styling to match MET design library
- Updated accessibility styling on text input components
- Added new modal types
> [To Feature] Multi tenancy - UX Pass 1

- CHANGELOG.MD
- met-web/src/components/FormCAC/FirstTab.tsx
- met-web/src/components/FormCAC/SecondTab.tsx
- met-web/src/components/common/Input/Button.tsx
- met-web/src/components/common/Input/Link.tsx
- met-web/src/components/common/Input/Pagination.tsx
- met-web/src/components/common/Input/Select.tsx
- met-web/src/components/common/Input/TextInput.tsx
- met-web/src/components/common/Input/index.tsx
- met-web/src/components/engagement/dashboard/comment/CommentsBlock.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/StyledTreeItem.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Documents/TreeView.tsx
- met-web/src/components/engagement/view/EmailPanel.tsx
- met-web/src/components/engagement/view/SurveyBlock.tsx
- met-web/src/components/engagement/view/widgets/Events/VirtualSession.tsx
- met-web/src/components/engagement/view/widgets/Map/ExpandModal.tsx
- met-web/src/components/engagement/view/widgets/Map/MapWidget.tsx
- met-web/src/components/engagement/view/widgets/Poll/PollWidgetView.tsx
- met-web/src/components/engagement/view/widgets/Subscribe/EmailListSection.tsx
- met-web/src/components/engagement/view/widgets/Subscribe/FormSignUpSection.tsx
- met-web/src/components/engagement/view/widgets/WhoIsListeningWidget.tsx
- met-web/src/components/feedback/FeedbackModal/index.tsx
- met-web/src/components/feedback/FeedbackModal/styledComponents.tsx
- met-web/src/components/landing/EngagementTile.tsx
- met-web/src/components/landing/FilterBlock.tsx
- met-web/src/components/landing/FilterDrawer.tsx
- met-web/src/components/landing/MetadataFilterChip.tsx
- met-web/src/components/landing/TileBlock.tsx
- met-web/src/components/layout/Footer/index.tsx
- met-web/src/components/publicDashboard/Dashboard.tsx
Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-583
- Worked on components to match the design system and support new colors
- Implemented focus states across public pages and components
> [To Main] Added the focus states to publicly accessible pages and components

- CHANGELOG.MD
- met-web/src/components/common/Indicators/StatusChip.tsx
- met-web/src/components/common/Navigation/Link.tsx
- met-web/src/components/common/Typography/Headers.tsx
- met-web/src/components/engagement/new/view/EngagementDescription.tsx
- met-web/src/components/engagement/new/view/EngagementSurveyBlock.tsx
- met-web/src/components/engagement/new/view/SuggestedEngagements.tsx
- met-web/src/components/engagement/new/view/index.tsx
- met-web/src/components/landing/EngagementTile.tsx
- met-web/src/components/landing/FilterDrawer.tsx
- met-web/src/components/landing/LandingComponent.tsx
- met-web/src/components/landing/MetadataFilterChip.tsx
- met-web/src/components/landing/TileBlock.tsx
- met-web/src/components/landing/TileSkeleton.tsx
- met-web/src/routes/UnauthenticatedRoutes.tsx
- met-web/src/styles/Theme.ts
- met-web/tests/unit/components/landingPage/LandingPage.test.tsx
Issue #:  [🎟️ DESENG-634](https://citz-gdx.atlassian.net/browse/DESENG-634)
- Redesigned the engagement cards to match the new design system
- Added a new section to the engagement page to display suggested engagements
- Engagement cards now take you to the "new look" route
- Tweaks to the engagement list page layout
- Minor tweaks to the engagement view page layout
> [To Main] DESENG-634: Update engagement cards; add suggested engagements block

- .github/workflows/analytics-api-cd.yml
- .github/workflows/analytics-api-ci.yml
- .github/workflows/codeql.yml
- .github/workflows/deploy.yml
- .github/workflows/met-api-cd.yml
- .github/workflows/met-api-ci.yml
- .github/workflows/met-cron-cd.yml
- .github/workflows/met-cron-ci.yml
- .github/workflows/met-etl-cd.yml
- .github/workflows/met-web-cd.yml
- .github/workflows/met-web-ci.yml
- .github/workflows/notify-api-cd.yml
- .github/workflows/notify-api-ci.yml
Issue #: [DESENG-645](https://citz-gdx.atlassian.net/browse/DESENG-645)
- Upgraded the version strings of various actions within the Github workflows for this repository
> [To Main] Update Github Workflows actions to v3

- met-web/src/components/engagement/listing/AdvancedSearch/SearchComponent.tsx
- met-web/src/components/engagement/listing/index.tsx
- met-web/src/components/engagement/new/view/EngagementListLoader.tsx
- met-web/src/routes/AuthenticatedRoutes.tsx
Issue #: https://citz-gdx.atlassian.net/browse/DESENG-664
Improved & optimized changes to the engagement search features for DESENG-664
> [To Feature] Improve loader features on authenticated engagement search page

- met-web/src/components/engagement/form/ActionContext.tsx
- met-web/src/components/engagement/listing/index.tsx
- met-web/src/components/engagement/view/ActionContext.tsx
- met-web/tests/unit/components/engagement/EngagementFormUserTab.test.tsx
- met-web/tests/unit/components/engagement/EngagementListing.test.tsx
- met-web/tests/unit/components/engagement/engagement.test.tsx
- met-web/tests/unit/components/engagement/form/create/EngagementForm.Create.test.tsx
- met-web/tests/unit/components/engagement/form/edit/EngagementForm.Edit.One.test.tsx
- met-web/tests/unit/components/engagement/form/edit/EngagementForm.Edit.Two.test.tsx
- met-web/tests/unit/components/survey/SurveyReportSettings.test.tsx
- met-web/tests/unit/components/widgets/DocumentWidget.test.tsx
- met-web/tests/unit/components/widgets/EventsWidget.test.tsx
- met-web/tests/unit/components/widgets/MapWidget.test.tsx
- met-web/tests/unit/components/widgets/PollWidget.test.tsx
- met-web/tests/unit/components/widgets/PollWidgetResultsView.test.tsx
- met-web/tests/unit/components/widgets/PollWidgetView.test.tsx
- met-web/tests/unit/components/widgets/SubscribeWidget.test.tsx
- met-web/tests/unit/components/widgets/TimeLineWidget.test.tsx
- met-web/tests/unit/components/widgets/VideoWidget.test.tsx
- met-web/tests/unit/components/widgets/WhoIsListeningWidget.test.tsx
Issue #: [🎟️ DESENG-664](https://citz-gdx.atlassian.net/browse/DESENG-664)
Modified unit tests so they pass after changes from DESENG-664
> [To Feature] Update unit tests for DESENG-664

- met-web/src/components/layout/SideNav/SideNav.tsx
- met-web/src/components/layout/SideNav/SideNavElements.tsx
- met-web/src/components/layout/SideNav/UserGuideNav.tsx
- met-web/src/components/layout/SideNav/types.ts
Issue #: [🎟️ DESENG-661](https://citz-gdx.atlassian.net/browse/DESENG-661)
- Removed "icon assignments" mapping and turned it into   a property of the Route item
- Renamed some variables to better indicate their purpose
- Added a more accessibly visible outline to route list items when navigating with the keyboard
- Made the entire route item surface clickable, expanding the <ListItemButton> component to take the full size of its parent. This should not affect the layout.
> [To Feature] DESENG-661 Patch: Optimizations and Accessibility

- CHANGELOG.MD
- met-api/src/met_api/models/user_group_membership.py
- met-api/src/met_api/resources/staff_user.py
- met-api/src/met_api/services/user_group_membership_service.py
Issue #: [🎟️ DESENG-660](https://citz-gdx.atlassian.net/browse/DESENG-660)
- Added a new API endpoint to fetch a list of a user's tenants, required for the new header
This is part of a larger feature branch for DESENG-660
> [To Feature] DESENG-660 Part 1: User/Tenant API changes

- CHANGELOG.MD
- met-web/src/components/engagement/admin/view/AuthoringTab.tsx
Issue #: [🎟️ DESENG-687](https://citz-gdx.atlassian.net/browse/DESENG-687)
- **Bugfix** Fix keyboard focus being trapped on buttons on authoring page
> [To Main] DESENG-687: Bugfix - Fix keyboard focus being trapped on buttons on authoring page

- CHANGELOG.MD
- met-web/src/components/engagement/form/EngagementWidgets/Poll/PollDisplay.tsx
- met-web/src/components/engagement/old-view/widgets/Poll/PollWidgetView.tsx
- met-web/src/services/widgetService/PollService/index.tsx
- met-web/tests/unit/components/widgets/PollWidgetView.test.tsx
Issue #: https://citz-gdx.atlassian.net/browse/DESENG-697
- **Feature** Redesign poll widget 
- Refactor PollWidget.tsx implementing Figma design
- Improved layout, similar to DocumentWidget
- Load data more efficiently
- Added new skeleton while loading
- Added new error handling for poll submission
> DESENG-697: New poll widget design implementation

- CHANGELOG.MD
- met-etl/Dockerfile
Issue #: https://citz-gdx.atlassian.net/browse/DESENG-677
-  Updated the Dagster versions to see if that fixes things. Vineet had suggested a similar fix to this issue when the Epic team encountered it
**User Guide update ticket (if applicable):** N/A
> DESENG-667 Update dagster version to attempt ETL pipeline fix

- .github/workflows/analytics-api-cd.yml
- .github/workflows/analytics-api-ci.yml
- .github/workflows/codeql.yml
- .github/workflows/deploy.yml
- .github/workflows/met-api-cd.yml
- .github/workflows/met-api-ci.yml
- .github/workflows/met-cron-cd.yml
- .github/workflows/met-cron-ci.yml
- .github/workflows/met-etl-cd.yml
- .github/workflows/met-web-cd.yml
- .github/workflows/met-web-ci.yml
- .github/workflows/notify-api-cd.yml
- .github/workflows/notify-api-ci.yml
- .github/workflows/zap-scan-analytics-api.yml
- .github/workflows/zap-scan-api.yml
- .github/workflows/zap-scan-notify-api.yml
- .github/workflows/zap-scan-web.yml
- CHANGELOG.MD
Issue #: https://citz-gdx.atlassian.net/browse/DESENG-813
- Add Openshift installation step
- Scan each workflow to make sure we're not missing any other libraries
- Chose Ubuntu version to mitigate future issues
**User Guide update ticket (if applicable):** n/a
> DESENG-813 Chose Ubuntu version, add oc cli installation step

- CHANGELOG.MD
- docs/MET_database_ERD.md
- met-api/migrations/versions/85cbb8d956de_added_event_name_property_to_events.py
- met-api/src/met_api/models/event_item.py
- met-api/src/met_api/models/event_item_translation.py
- met-api/src/met_api/schemas/event_item_translation_schema.py
- met-api/src/met_api/schemas/schemas/event_item_translation.json
- met-api/src/met_api/services/event_item_translation_service.py
- met-api/src/met_api/services/widget_events_service.py
- met-api/tests/utilities/factory_scenarios.py
- met-api/tests/utilities/factory_utils.py
- met-web/src/components/common/index.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/EventInfoPaper.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/InPersonEventFormDrawer.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/VirtualEventInfoPaper.tsx
- met-web/src/components/engagement/form/EngagementWidgets/Events/VirtualSessionFormDrawer.tsx
- met-web/src/components/engagement/old-view/widgets/Events/EventsWidget.tsx
- met-web/src/components/engagement/old-view/widgets/Events/InPersonEvent.tsx
- met-web/src/components/engagement/old-view/widgets/Events/VirtualSession.tsx
- met-web/src/models/event.ts
- met-web/src/services/widgetService/EventService/index.tsx
- met-web/tests/unit/components/factory.ts
- **Feature** Redesign event widget [🎟️ DESENG-698](https://citz-gdx.atlassian.net/browse/DESENG-698)
- Modified api to accomodate additional field required in event widget design
- Modified forms and cards on admin side to show new field
- Implemented front-end design
- Tested with multiple events on one page
- Optimized for mobile and desktop viewports
- Updated unit test data
> Feature/deseng698 - Implemented event widget design

- CHANGELOG.MD
- met-etl/requirements.txt
Issue #: https://citz-gdx.atlassian.net/browse/DESENG-677
- Update dependencies to match met-api and hopefully build the Dockerfile
> DESENG-677: Fix SQLAlchemy dependency in MET ETL

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/analytics-api-cd.yml
- .github/workflows/met-api-cd.yml
- .github/workflows/met-cron-cd.yml
- .github/workflows/met-web-cd.yml
- .github/workflows/notify-api-cd.yml
- CHANGELOG.MD
- openshift/analytics-api/templates/hpa.yaml
- openshift/api/templates/hpa.yaml
- openshift/deploy.sh
- openshift/web/templates/hpa.yaml
Issue #: [🎟️ DESENG-847](https://citz-gdx.atlassian.net/browse/DESENG-847)
- **Bugfix** Finish upgrading DeploymentConfigs -> Deployments cross-app
- Completed the replacement of all deprecated DeploymentConfigs with Deployments across the application.
- Updated Helm charts and deployment scripts to reflect the changes.
**User Guide update ticket (if applicable):** _N/A_
> Finish upgrading DeploymentConfigs -> Deployments cross-app
