met-web/src/components/engagement/form/ActionContext.tsx
met-web/src/components/engagement/view/ActionContext.tsx
met-web/src/components/imageUpload/index.tsx
met-web/src/components/layout/Header/LoggedOutHeader.tsx
met-web/src/services/notificationService/notificationSlice.tsx
met-web/src/services/notificationService/types.ts
met-web/src/services/objectStorageService/index.ts
met-web/src/utils/index.ts

*Issue #:*
https://github.com/bcgov/met-public/issues/262
- Trigger alert message for failed banner image upload
- For logged out header only show title "Login To Met" on landing page
- remove padding for banner image display in engagement form

Add error dispatches for engagement uploading

---

met-web/src/components/engagement/view/EmailPanel.tsx
met-web/src/styles/Theme.ts

*Issue #:*
https://github.com/bcgov/met-public/issues/414
- Add terms and conditions to email verification modal
- Add spacing and update text sizing

Add terms and conditions text to email verification modal

---

met-web/src/components/engagement/form/EngagementForm.tsx
met-web/src/components/engagement/form/EngagementFormTabs.tsx
met-web/src/components/engagement/form/EngagementFormWrapper.tsx
met-web/src/components/engagement/form/EngagementSettings.tsx
met-web/src/components/engagement/form/StyledFormComponents.tsx
met-web/src/components/engagement/form/index.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/457
- Add tab panel for engagement details and settings
- Add engagement settings tab
- Add copy engagement view url in settings tab

Add settings tab for create engagement page

---

met-api/src/met_api/models/survey.py
met-cron/src/met_cron/services/survey_etl_service.py

Fixed Survey ETL to be based on updated_date
Fixed created_date and updated_date for survey
*Issue #:*

Fixed created_date and updated_date for survey

---

met-web/src/components/engagement/form/RichTextEditor.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/490
- Add handlePastedText={() => false} as prop to the Editor component following https://github.com/jpuri/react-draft-wysiwyg/issues/498

Fix Rich Text editor copying over background and font family

---

met-web/src/components/engagement/dashboard/report/CommentInfoModal.tsx
met-web/src/components/engagement/dashboard/report/EngagementDashboard.tsx
met-web/src/components/engagement/form/EngagementFormModal.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/483
- When engagement is still open and read comments is clicked a modal will appear explaining why user cannot view comments at that point

Create comment info modal

---

met-web/src/components/engagement/dashboard/report/EngagementDashboard.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/527
Added the engagement name to the what we heard report.

Show the engagement name in the dashboard

---

met-web/src/components/comments/admin/review/CommentReview.tsx
met-web/src/components/common/index.tsx
met-web/src/components/engagement/form/EngagementForm.tsx
met-web/src/components/engagement/view/EmailPanel.tsx
met-web/src/components/engagement/view/PreviewBanner.tsx
met-web/src/components/survey/building/index.tsx
met-web/src/components/survey/create/CreateOptions.tsx
met-web/src/components/survey/create/LinkOptions.tsx
met-web/src/components/survey/submit/SurveyForm.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/533
- Add missing loading animation to action buttons
- Replace primary button with MUI Lab LoadingButton

Add a reusable loading primary button

---

met-web/src/apiManager/endpoints/index.ts
met-web/src/components/LandingPage/LandingPage.tsx
met-web/src/components/comments/admin/reviewListing/index.tsx
met-web/src/components/comments/admin/textListing/index.tsx
met-web/src/components/common/Table/index.tsx
met-web/src/components/common/Table/types.ts
met-web/src/components/engagement/dashboard/comment/CommentTable.tsx
met-web/src/components/engagement/dashboard/comment/CommentViewContext.tsx
met-web/src/components/survey/listing/index.tsx
met-web/src/services/commentService/index.tsx
met-web/src/services/engagementService/index.ts
met-web/src/services/surveyService/form/index.ts
met-web/src/services/type.ts

*Issue #:*
https://github.com/bcgov/met-public/issues/561
- Configure MetTable to have server side pagination
- update listings pages: Engagements, surveys and comments

Make METTable and listing pages use server side pagination

---

met-api/src/met_api/resources/comment.py
met-api/src/met_api/resources/engagement.py
met-api/src/met_api/resources/survey.py

*Issue #:*
https://github.com/bcgov/met-public/issues/595
- args.get('sort_key', 'name', str) change third argument from int to str to fix sort_key always defaulting

Fix sort_key always defaulting to default value

---

met-api/src/met_api/models/comment.py
met-api/src/met_api/models/engagement.py
met-api/src/met_api/models/survey.py
met-api/src/met_api/resources/comment.py
met-api/src/met_api/resources/engagement.py
met-api/src/met_api/resources/survey.py
met-api/src/met_api/services/comment_service.py
met-api/src/met_api/services/engagement_service.py
met-api/src/met_api/services/survey_service.py
met-web/src/services/surveyService/form/index.ts

*Issue #:*
https://github.com/bcgov/met-public/issues/615
- If page and size are not passed to pagination resources all records will be returned
- Fix Select component triggering error when adding existing survey to engagement

Make paginated resources optionally return everything

---

.github/workflows/met-api-ci.yml
.github/workflows/met-web-ci.yml

*Issue #:*
https://github.com/bcgov/met-public/issues/625
When creating a PR from a fork repo, if the branch name is the same as the protected branch ('main') the coverage gets directly updated in Codecov. As a workaround this change will override the branch name with a prefix (PR_) if the CI is originating from a PR.

Fix CodeCov duplicated branch naming

---

met-web/src/components/common/Table/index.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/574
- Add a check if current nestedSortKet is equal to the column to activate the sort column

Fix multiple columns being active for sort

---

met-web/src/components/survey/listing/index.tsx
met-web/src/components/survey/submit/SurveySubmitWrapped.tsx
met-web/tests/unit/components/surveyListing.test.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/646
- Add unit test to check table rendering and rows fetching
- Add unit test to check search filter working and calling proper service method

Add unit tests for survey listing

---

met-api/migrations/versions/224b70277ac4_alter_commenttype.py
met-api/src/met_api/constants/feedback.py

*Issue #:*
https://github.com/bcgov/met-public/issues/337
Fixes submit feedback when comment type is not selected.

Fix comment type NONE

---

met-api/src/met_api/schemas/feedback.py
met-web/src/components/feedback/listing.tsx
met-web/src/models/feedback.ts
met-web/tests/unit/components/feedbackModal.test.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/337
Fixes display of feedback type (string instead of number)
Adds published date to feedback list

Fixes display of feedback type

---

met-web/src/components/engagement/form/EngagementSettings.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/707
- Remove extra character  '}' from copy url

Remove extra character from copy url

---

met-web/src/components/engagement/listing/index.tsx
met-web/src/components/survey/listing/index.tsx
met-web/src/components/survey/submit/EngagementLink.tsx
met-web/tests/unit/components/EngagementListing.test.tsx
met-web/tests/unit/components/surveyListing.test.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/413
Changes made on the engagement page to replace the status of Published with the status of the engagement:
Published/Upcoming
Published/Open
Published/Closed

change published with the status of the engagement

---

met-web/package.json
met-web/src/components/survey/building/index.tsx

*Issue #:*
Enable noeval in formio to avoid unsafe-eval CSP issue

Fix unsafe-eval with Evaluator.noeval = true

---

met-web/src/components/engagement/listing/index.tsx
met-web/src/components/survey/listing/index.tsx
met-web/src/constants/engagementStatus.ts

*Issue #:*
https://github.com/bcgov/met-public/issues/413
Changes made to handle closed engagements. Status for closed engagements/surveys should show as Published/Closed.

fixing a bug for closed engagement

---

met-etl/src/etl_project/services/jobs/met_data_ingestion.py
met-etl/src/etl_project/services/ops/comments_etl_service.py
met-etl/src/etl_project/services/ops/engagement_etl_service.py
met-etl/src/etl_project/services/ops/submission_etl_service.py
met-etl/src/etl_project/services/ops/survey_etl_service.py
met-etl/src/etl_project/services/ops/user_etl_service.py
met-etl/src/etl_project/services/schedules/met_data_ingestion_schedule.py

*Issue #:*
https://github.com/bcgov/met-public/issues/745
- Added logic to update the run cycle end time
- Updated the job run schedule to be every 30 mins

Re-write ETL jobs to dagster

---

met-api/src/met_api/resources/widget_documents.py
met-api/src/met_api/services/widget_documents_service.py
met-api/tests/unit/api/test_widget_document.py
met-api/tests/unit/services/test_widget_documents.py
met-api/tests/utilities/factory_scenarios.py
met-api/tests/utilities/factory_utils.py

*Issue #:*
https://github.com/bcgov/met-public/issues/162
https://github.com/bcgov/met-public/issues/163
- Add widget document api unit tests for GET and POST
- Add widget document service unit tests for GET and POST

Add service and api unit tests for widget documents

---

met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentFolder.tsx
met-web/src/components/engagement/form/EngagementWidgets/Documents/DocumentsBlock.tsx
met-web/src/components/engagement/form/EngagementWidgets/Documents/FileDrawer.tsx
met-web/tests/unit/components/EngagementFormDocumentWidget.test.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/163
- Add unit test to test document widget can be created
- test Folder form appearing
- test file form appearing

Add unit testing for document widgets

---

met-web/src/components/engagement/view/DocumentWidget.tsx

*Issue #:*
-Change document widget folder to MUI Stack for responsiveness

Make document widget more responsive on all screen sizes

---

met-web/package.json
met-web/src/components/common/dateHelper.tsx
met-web/src/components/engagement/banner/BannerWithImage.tsx
met-web/src/components/engagement/banner/BannerWithoutImage.tsx
met-web/src/components/engagement/view/PreviewBanner.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/940
- Fixed the issues with date formatting so that the app works on Firefox browser as well. Functions used to convert date to/from utc like utcToZonedTime and zonedTimeToUtc where causing issues on Firefox browser. Removed the dependency on these and instead used dayjs for date formatting.
- Changes made to remove the dependency on moment

fix for firefox date error

---

met-web/src/components/common/index.tsx
met-web/src/components/engagement/form/EngagementWidgets/Phases/PhasesForm.tsx
met-web/src/components/engagement/view/widgets/PhasesWidget/EngagementPhase.tsx
met-web/src/components/engagement/view/widgets/PhasesWidget/ForumIcon.tsx
met-web/src/components/engagement/view/widgets/PhasesWidget/IconBox.tsx
met-web/src/components/engagement/view/widgets/PhasesWidget/PhaseBox.tsx
met-web/src/components/engagement/view/widgets/PhasesWidget/PhasesWidgetMobile/EngagementPhaseMobile.tsx
met-web/src/components/engagement/view/widgets/PhasesWidget/PhasesWidgetMobile/PhaseBoxMobile.tsx
met-web/src/models/engagementPhases.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/979
- Grey out past phases
- Add custom forum icon
- Add current phase indicator
- Update background color for learn more boxes

Implement design tweaks to engagement phase component for desktop

---

met-web/src/components/engagement/view/widgets/PhasesWidget/PhaseBox.tsx
met-web/src/components/engagement/view/widgets/PhasesWidget/PhasesWidgetMobile/EngagementPhaseMobile.tsx
met-web/src/components/engagement/view/widgets/PhasesWidget/PhasesWidgetMobile/PhaseBoxMobile.tsx
met-web/src/components/engagement/view/widgets/PhasesWidget/index.tsx

*Issue #992 :*
https://github.com/bcgov/met-public/issues/#992
-Add Icon for current phase
-Add background color for phases that are not in the current phase

Add current phase Icon and background color for mobile process widget

---

met-web/src/components/survey/create/CloneOptions.tsx

*Issue #946 :*
https://github.com/bcgov/met-public/issues/946
-Consistent width & height between input fields for survey clone options

Make survey clone options text fields consistent

---

met-api/src/met_api/schemas/engagement.py
met-api/src/met_api/services/engagement_service.py
met-web/src/components/common/Modals/Schedule/index.tsx
met-web/src/components/engagement/form/EngagementForm.tsx
met-web/src/components/engagement/view/PreviewBanner.tsx

*Issue #402 :*
https://github.com/bcgov/met-public/issues/402
- Remove description and content as mandatory fields for engagement creation
-Add indicator in preview page that content and description is missing
-Prevent scheduling if engagement has no description or content
-Update back end by removing description and content as required fields for db

Remove rich description & content as mandatory fields for Engagement Form

---

met-api/src/met_api/services/widget_documents_service.py
met-api/tests/unit/models/test_widget_documents.py
met-api/tests/utilities/factory_scenarios.py

*Issue #1001 :*
https://github.com/bcgov/met-public/issues/1001
Expectation:
-When document folders or files are edited do not reorder the data files randomly.
Current version: 
-When documents are reordered they randomly shuffle order.
This pr:
-Sort folders by ascending id order to  make document order consistent in the widget tab 

Fix document reordering

---

met-web/src/components/engagement/form/ActionContext.tsx
met-web/src/components/engagement/form/AddSurveyBlock.tsx
met-web/src/components/engagement/form/AddSurveyBlockTabs.tsx
met-web/src/components/engagement/form/EngagementForm.tsx
met-web/src/components/engagement/form/types.ts
met-web/src/models/engagement.ts
met-web/src/models/engagementStatusBlock.ts
met-web/src/services/engagementService/types.ts
met-web/tests/unit/components/engagement/EngagementForm.test.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/397
Changes made to 
- insert status blocks data to engagement status block table in case the default values are updated during engagement creation
- update status blocks data for an engagement for any changes

survey block statuses tab updates

---

met-web/src/components/engagement/form/AddSurveyBlockTabs.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/397
Fix to save the state for each of the text that will appear in the survey block for each status.

fix to save the state for survey status block

---

met-web/src/components/engagement/view/PreviewBanner.tsx

*Issue #398 :*
https://github.com/bcgov/met-public/issues/398
-Change text to "Click to View Different Engagement status"
-Change label size to 13px
-Change padding to 8px
-Change border color to #cdcdcd

UI Tweaks to Preview Status Box

---

met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/AddContactDrawer.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/991
Changes made to check if edited contact has the image file name in the form then use it else use fetched data.

fix for edit contact profile picture

---

met-web/src/components/common/index.tsx
met-web/src/components/engagement/form/EngagementWidgets/Documents/CreateFolderForm.tsx
met-web/src/styles/Theme.ts

*Issue #1027 :*
*Issue #1102 :*
https://github.com/bcgov/met-public/issues/1027
https://github.com/bcgov/met-public/issues/1102
-Make all text fields and buttons 40px height & width
-Remove button overlap for document widget

Make Styling Consistent and Remove Document Widget bugs

---

met-web/src/components/engagement/form/EngagementWidgets/Documents/CreateFolderForm.tsx

*Issue #1116 :*
https://github.com/bcgov/met-public/issues/1116
Currently in the document widget, if you do not add a name to a folder it can still be created
- move the validation check into the try catch block

Prevent empty folders in Document Widget

---

met-api/src/met_api/config.py
met-api/src/met_api/models/comment.py
met-api/src/met_api/utils/roles.py
met-web/src/components/engagement/dashboard/comment/CommentViewContext.tsx
met-web/src/components/engagement/dashboard/comment/CommentsBlock.tsx
met-web/src/components/engagement/dashboard/report/EngagementDashboard.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/1022
- Add new role for dashboard access
- Survey email to have the link for comments
- Dashboard access to public should be restricted until engagement is closed.
- Both dashboard and comments should be accessible to users having dashboard access role

changes for comments/dashboard access

---

met-web/src/components/common/Table/index.tsx
met-web/src/components/engagement/dashboard/comment/CommentTable.tsx
met-web/src/components/engagement/dashboard/comment/CommentViewContext.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/1022
Changes to pop up a message to inform public user that there are no approved comments on the engagement.

handle empty comment listing

---

met-web/src/components/engagement/view/EngagementView.tsx
met-web/src/components/engagement/view/widgets/WhoIsListeningWidget.tsx

*Issue #1128:*
https://github.com/bcgov/met-public/issues/1128
-Remove some margin top on widget block
-Add more spacing for bio on who is listening widget

Align Widgets

---

met-web/src/components/layout/Header/InternalHeader.tsx
met-web/src/components/layout/SideNav/SideNav.tsx

*Issue #990:*
https://github.com/bcgov/met-public/issues/990
-make side nav full screen on mobile

Make side nav cover banner on mobile

---

met-web/src/components/engagement/view/widgets/Events/InPersonEvent.tsx
met-web/src/components/engagement/view/widgets/Events/VirtualSession.tsx

*Issue #1184 :*
https://github.com/bcgov/met-public/issues/1184
-Make the event widget more responsiveness at different sizes

Update spacing for responsiveness in events widget

---

met-web/src/components/engagement/view/widgets/Events/VirtualSession.tsx

*Issue #1184 :*
https://github.com/bcgov/met-public/issues/1184
-make url open a new tab

Make public widget link open a new tab

---

met-api/src/met_api/resources/engagement_members.py
met-api/src/met_api/services/engagement_service.py
met-api/src/met_api/services/membership_service.py
met-api/src/met_api/utils/roles.py
met-web/src/apiManager/endpoints/index.ts
met-web/src/components/engagement/form/ActionContext.tsx
met-web/src/components/engagement/form/EngagementFormTabs/EngagementForm.tsx
met-web/src/components/permissionsGate/PermissionMaps.tsx
met-web/src/services/membershipService/index.tsx
met-web/src/services/userService/index.ts
met-web/src/services/userService/types.ts
met-web/src/services/userService/userSlice.ts
met-web/tests/unit/components/engagement/EngagementForm.test.tsx
met-web/tests/unit/components/engagement/EngagementFormUserTab.test.tsx
met-web/tests/unit/components/widgets/DocumentWidget.test.tsx
met-web/tests/unit/components/widgets/EventsWidget.test.tsx
met-web/tests/unit/components/widgets/PhasesWidget.test.tsx
met-web/tests/unit/components/widgets/WhoIsListeningWidget.test.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/1281
- Allow team members to visit engagement form page for their engagements only
- fix team members draft engagement filter
- Add assigned engagement ids to redux
- Mock use selector in unit tests

Restrict access to engagement form page for team members

---

met-web/src/components/common/index.tsx
met-web/src/components/engagement/view/SurveyBlock.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/1230
fix added to disable "Take me to the survey" button while previewing the closed status.

bug fix for preview of closed status

---

met-web/package-lock.json
met-web/package.json

*Issue #:*
https://github.com/bcgov/met-public/issues/1290
- https://github.com/mapbox/mapbox-gl-js/issues/10240
- downgrade maplibre to older version where uglify v >2 wasn't used

Downgrade maplibre library

---

met-api/src/met_api/models/submission.py
met-api/tests/unit/services/test_submission.py

*Issue #:*
https://github.com/bcgov/met-public/issues/1370
changes to auto approve submissions which:
- do not have a textarea or textfield in the submission json
- has textarea or textfield in the submission json but have a null value
changes to exclude auto approved submissions from comment listing page as they do not have a comment

adding logic to auto aprv submission without cmnt

---

met-web/src/components/engagement/view/EngagementInfoSection.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/1411
changes made to use the mock status only for preview else use the status of the saved engagement.

fix for engagement status badget

---

met-web/src/components/engagement/form/EngagementWidgets/Map/Form.tsx

*Issue #1382 :*
https://github.com/bcgov/met-public/issues/1382
-Add label under form headers

add labels to map widget form

---

met-web/sample.env
met-web/src/components/engagement/form/EngagementFormTabs/EngagementSettings.tsx
met-web/src/components/engagement/form/EngagementFormTabs/constants.ts
met-web/src/components/landing/LandingComponent.tsx
met-web/src/config.ts

*Issue #:*
https://github.com/bcgov/met-public/issues/1450
- Add an engagement project types variable in config
- Add project types in met-web config maps for dev, test, and prod
- Add project types in local sample.env

Externalize engagement project types to env variable

---

met-web/src/components/map/index.tsx

*Issue #1446 :*
https://github.com/bcgov/met-public/issues/1446
-Add layer line layer to map widget

display shapefiles with only lines

---

met-web/src/components/landing/LandingComponent.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/1461
- Add a didMount state initialized as false, set it to true after initial mount

Fix landing page scrolling to filters on initial mount 

---

met-api/src/met_api/schemas/survey.py
met-web/src/components/survey/listing/index.tsx
met-web/src/models/survey.ts
met-web/tests/unit/components/surveyListing.test.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/1418
- Add comment count badges to survey listing page

Add comment count badges to survey listing page

---

met-web/src/components/survey/building/index.tsx
met-web/src/components/survey/create/CreateOptions.tsx

*Issue #1453 :*
https://github.com/bcgov/met-public/issues/1453
-Added auto-complete component to start survey as multi-page
-Added a modal to warn users that switching survey type will remove all their current progress

Add multi page option in survey creation

---

met-web/src/App.tsx

*Issue #:*
https://github.com/bcgov/met-public/issues/1472
- Fix basename check in App.tsx

Redirect app to /eao at the beginning if no valid basename was present

---

met-api/src/met_api/resources/submission.py
met-api/src/met_api/services/submission_service.py
met-api/tests/unit/api/test_submission.py

*Issue #:*
https://github.com/bcgov/met-public/issues/1464
- Pass exclude=['submission_json'] to submission schema during Marshalling

Exclude submission json during submission fetch

---

met-api/src/met_api/models/survey.py
met-web/src/components/survey/building/index.tsx

https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/1366
- disable is hidden switch on the screen if survey is linked to an engagement

fixes for saving a survey as hidden

---

met-api/src/met_api/resources/survey.py
met-api/src/met_api/services/survey_service.py
met-api/src/met_api/utils/roles.py
met-api/tests/unit/api/test_survey.py
met-api/tests/utilities/factory_scenarios.py
met-api/tests/utilities/factory_utils.py
met-web/src/components/survey/building/index.tsx

https://app.zenhub.com/workspaces/met-ops-6254279dcfa60b0010ea5a0d/issues/gh/bcgov/met-public/1367
- Added a new role to check user access while editing a template survey
- Logic to restrict users without a role to edit template surveys

implement restrictions on edit template surveys

---

met-web/src/components/engagement/form/EngagementFormTabs/EngagementForm.tsx

#1414 
-Add character count to description

Add character count to engagement form description

---

met-web/src/components/engagement/status/index.tsx
met-web/src/components/landing/EngagementTile.tsx
met-web/src/components/landing/LandingComponent.tsx
met-web/src/components/landing/LandingContext.tsx

-change the status drop down on homepage to handle Upcoming, Open & Closed engagements
-added a time calculation to display upcoming engagements vs open engagements

Update home page statuses to open, upcoming & closed

---

met-web/src/components/survey/submit/Stepper.tsx

-Only display text on the current stepper for mobile

mobile responsiveness for progress bar

---

met-cron/pre-hook-update-db.sh

MET-CRON project no longer connects to DB directly.. so no need to run the migration scripts

No migration needed since this project no longer connects to DB

---

met-web/src/components/userManagement/userDetails/AddToEngagement.tsx

UX Assurance for task #720 
-Add filter to remove engagements the user is already a part of

Filter engagements the user is already a part of for add engagement modal

---

met-web/src/components/engagement/listing/index.tsx
met-web/src/components/survey/listing/index.tsx

- Add tooltips for comments icons in engagement listing page
- Add tooltips for comments icons in survey listing page
- Disable interactivity on tooltips so they don't remain open when hovered over them

Add tooltips for comment icons in engagement and survey listing pages

---

met-web/src/components/Form/formio-bootstrap.scss
met-web/src/components/survey/submit/Stepper.tsx
met-web/src/styles/Theme.ts

Task:
The current color for paragraph is set to #666666 and the unvisited page name is #000000 at 60% opacity.
All text has to be #494949
-updated form stepper & paragraph to be #494949 
-update form io links to always be underlined & to be the color #1a5a96

Update form io text & link color

---

met-api/src/met_api/utils/enums.py
met-api/tests/unit/api/test_engagement_membership.py
met-api/tests/unit/api/test_user.py
met-api/tests/utilities/factory_scenarios.py

- Add a test for adding reviewer to KC group
- Add test_engagement_membership test
- Add tests for creating memberships for team member and reviewer

Add unit tests for adding to kc group and creating memberships

---

met-web/src/components/layout/SideNav/SideNav.tsx
met-web/src/components/layout/SideNav/UserGuideNav.tsx
met-web/src/helper/index.ts
met-web/src/routes/AuthenticatedRoutes.tsx

- Add example help paths
- Use Levenshtein distance to determine the help page that corresponds to the current route
- Add user guide list item in side nav

Add user guide logic and list item in sidenav

---

met-web/src/models/engagementPhases.tsx

-update colors for accessibility

Update colors for engagement phases

---

met-api/src/met_api/models/survey.py
met-web/src/components/survey/listing/AdvancedSearch.tsx

- Add icons in advanced search status filter

Add icons in survey advanced search status filter

---

met-web/package-lock.json
met-web/package.json

- revert node-sass bump back to "^7.0.3" because it is compatible with node 14 and that is what we are using in our deployment

Revert node-sass bump

---

met-web/src/components/engagement/view/widgets/Video/VideoWidgetView.tsx
met-web/src/components/landing/EngagementTile.tsx

- add hover and click effect on engagement tile

Make engagement tiles clickable

---

met-web/src/components/engagement/view/widgets/Video/VideoWidgetView.tsx
met-web/src/components/landing/LandingComponent.tsx

- Replace search bar in homepage from autocomplete to textfield
- useDebounce on search text change at 300ms

Replace search bar in homepage from autocomplete to textfield

---

met-web/src/components/comments/admin/reviewListing/AdvancedSearch.tsx
met-web/src/components/comments/admin/reviewListing/Submissions.tsx

- Adding padding between the search and header.
- The size of "Reset All Filters" should match the size of other buttons, and remove "Filter by" for all the dates fields in the advanced search and change Filter from "Reviewed Date" to "Review Date”.

UI tweaks for the comment listing page

---

met-web/src/components/Form/formio.scss

-update wizard buttons to match material ui styles

update form io button styles to match material ui 

---

met-api/src/met_api/services/engagement_metadata_service.py
met-api/src/met_api/services/engagement_service.py
met-api/src/met_api/services/engagement_settings_service.py
met-web/src/components/engagement/form/EngagementFormTabs/Links/PublicUrls.tsx
met-web/src/components/engagement/form/EngagementFormTabs/Settings/EngagementInformation.tsx
met-web/src/components/engagement/form/EngagementFormTabs/Settings/EngagementSettingsContext.tsx
met-web/src/components/engagement/form/EngagementFormTabs/Settings/InternalEngagement.tsx
met-web/src/components/engagement/form/EngagementFormTabs/Settings/SendReport.tsx

- Update text
- Add an update restriction based on engagement status

Engagement settings UX/UI fixes

---

met-web/src/components/publicDashboard/SubmissionTrend/SubmissionTrend.tsx

-Dashboard touch ups requested for less then 300 px phone responsivenss 
-general margin for a better layout

Dashboard Touch ups for ultra small screen

---

met-web/src/components/publicDashboard/SubmissionTrend/SubmissionTrend.tsx

-Requested by Ian: remove calendar icons on dashboard for extra small screens since they block placeholder text

Remove icons for dashboard on extra small screens

---

met-web/src/apiManager/apiSlices/widgets/index.ts
met-web/src/components/engagement/form/EngagementWidgets/Phases/PhasesForm.tsx
met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/WhoIsListeningForm.tsx
met-web/src/services/widgetService/DocumentService/index.tsx
met-web/src/services/widgetService/index.tsx
met-web/tests/unit/components/widgets/PhasesWidget.test.tsx
met-web/tests/unit/components/widgets/WhoIsListeningWidget.test.tsx

- Use redux rtk for posting items
- Set redux rtk create items to invalidate widgets

Invalidate widgets when creating widget items

---

met-api/src/met_api/models/survey.py

https://github.com/bcgov/met-public/issues/1899
Viewers shouldnt get access to scheduled surveys/engagements

Scheduled surveys cant be viewed by unauthorized

---

met-api/src/met_api/models/engagement.py
met-api/src/met_api/services/membership_service.py

https://github.com/bcgov/met-public/issues/2006
- Added the is active check
- Added a missing join condition
- Added auth checks

Added permissions for revoked membership

---

met-web/src/components/userManagement/listing/ActionsDropDown.tsx
met-web/src/components/userManagement/listing/AddUserModal.tsx
met-web/src/components/userManagement/userDetails/AddToEngagement.tsx
met-web/src/services/engagementService/index.ts

Issue #: https://github.com/bcgov/met-public/issues/1910
- Removed assign role drop down for TM on user listing
- Removed assign to an engagement for Viewer on user listing
- Added check to list only assigned engagements for TM trying to assign engagement to another TM/Reviewer

Remove assign role from TM

---

met-api/src/met_api/schemas/membership_engagement.py
met-web/src/components/userManagement/userDetails/AssignedEngagementsListing.tsx

Issue #: https://github.com/bcgov/met-public/issues/2049
- update engagement link in user details table
- update membership schema to only take id and name from engagement

Only get id and name of engagement for membership

---

met-api/src/met_api/config.py
met-api/src/met_api/services/email_verification_service.py
met-api/src/met_api/services/engagement_service.py
met-api/src/met_api/services/staff_user_service.py
met-api/src/met_api/services/submission_service.py

Issue #: https://github.com/bcgov/met-public/issues/2017
- Add a get gc notify config method
- Structure gc notify configs to have default and ability to have tenant name as key

update email config to be dynamic with the tenant

---

met-web/src/components/userManagement/listing/AddUserModal.tsx

- Currently TM is not able to assign an engagement to which the user is assigned to another TM/Reviewer
- This change is to fix this by temporarily removing the check for assigned engagements

Allow TM to assign engagements user is assigned to

---

met-web/src/components/comments/admin/reviewListing/Submissions.tsx
met-web/src/components/userManagement/userDetails/AddToEngagement.tsx

- Currently TM is not able to assign an engagement to which the user is assigned to another TM/Reviewer from user details page
- This change is to fix this bug

fix TM not able to assign engagement from user details

---

met-api/src/met_api/models/membership.py
met-api/src/met_api/resources/staff_user.py
met-api/src/met_api/services/membership_service.py
met-api/src/met_api/services/staff_user_membership_service.py
met-api/src/met_api/services/staff_user_service.py
met-api/tests/unit/api/test_user_membership.py
met-api/tests/utilities/factory_scenarios.py
met-web/src/components/userManagement/listing/ActionsDropDown.tsx

Issue #: https://github.com/bcgov/met-public/issues/1907
- Remove reinstate memberships logic
- Fix Reassign Role typo in drop down
We are removing reinstate membership logic above because it can create an access risk. It is better managed manually to readd users to engagements they were revoked on when their role is changed

Remove reinstate memberships functionality

---

met-web/package.json

Update formio version from 1.0.11 -> 1.0.12

update formio version for met-web

---

met-api/src/met_api/models/staff_user.py
met-api/src/met_api/resources/staff_user.py
met-api/src/met_api/services/membership_service.py
met-api/src/met_api/services/staff_user_membership_service.py
met-api/src/met_api/services/staff_user_service.py
met-web/src/components/userManagement/listing/ActionsDropDown.tsx
met-web/src/components/userManagement/listing/UserManagementContext.tsx
met-web/src/components/userManagement/userDetails/ActionsDropDown.tsx
met-web/src/components/userManagement/userDetails/AddToEngagement.tsx
met-web/src/components/userManagement/userDetails/UserDetails.tsx
met-web/src/components/userManagement/userDetails/UserDetailsContext.tsx
met-web/src/components/userManagement/userDetails/UserStatusButton.tsx
met-web/src/constants/httpResponseCodes.ts
met-web/src/services/userService/api/index.tsx

- Add a default filter to filter out inactive user on fetching a single or a list of users
- Add include_inactive flag
- Make include_inactive flag true only for operations allowed on inactive user, like activate user

Restrict actions on inactive user

---

met-web/src/components/engagement/form/EngagementFormTabs/EngagementTabsContext.tsx
met-web/tests/unit/components/engagement/EngagementFormUserTab.test.tsx
met-web/tests/unit/components/engagement/form/create/EngagementForm.Create.test.tsx
met-web/tests/unit/components/engagement/form/edit/EngagementForm.Edit.One.test.tsx
met-web/tests/unit/components/engagement/form/edit/EngagementForm.Edit.Two.test.tsx
met-web/tests/unit/components/factory.ts

Issue #: https://github.com/bcgov/met-public/issues/2077
- Split EngagementForm.Edit into two tests
- Add missing mocks

Fix test error logs in EngagementForm tests

---

met-web/src/components/landing/EngagementTile.tsx

-Change boolean to check submission_status instead of status_id to match engagement tile badge

Make Engagement Tiles consistent with submission_status

---

met-api/src/met_api/models/survey.py
met-api/src/met_api/services/email_verification_service.py
met-api/tests/unit/models/test_survey.py

- The survey get_open was wrongly factored in timestamps  since engagement start date and end dates are just days.
Fixed to remove timestamp in the date calculation.
- Get_open is not needed while fetching email validations.validations are already handled on the submit of the surveys

fixed date handling in open survey fetch

---

met-web/src/components/userManagement/listing/UserManagementListing.tsx

Issue #: https://github.com/bcgov/met-public/issues/2110
-Disable sorting by role for user management listing

Disable sorting by role for user management

---

met-api/src/met_api/models/staff_user.py

Server_default was not working;probably bcoz there is no database constraint..easiser option is to work with default.so switching back to it

Fix for New Staff users were getting blank status

---

met-web/src/components/FormioModalListener/index.tsx
met-web/src/components/scrollToTop/index.tsx
met-web/src/routes/AuthenticatedRoutes.tsx

Issue #: https://github.com/bcgov/met-public/issues/1327
-Add a listener that unrenders the formio modal on switching routes

Formio modal bug fix

---

met-web/src/components/Form/formio.scss
met-web/src/components/engagement/form/EngagementWidgets/Documents/StyledTreeItem.tsx
met-web/src/components/engagement/form/EngagementWidgets/Documents/TreeView.tsx

Issue: #1830 
-Make document arrow slightly bigger

Update document widget arrow size

---

met-web/src/components/engagement/form/ActionContext.tsx
met-web/src/components/engagement/form/EngagementFormTabs/EngagementTabsContext.tsx
met-web/src/routes/RedirectLogin.tsx
met-web/src/routes/UnauthenticatedRoutes.tsx
met-web/src/services/userService/index.ts
met-web/tests/unit/components/comment/CommentListing.test.tsx
met-web/tests/unit/components/engagement/EngagementFormUserTab.test.tsx
met-web/tests/unit/components/engagement/form/create/EngagementForm.Create.test.tsx
met-web/tests/unit/components/engagement/form/edit/EngagementForm.Edit.One.test.tsx
met-web/tests/unit/components/engagement/form/edit/EngagementForm.Edit.Two.test.tsx
met-web/tests/unit/components/widgets/DocumentWidget.test.tsx
met-web/tests/unit/components/widgets/EventsWidget.test.tsx
met-web/tests/unit/components/widgets/MapWidget.test.tsx
met-web/tests/unit/components/widgets/PhasesWidget.test.tsx
met-web/tests/unit/components/widgets/WhoIsListeningWidget.test.tsx

Issue #: https://github.com/bcgov/met-public/issues/2184
- Pull project Id from query params to project metadata in engagement create
- If loggedout redirect to login and redirect back when visiting engagement create

Pull projectId from query params and redirect to login

---

.github/workflows/analytics-api-cd.yml
.github/workflows/met-api-cd.yml
.github/workflows/met-cron-cd.yml
.github/workflows/met-etl-cd.yml
.github/workflows/met-web-cd.yml
.github/workflows/notify-api-cd.yml

- Workflow should now push/deploy images to the EAO environment by default
- Users will have to manually run actions if they wish to deploy to GDX 

Updating Github actions to use EAO as default Environment

---

met-web/Dockerfile

- Updating base image to node 16 in order to fix failing image build stage 

updating Docker file base Image

---

met-web/src/components/engagement/form/EngagementFormTabs/EngagementForm.tsx

Issue #: https://github.com/bcgov/met-public/issues/1433
- fetch engagement after update it

Persist engagement banner after save is pressed

---

met-web/src/components/engagement/form/EngagementFormTabs/EngagementForm.tsx

Issue #: https://github.com/bcgov/met-public/issues/2265
- Disable date fields when engagement is closed or unpublished

Disable date fields when engagement is closed or unpublished

---

met-web/src/components/engagement/view/EngagementBanner/BannerSection.tsx
met-web/src/components/engagement/view/EngagementBanner/StandAloneBanner.tsx
met-web/src/components/engagement/view/EngagementBanner/index.tsx
met-web/src/components/engagement/view/EngagementView.tsx
met-web/src/web-components/components/engagement-banner-wc.tsx

Issue #: https://github.com/bcgov/met-public/issues/2281
- Remove the survey button from the banner section
- Make the survey button an optional prop that optionally renders
- Pass the survey button to the standalone banner but not the original met banner

Make share thoughts button optional

---

met-web/src/components/layout/SideNav/UserGuideNav.tsx
met-web/src/components/publicDashboard/SurveyBar/index.tsx

Issue #:
- Fix navigation to user guide for read all comments
- Choose first question survey results by default

Fix link to read all comments guide and survey results question highlight

---

met-web/src/services/userService/index.ts

Once token is refreshed , the new refreshed token is stored in the session storage

Added refreshed tokens to session storage

---

met-api/src/met_api/models/comment.py
met-api/src/met_api/models/engagement_slug.py
met-api/src/met_api/schemas/engagement.py

- add the find by method for slug to behave case-insensitive..so that something like engage.eao.gov.bc.ca/my-test-eng and engage.eao.gov.bc.ca/MY-TEST-ENG works
- removed some unnecessary print statements
- Handled big with submission fetch.. the query was fetching multiple records of submissions since it was doing an inner join with comments table and there for it messed up the pagination/sort order etc.Handled it in a different way so that no join is manually done.

Made slug url case insensitive , Fixed bug with wrong query join for submission

---

met-api/src/met_api/models/comment.py
met-api/src/met_api/models/engagement_slug.py
met-api/src/met_api/schemas/engagement.py
met-api/src/met_api/services/comment_service.py

Issue #: N/A
Bringing 3 bug fixes forward from the EAO team's `main` branch:
- Make fetching by URL slug case insensitive
- Fixing a bug in the submission query filter
- Add CSV exporting functionality

Bring bugfixes from main into gdx-dev

---

.github/CODEOWNERS

Issue #: N/A
Update the .github/CODEOWNERS special file to automatically request review from @bcgov/gdx-engagement-admin and @kshapka-bcgov.

Transfer code ownership to GDX Admin

---

met-api/src/met_api/resources/widget_poll.py

Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-464
Updating return of poll widget get to use jsonify

Testign dev server view error response

---

CHANGELOG.MD
met-web/src/components/engagement/form/EngagementFormTabs/FormTabs.tsx
met-web/src/components/engagement/form/EngagementFormTabs/constants.ts
met-web/tests/unit/components/engagement/form/edit/EngagementForm.Edit.One.test.tsx

Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-489
Updated text "engagement core" to "engagement content"

DESENG-489: engagement core to engagement content

---

CHANGELOG.MD
met-api/src/met_api/services/engagement_service.py
met-api/src/met_api/services/membership_service.py
met-api/src/met_api/services/staff_user_service.py
met-api/src/met_api/utils/constants.py
met-api/src/met_api/utils/enums.py
met-api/src/met_api/utils/roles.py
met-api/src/met_api/utils/tenant_validator.py
met-web/src/components/engagement/view/PreviewBanner.tsx
met-web/src/components/survey/building/index.tsx
met-web/src/components/survey/listing/Surveys.tsx
met-web/src/components/userManagement/listing/AssignRoleModal.tsx
met-web/src/components/userManagement/listing/ReassignRoleModal.tsx
met-web/src/models/user.ts

Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-476
Updated Superuser to Administrator

DESENG-476 - Superuser to Administrator

---

CHANGELOG.MD
met-web/src/components/engagement/form/EngagementFormTabs/AdditionalDetails/AdditionalTabContent.tsx
met-web/src/components/engagement/form/EngagementFormTabs/EngagementForm.tsx
met-web/src/components/engagement/form/EngagementFormTabs/EngagementTabsContext.tsx
met-web/src/components/engagement/form/EngagementFormTabs/Settings/EngagementSettingsForm.tsx
met-web/src/components/engagement/form/EngagementFormTabs/UserManagement/EngagementUserManagement.tsx
met-web/tests/unit/components/engagement/form/create/EngagementForm.Create.test.tsx
met-web/tests/unit/components/engagement/form/edit/EngagementForm.Edit.One.test.tsx

Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-498
Implemented a floating behavior for the save/preview buttons during engagement editing. This feature persists across all tabs but exclusively saves data for the Engagement Content tab.

Implemented floating save/preview buttons for engagement editing

---

met-api/tests/unit/api/test_engagement_content.py
met-api/tests/unit/api/test_engagement_custom_content.py
met-api/tests/unit/api/test_engagement_summary_content.py
met-api/tests/utilities/factory_scenarios.py

Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-500
Added unit tests for dynamic engagement pages

Unit Tests for dynamic engagement pages

---

CHANGELOG.MD
met-web/src/components/engagement/listing/AdvancedSearch/SearchComponent.tsx

Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-525
Resetting search filter values invokes the list to reload

[To Main] DESENG-525: Resetting engagement list on reset button

---

CHANGELOG.MD
met-api/src/met_api/services/metadata_taxon_service.py
met-web/src/apiManager/endpoints/index.ts
met-web/src/components/engagement/form/EngagementFormTabs/EngagementTabsContext.tsx
met-web/src/components/landing/DeletableFilterChip.tsx
met-web/src/components/landing/FilterBlock.tsx
met-web/src/components/landing/FilterDrawer.tsx
met-web/src/components/landing/LandingComponent.tsx
met-web/src/components/landing/LandingContext.tsx
met-web/src/components/landing/MetadataFilterChip.tsx
met-web/src/components/landing/TileBlock.tsx
met-web/src/components/metadataManagement/MetadataFilterTypes.tsx
met-web/src/components/metadataManagement/TaxonCard.tsx
met-web/src/components/metadataManagement/TaxonEditForm.tsx
met-web/src/components/metadataManagement/TaxonEditor.tsx
met-web/src/components/metadataManagement/TaxonTypes.tsx
met-web/src/components/metadataManagement/presetFieldsEditor/PresetValuesEditor.tsx
met-web/src/components/metadataManagement/types.ts
met-web/src/locales/en/default.json
met-web/src/models/engagement.ts
met-web/src/services/engagementMetadataService/index.ts
met-web/src/services/engagementService/index.ts
met-web/tests/unit/components/landingPage/LandingPage.test.tsx

Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-445
- Updated the Metadata Management UI to allow taxa to be marked as filterable.
- Currently, the only two filter types are `chips_any` and `chips_all`.
- `chips_any`: Displays as a series of toggleable buttons ("chips"), uses the `list_match_any` subquery returning engagements with any of the selected values.
- `chips_all`: Similar to chips_any; uses the `list_match_all` subquery to get only engagements with ALL of the selected values.
- If multiple filterable taxa are selected, all the taxon filters must be met for an engagement to be returned.
- Updated the public-facing engagement list to allow filtering by metadata taxa. This makes use of the new API endpoint to retrieve filterable taxa.
- Added a new filter "drawer" to the …

[To Feature] DESENG-445/frontend

---

CHANGELOG.MD
met-api/src/met_api/services/keycloak.py
met-api/tests/unit/api/test_engagement_membership.py
met-api/tests/unit/api/test_user.py
met-api/tests/unit/api/test_user_membership.py
met-api/tests/unit/services/test_keycloak.py

Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-508
Updated Keycloak Unit Tests for New CSS API Integration.

[ To Main ] - DESENG-508 - Updated Keycloak unit test for new CSS API

---

CHANGELOG.MD
met-api/sample.env
met-api/src/met_api/config.py
met-api/src/met_api/utils/notification.py
met-api/tests/unit/utils/test_notification.py
openshift/api.dc.yml

Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-533
- Enabled dev open shift to use GC_NOTIFY api key of test which allows all email.
- Added new env var `SEND_EMAIL_INTERNAL_ONLY` to allow for internal emails such as govt emails only.

DESENG-533: Internal email check

---

CHANGELOG.MD
met-api/src/met_api/services/submission_service.py
met-api/tests/unit/api/test_submission.py
met-api/tests/unit/services/test_submission.py
met-api/tests/utilities/factory_utils.py

Issue #: [🎟️ DESENG-527](https://apps.itsm.gov.bc.ca/jira/browse/DESENG-527)
- **Bugfix**: Submission of rejected comments [🎟️ DESENG-527](https://apps.itsm.gov.bc.ca/jira/browse/DESENG-527)
- Fixed issue where resubmitted comments would not reappear in the queue for approval.
- Added unit tests to ensure the issue does not reoccur.

[To Main] Bugfix: Comments do not update when editing rejected comments [DESENG-527]

---

CHANGELOG.MD
met-web/src/App.scss

Issue #: [🎟️ DESENG-577](https://apps.itsm.gov.bc.ca/jira/browse/DESENG-577)
- **Task**: CSS Selector specificity 
- Replace the `!important` flag with more specific CSS selectors, specifically within dropdowns,
to ensure that the correct styles are applied, and that states we have not yet designed for
(e.g, complex focus states) are still styled appropriately and in an accessible manner.
- Soon, we will be doing a more in-depth revamp of dropdowns in the app to make them more
accessible and user-friendly. This helps work towards that goal.

[To Main / DESENG-577] Being more specific with CSS selectors

---

CHANGELOG.MD
met-web/src/components/engagement/form/ActionContext.tsx
met-web/src/components/engagement/form/EngagementFormTabs/EngagementContent/ContentTabs.tsx
met-web/src/components/engagement/form/EngagementFormTabs/EngagementTabsContext.tsx

Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-541
- Implemented notifications for successful saves across all engagement tabs.
- Resolved issue with saving engagement summary content during engagement creation.
- Updated tooltip on engagement content to use MetTooltip for consistency.

[To Main] DESENG-541: Added save notifications for all engagement tabs

---

CHANGELOG.MD
met-api/migrations/versions/e4d15a1af865_remove_default_taxon_data.py

Issue #: [DESENG-578](https://apps.itsm.gov.bc.ca/jira/browse/DESENG-578)
- **Task** Remove default taxa from GDX tenant [DESENG-578](https://apps.itsm.gov.bc.ca/jira/browse/DESENG-578)
- Removed the pre-populated taxon entries from the GDX tenant.
- With the power of the editor interface, tenants are now expected to create their own taxon entries.

[To Main / DESENG-578] Remove default taxon data

---

CHANGELOG.MD
openshift/cron.bc.yml

- **Task** Openshift - Update the buildconfig for the MET-cron job runner [🎟️ DESENG-559](https://apps.itsm.gov.bc.ca/jira/browse/DESENG-559)
- Versioning now uses the openshift.io namespace
- Changed some item descriptions
- This solves an error where `oc process` wouldn't read the file and create JSONs for it

[To Main] Openshift - update buildconfig yaml

---

CHANGELOG.MD
met-api/src/met_api/models/staff_user.py
met-api/tests/unit/api/test_user.py

Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-478
- Tested users can belong to more than one tenant.
- Override the default tenant filter for the **staff_user** table to check with the **user_group_membership** table.
Note : tenant_id is left as it is in the staff_user table to track the tenant_id of the user when it is created first time. 

[To Main] DESENG-478 - Override _add_tenant_filter to check in user group membership table for tenant mapping

---

met-web/src/components/imageUpload/Uploader.tsx
met-web/src/components/tenantManagement/TenantForm.tsx
met-web/tests/unit/components/tenantManagement/CreateTenant.test.tsx
met-web/tests/unit/components/tenantManagement/EditTenant.test.tsx
met-web/tests/unit/components/tenantManagement/TenantDetail.test.tsx

Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-605
Completion of unit test suite for tenant frontend CRUD

[To Feature] DESENG-605-606-unit-tests

---

CHANGELOG.MD
met-api/sample.env
met-api/src/met_api/config.py
met-web/src/App.tsx
met-web/src/components/engagement/dashboard/comment/CommentsBlock.tsx
met-web/src/components/engagement/view/SurveyBlock.tsx
met-web/src/components/engagement/view/widgets/Subscribe/FormSignUpSection.tsx
met-web/src/components/landing/EngagementTile.tsx
met-web/src/components/layout/Footer/index.tsx
met-web/src/components/layout/Header/PublicHeader.tsx
met-web/src/components/publicDashboard/Dashboard.tsx
met-web/src/components/survey/edit/FormWrapped.tsx
met-web/src/components/survey/submit/ActionContext.tsx
met-web/src/components/survey/submit/SurveySubmitWrapped.tsx
met-web/src/routes/LanguageParam.tsx
met-web/src/routes/NotFound.tsx
met-web/src/routes/UnauthenticatedRoutes.tsx
met-web/src/services/userService/index.ts

Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-625
- Removed language from URLs other than engagement/survey links
- Fixed the issue of null appearing in public URLs

[To Main] Fix for issue of null appearing in public URLs

---

CHANGELOG.MD
met-web/package-lock.json
met-web/package.json
met-web/src/App.tsx
met-web/src/components/appLayouts/AuthenticatedLayout.tsx
met-web/src/components/appLayouts/PublicLayout.tsx
met-web/src/components/common/Layout/index.tsx
met-web/src/components/common/Navigation/Breadcrumb.tsx
met-web/src/components/layout/Header/InternalHeader.tsx
met-web/src/components/layout/SideNav/SideNav.tsx
met-web/src/components/tenantManagement/Create.tsx
met-web/src/components/tenantManagement/Detail.tsx
met-web/src/components/tenantManagement/Edit.tsx
met-web/src/components/tenantManagement/Listing.tsx
met-web/src/components/tenantManagement/TenantForm.tsx
met-web/src/routes/AuthenticatedRoutes.tsx
met-web/src/routes/UnauthenticatedRoutes.tsx
met-web/tests/unit/components/tenantManagement/CreateTenant.test.tsx
met-web/tests/unit/components/tenantManagement/EditTenant.test.tsx
met-web/tests/unit/components/tenantManagement/TenantDetail.test.tsx
met-web/tests/unit/components/tenantManagement/TenantListing.test.tsx

- **Feature** Use createBrowserRouter insead of \<BrowserRouter> in the App component [🎟️ DESENG-627](https://apps.itsm.gov.bc.ca/jira/browse/DESENG-627)
- Updated the App component to use the more flexible createBrowserRouter function instead of the <BrowserRouter> component
- This enables the use of [data router](https://reactrouter.com/en/6.23.0/routers/picking-a-router) functionality and other advanced features in the future, most notably the Blocker component
- Added the AutoBreadcrumbs component to the common components library, which will be used to generate breadcrumbs based on the current route
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

[To Main] Feature - DESENG-627 use createBrowserRouter() in-app

---

CHANGELOG.MD
met-web/src/components/appLayouts/AuthenticatedLayout.tsx
met-web/src/components/appLayouts/PublicLayout.tsx
met-web/src/components/common/Layout/index.tsx
met-web/src/components/common/index.tsx
met-web/src/components/engagement/new/view/index.tsx
met-web/src/routes/AuthenticatedRoutes.tsx
met-web/src/routes/UnauthenticatedRoutes.tsx

Issue #: [🎟️ DESENG-636](https://apps.itsm.gov.bc.ca/jira/browse/DESENG-636)
- **Feature** Add a new engagemnt view page at `/gdx/new-look/[name]/[language]` 
- Added a new page to view engagements using the new look for MET
- The page is available at `/gdx/new-look/[name]/[language]`
- The page is a work in progress and will be updated in the future

[To Main] Feature - DESENG-636 - Add new engagement view page

---

met-api/src/met_api/models/language_tenant_mapping.py
met-api/src/met_api/resources/language.py
met-api/src/met_api/services/language_service.py
met-api/src/met_api/utils/roles.py
met-api/tests/unit/services/test_language_service.py
met-web/src/apiManager/endpoints/index.ts
met-web/src/components/language/index.tsx
met-web/src/models/languageTenantMapping.ts
met-web/src/services/languageService/index.ts

- Add frontend language view 
- Update backend routes to use tenant short name, add authentication and CORS
*Remaining work:*
- Add tests
- Merge in changes from main
- Create migration to add EDIT_LANGUAGES to admin composite role

Feature/deseng623 - Add frontend, update backend routes to use tenant short name

---

CHANGELOG.MD
met-web/src/components/appLayouts/PublicLayout.tsx
met-web/src/components/common/Indicators/StatusChip.tsx
met-web/src/components/common/Indicators/index.ts
met-web/src/components/common/Input/Button.tsx
met-web/src/components/common/Input/index.tsx
met-web/src/components/common/Layout/index.tsx
met-web/src/components/common/Navigation/Link.tsx
met-web/src/components/common/Typography/Body.tsx
met-web/src/components/common/Typography/Headers.tsx
met-web/src/components/common/Typography/index.tsx
met-web/src/components/engagement/new/view/EngagementHero.tsx
met-web/src/components/engagement/new/view/index.tsx
met-web/src/components/engagement/view/EngagementBanner/BannerSection.tsx
met-web/src/components/engagement/view/EngagementView.tsx
met-web/src/components/engagement/view/widgets/Map/MapWidget.tsx
met-web/src/components/layout/Footer/index.tsx
met-web/src/routes/NotFound.tsx
met-web/src/routes/UnauthenticatedRoutes.tsx
met-web/tests/unit/components/engagement/engagement.test.tsx

Issue #:  [🎟️ DESENG-630](https://apps.itsm.gov.bc.ca/jira/browse/DESENG-630)
- **Feature** Add new header to "new look" engagement page
- Added a new hero image to the new engagement page
- Added a header overlaying the hero image
- The header uses the sponsor name, CTA message, and CTA URL from DESENG-629, as well as the engagement title, dates, and status
- Added new engagement status chips for use in the header
- Added link from the old engagement page offering the option to preview the new engagement page
- Added global width limit to the public view to avoid display issues on very wide screens
- **Task** De-duplicate link code and only use \<Link>s from the common/Navigation module
By submitting this pull request, I confirm that you can use, modify, copy, …

[To Main] DESENG-630 - Create header section for new engagement page

---

CHANGELOG.MD
met-web/src/components/appLayouts/PublicLayout.tsx
met-web/src/components/common/Layout/index.tsx
met-web/src/components/common/RichTextEditor/index.tsx
met-web/src/components/common/Typography/Body.tsx
met-web/src/components/engagement/form/EngagementFormTabs/EngagementForm.tsx
met-web/src/components/engagement/form/EngagementWidgets/Documents/StyledTreeItem.tsx
met-web/src/components/engagement/form/EngagementWidgets/Subscribe/constants.ts
met-web/src/components/engagement/new/view/EngagementDescription.tsx
met-web/src/components/engagement/new/view/EngagementHero.tsx
met-web/src/components/engagement/new/view/EngagementLoader.tsx
met-web/src/components/engagement/new/view/index.tsx
met-web/src/components/engagement/view/widgets/DocumentWidget.tsx
met-web/src/components/engagement/view/widgets/Events/EventsWidget.tsx
met-web/src/components/engagement/view/widgets/Events/VirtualSession.tsx
met-web/src/components/engagement/view/widgets/Map/MapWidget.tsx
met-web/src/components/engagement/view/widgets/Subscribe/SubscribeWidget.tsx
met-web/src/components/engagement/view/widgets/Timeline/TimelineWidgetView.tsx
met-web/src/components/engagement/view/widgets/Video/VideoWidgetView.tsx
met-web/src/components/engagement/view/widgets/WhoIsListeningWidget.tsx
met-web/src/routes/UnauthenticatedRoutes.tsx

Issue #: [🎟️ DESENG-631](https://apps.itsm.gov.bc.ca/jira/browse/DESENG-631)
- **Feature** Add engagement description to the engagement page
- Display engagement description on the new engagement page
- Display first widget of the engagement beside the description
- Limit text editor to remove disruptive formatting options

[To Main] Feature - DESENG 631: Add Engagement Description Block

---

CHANGELOG.MD
met-web/src/components/common/Indicators/StatusChip.tsx
met-web/src/components/common/Input/Button.tsx
met-web/src/components/common/Input/RichTextArea.tsx
met-web/src/components/common/Input/TextInput.tsx
met-web/src/components/common/Navigation/Link.tsx
met-web/src/components/common/RichTextEditor/index.tsx
met-web/src/components/common/Typography/Body.tsx
met-web/src/components/common/Typography/Headers.tsx
met-web/src/components/common/index.tsx
met-web/src/components/engagement/form/EngagementWidgets/Subscribe/constants.ts
met-web/src/components/engagement/new/view/EngagementContentTabs.tsx
met-web/src/components/engagement/new/view/EngagementDescription.tsx
met-web/src/components/engagement/new/view/EngagementHero.tsx
met-web/src/components/engagement/new/view/EngagementSurveyBlock.tsx
met-web/src/components/engagement/new/view/index.tsx
met-web/src/components/engagement/view/EmailModal.tsx
met-web/src/components/engagement/view/types.ts
met-web/src/components/engagement/view/widgets/Timeline/TimelineWidgetView.tsx
met-web/src/styles/Theme.ts

Issue #: [🎟️ DESENG-633](https://citz-gdx.atlassian.net/browse/DESENG-633)
- **Feature** Add a new survey block to the engagement page
- Added a survey block to the new engagement page matching the designs from UX
- The survey block displays side-by-side with the second widget of the engagement
- The survey block is not displayed if there is no survey and no second widget
- Customized the rich text editor/display to render links and h2 elements using the correct components
- Transitioned many new design system components to rely on Material theming for colors and typography,
allowing for areas with dark backgrounds to have light text and vice versa
- Moved useLoaderData() calls to within smaller components to reduce prop drilling, improve readability,
make it …

[To Main] DESENG 633: Engagement Survey Block

---

CHANGELOG.MD
met-web/src/components/engagement/listing/AdvancedSearch/SearchComponent.tsx
met-web/src/components/engagement/listing/index.tsx
met-web/src/components/engagement/new/create/index.tsx
met-web/src/routes/AuthenticatedRoutes.tsx

Issue #: [🎟️ DESENG-654](https://citz-gdx.atlassian.net/browse/DESENG-654)
- **Feature** Add a skeleton page for the new engagement authoring wizard
- Users are taken to the new page when pressing the "create engagement" button.
- This route will be updated in future tickets to include the full authoring wizard, and will eventually replace the old authoring flow.
- [Visual change only] Replaced some old components in the Engagement listing section to match new designs

[To Main] DESENG-654: Add skeleton for new Engagement Authoring page

---

CHANGELOG.MD
met-web/Dockerfile

Issue #: [🎟️ DESENG-665](https://citz-gdx.atlassian.net/browse/DESENG-665)
- **Hotfix** Fix MET-web CI build errors
- Update the `npm install` command in CI for the web app to use `--legacy-peer-deps`, resolving a dependency issue that was causing the build to fail

[Hotfix - To Main] DESENG 665: Fix MET-web CI build errors

---

CHANGELOG.MD
met-web/src/components/engagement/new/create/WizardLoader.tsx
met-web/src/components/engagement/new/create/index.tsx
met-web/src/components/engagement/new/create/languageLoader.tsx
met-web/src/routes/AuthenticatedRoutes.tsx

- **Feature** Admin authoring experience - language selector [🎟️ DESENG-657](https://citz-gdx.atlassian.net/browse/DESENG-657)
- Created loader for engagement creation wizard
- Created language selector field in engagement creation wizard

Feature/deseng657: Implemented language selector in engagement creation wizard

---

met-web/src/components/engagement/form/ActionContext.tsx
met-web/src/components/engagement/form/EngagementFormTabs/EngagementContent/EngagementContentContext.tsx
met-web/src/components/engagement/form/EngagementFormTabs/EngagementContent/SummaryTabContent.tsx
met-web/src/components/engagement/form/EngagementFormTabs/EngagementForm.tsx
met-web/src/components/engagement/form/EngagementFormTabs/EngagementTabsContext.tsx
met-web/src/components/engagement/form/EngagementFormWrapper.tsx
met-web/src/components/engagement/form/types.ts
met-web/src/components/engagement/new/view/EngagementLoader.tsx
met-web/src/components/imageUpload/imageUploadContext.tsx

Issue #: https://citz-gdx.atlassian.net/browse/DESENG-664
Fixed the engagement creation flow so that users are taken to the appropriate form page (with engagement ID) after engagement creation
Also updated various state variables so they properly reflect changes to the engagement state

[To Feature] DESENG 664: Fix engagement creation flow

---

CHANGELOG.MD
met-web/src/App.tsx
met-web/src/apiManager/endpoints/index.ts
met-web/src/components/appLayouts/AuthenticatedLayout.tsx
met-web/src/components/common/Layout/index.tsx
met-web/src/components/common/Navigation/DropdownMenu.tsx
met-web/src/components/engagement/listing/index.tsx
met-web/src/components/layout/Header/InternalHeader.tsx
met-web/src/components/layout/SideNav/SideNav.tsx
met-web/src/components/layout/SideNav/types.ts
met-web/src/routes/AuthenticatedRootRouteLoader.tsx
met-web/src/services/tenantService/index.tsx
met-web/tests/unit/components/factory.ts
met-web/tests/unit/components/header.test.tsx
met-web/tests/unit/components/sidenav.test.tsx

Issue #: [🎟️ DESENG-660](https://citz-gdx.atlassian.net/browse/DESENG-660)
- Redesigned the admin header to match the new design system
- Added a new dropdown to the header to allow users to switch between tenants
- Added a user menu, which for now only contains a logout button
- Added a "drawer" view for the tenant switcher and user menu on mobile
This is part of a larger feature branch for DESENG-660

[To Feature] DESENG-660 Part 2: Admin Header UI updates

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.MD
CONTRIBUTING.md

Issue #: https://citz-gdx.atlassian.net/browse/DESENG-651
- Update PR template to remove license-related contribution dislcaimer
- Add common components, more instructions, style guide to contributing.md

DESENG-651 Update pr template, contributing guide

---

CHANGELOG.MD
met-etl/Dockerfile
met-etl/container/user_code/Dockerfile

Issue #: https://citz-gdx.atlassian.net/browse/DESENG-677
- Update dagster versions for ETL service
**User Guide update ticket (if applicable):** N/A

DESENG-677 Update dagster versions to solve issue

---

CHANGELOG.MD
met-web/src/components/engagement/admin/view/AuthoringTab.tsx
met-web/src/components/engagement/admin/view/index.tsx
met-web/src/components/engagement/admin/view/types.tsx
met-web/src/components/layout/Footer/index.tsx
met-web/src/components/layout/SideNav/SideNav.tsx
met-web/src/utils/index.ts

…. Fixed a couple of issues with Footer and Admin SideNav as well.
Issue #: https://citz-gdx.atlassian.net/browse/DESENG-674
- Implemented authoring tab in admin engagement view
- Co-ordinated with Nat to build admin view index.tsx
- Used original data fetch config since I don't have Nat's loader
- Modified tab values to match hi-fi prototype
- Fixed an invalid prop in the footer
- Fixed a React key error in admin side nav
N/A

feature/deseng674: Implemented authoring tab to admin engagement view

---

.github/workflows/met-web-ci.yml
CHANGELOG.MD
met-web/Dockerfile
met-web/package-lock.json

Issue #: [🎟️ DESENG-682](https://citz-gdx.atlassian.net/browse/DESENG-682)
- **Task** Upgrade to Node v20
- Upgraded deployment / CI configs to reference Node v20

[To Main] Task - DESENG-682: Upgrade to node 20

---

CHANGELOG.MD
docs/MET_database_ERD.md
met-api/migrations/versions/70a410c85b24_removing_title_column_from_widget_video_.py
met-api/src/met_api/models/widget_translation.py
met-api/src/met_api/models/widget_video.py
met-api/src/met_api/schemas/schemas/video_widget_update.json
met-api/src/met_api/schemas/widget_translation.py
met-api/src/met_api/schemas/widget_video.py
met-api/src/met_api/services/widget_translation_service.py
met-api/src/met_api/services/widget_video_service.py
met-api/tests/unit/api/test_widget_video.py
met-api/tests/utilities/factory_utils.py
met-web/src/components/engagement/form/EngagementWidgets/Video/Form.tsx
met-web/src/components/engagement/old-view/widgets/Video/VideoWidgetView.tsx
met-web/src/models/videoWidget.ts
met-web/src/services/widgetService/VideoService/index.tsx
met-web/tests/unit/components/factory.ts
met-web/tests/unit/components/widgets/VideoWidget.test.tsx

Issue #: https://citz-gdx.atlassian.net/browse/DESENG-692
- Removed unneeded columns from db (title from widget_video table and associated translation column)
- Updated all other met_api and met_web logic to accomodate this
- Title is now pulled from widget table, not widget_video table
N/A

Feature/deseng692: Reverted to previous title logic for video widget

---

CHANGELOG.MD
met-web/src/components/common/Input/Select.tsx
met-web/src/components/common/RichTextEditor/RichEditorStyles.css
met-web/src/components/common/Typography/index.tsx
met-web/src/components/engagement/admin/config/EngagementCreateAction.tsx
met-web/src/components/engagement/old-view/widgets/Timeline/TimelineWidgetView.tsx
met-web/src/components/engagement/public/view/EngagementDescription.tsx
met-web/src/components/engagement/public/view/EngagementSurveyBlock.tsx
met-web/src/styles/Theme.ts

Issue #: https://citz-gdx.atlassian.net/browse/DESENG-694
- **Feature** New Timeline Widget designs
- Implemented Figma design
- Adjusted styling in Engagement views slightly to accommodate theme-aware widgets
https://citz-gdx.atlassian.net/browse/DESENG-720

DESENG-694: Update timeline widget design

---

CHANGELOG.MD
docs/MET_database_ERD.md
met-api/migrations/versions/917a911b6ca9_added_widget_listening_table_for_.py
met-api/src/met_api/models/__init__.py
met-api/src/met_api/models/widget_listening.py
met-api/src/met_api/models/widget_translation.py
met-api/src/met_api/resources/__init__.py
met-api/src/met_api/resources/widget_listening.py
met-api/src/met_api/schemas/schemas/listening_widget_update.json
met-api/src/met_api/schemas/widget_listening.py
met-api/src/met_api/schemas/widget_translation.py
met-api/src/met_api/services/widget_listening_service.py
met-api/src/met_api/services/widget_translation_service.py
met-api/tests/unit/api/test_widget_listening.py
met-api/tests/unit/api/test_widget_timeline.py
met-api/tests/utilities/factory_scenarios.py
met-api/tests/utilities/factory_utils.py
met-web/src/apiManager/endpoints/index.ts
met-web/src/components/engagement/admin/create/authoring/AuthoringSummary.tsx
met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/AddContactDrawer.tsx
met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/ContactInfoPaper.tsx
met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/WhoIsListeningContext.tsx
met-web/src/components/engagement/form/EngagementWidgets/WhoIsListening/WhoIsListeningForm.tsx
met-web/src/components/engagement/old-view/widgets/Map/MapWidget.tsx
met-web/src/components/engagement/old-view/widgets/Video/VideoWidgetView.tsx
met-web/src/components/engagement/old-view/widgets/WhoIsListeningWidget.tsx
met-web/src/components/imageUpload/index.tsx
met-web/src/models/listeningWidget.ts
met-web/src/routes/AuthenticatedRoutes.tsx
met-web/src/services/widgetService/ListeningService/index.tsx

Issue #: https://citz-gdx.atlassian.net/browse/DESENG-695
Issue #: https://citz-gdx.atlassian.net/browse/DESENG-692
Issue #: https://citz-gdx.atlassian.net/browse/DESENG-693
- New Who is Listening widget front end
- Implemented Figma design
- Added widget_listening table to db for widget instance data
- Added option to enter widget description text (below title, above contacts)
- Adjusted CSS to accomodate multiple viewports
- Added ARIA labels for accessibility
- Updated contact create/edit form
- Video Widget
- Changed icon colour from yellow to white to accomodate company branding requests
- Map Widget
- Adjusted viewport settings of expand map link to accomodate breakpoints of engagement view page
N/A

Feature/deseng695: Updated Who is Listening Widget, changed colour of Video Widget overlay logo, fixed media query for Map Widget expand link.

---

.github/workflows/analytics-api-cd.yml
.github/workflows/analytics-api-ci.yml
.github/workflows/deploy.yml
.github/workflows/met-api-cd.yml
.github/workflows/met-api-ci.yml
.github/workflows/met-cron-cd.yml
.github/workflows/met-cron-ci.yml
.github/workflows/met-etl-cd.yml
.github/workflows/met-web-cd.yml
.github/workflows/met-web-ci.yml
.github/workflows/notify-api-cd.yml
.github/workflows/notify-api-ci.yml
CHANGELOG.MD

Issue #: https://citz-gdx.atlassian.net/browse/DESENG-797
Related issue: https://github.com/actions/runner-images/issues/11101
- **Chore** Update GitHub Actions workflows to use ubuntu-latest instead of ubuntu-20.04
- This is to stay ahead of the deprecation of ubuntu-20.04 in GitHub Actions as of today's date
N/A

DESENG-797: Update GitHub Actions workflows to use ubuntu-latest instead of 20.04

---

CHANGELOG.MD
met-cron/config.py
met-cron/pre-hook-update-db.sh
met-cron/src/met_cron/services/closing_soon_mail_service.py
openshift/README.md
openshift/api/templates/configmap.yaml
openshift/api/templates/deploymentconfig-cron.yaml
openshift/api/values.yaml

Issue #: [🎟️ DESENG-811](https://citz-gdx.atlassian.net/browse/DESENG-811)
- **Feature** Add MET Cron job to OpenShift
- Added the met-cron deployment to the met-api helm chart.
- Removed an unneeded Service, as the Cron does not serve any traffic.
- Set up injection of HashiCorp Vault secrets to the Cron job
- Merged met-cron ConfigMap into the met-api ConfigMap, as they differed very little.
- Renamed config key "OFFSET_DAYS" to "CLOSING_SOON_EMAIL_ADVANCE_NOTICE_DAYS" to be more descriptive.
- Removed the old met-cron deployment YAML files.
**User Guide update ticket (if applicable):** *N/A*

DESENG-811: Add MET Cron deployment & config to MET API helm chart

---

CHANGELOG.MD
met-api/requirements.txt
met-etl/requirements.txt

Issue #: [🎟️ DESENG-677](https://citz-gdx.atlassian.net/browse/DESENG-677)
- **Bugfix** Add required dependencies for met-etl to requirements.txt 
- pin flask_restx to 1.3.0

DESENG-677: Add required dependencies for met-etl

---

CHANGELOG.MD
met-etl/src/etl_project/services/ops/survey_etl_service.py

Issue #: [🎟️ DESENG-677](https://citz-gdx.atlassian.net/browse/DESENG-677)
- **Bugfix** Fix survey ID access in MET ETL
- the load_survey function in the MET ETL pipeline now uses .scalar() instead of .first() to get the survey ID
- https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Result.scalar
**User Guide update ticket (if applicable):** _N/A_

DESENG-677-met-etl-fix-survey-id-access

---

.github/dependabot.yml
CHANGELOG.MD

Issue #: [🎟️ DESENG-812](https://citz-gdx.atlassian.net/browse/DESENG-812)
- **Feature**: Add Dependabot alerts for Github Actions 
- Added a Dependabot configuration file to automatically check for updates to Github Actions runner images and workflows.
If any updates are found, a pull request will be created to update the versions referenced in the workflows.
**User Guide update ticket (if applicable):** _N/A_

DESENG-812: Add automatic updates for Github Actions
